### ISSUE TITLE
Error running tests inheriting from XunitTestCase

### ISSUE THREAD

**Issue by ErikEJ** [xunit/xunit#1062]
When running the EF Core specification tests, I get this error:

[xUnit.net 00:00:00.5177689] Unable to de-serialize test case Microsoft.EntityFrameworkCore.Specification.Tests.GraphUpdatesWithIdentitySqlCeTest.Sever_optional_one_to_one_with_alternate_key(changeMechanism: 3): System.InvalidOperationException: Could not de-serialize type 'Microsoft.EntityFrameworkCore.Specification.Tests.TestUtilities.Xunit.SkipXunitTestCase' because it lacks a parameterless constructor.

Server stack trace: 
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 210
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue) in C:\BuildAgent\work\cb37e9acf085d108\src\common\XunitSerializationInfo.cs:line 110
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\BuildAgent\work\cb37e9acf085d108\src\common\SerializationHelper.cs:line 37
   at Xunit.Sdk.TestFrameworkExecutor`1.Deserialize(String value) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\TestFrameworkExecutor.cs:line 66
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Xunit.Abstractions.ITestFrameworkExecutor.Deserialize(String value)
   at Xunit.Xunit2.Deserialize(String value)
   at Xunit.XunitFrontController.Deserialize(String value)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.Deserialize(LoggerHelper logger, ITestFrameworkExecutor executor, TestCase testCase)

The offending class is here:
https://github.com/aspnet/EntityFramework/blob/c9b5916a4e0fff763febea00da793ebd4113632d/src/Microsoft.EntityFrameworkCore.Specification.Tests/TestUtilities/Xunit/SkipReasonTestCase.cs

Is this an EF or XUnit issue?

Using:
``
  <package id="xunit" version="2.2.0-beta4-build3444" targetFramework="net46" />
  <package id="xunit.abstractions" version="2.0.1" targetFramework="net46" />
  <package id="xunit.assert" version="2.2.0-beta4-build3444" targetFramework="net46" />
  <package id="xunit.core" version="2.2.0-beta4-build3444" targetFramework="net46" />
  <package id="xunit.extensibility.core" version="2.2.0-beta4-build3444" targetFramework="net46" />
  <package id="xunit.extensibility.execution" version="2.2.0-beta4-build3444" targetFramework="net46" />
  <package id="xunit.runner.visualstudio" version="2.2.0-beta4-build1194" targetFramework="net46" developmentDependency="true" />
``

**Comment by bradwilson** [comment]
It's an issue with whoever wrote `SkipReasonTestCase` (presumably the EF team).

TestCases must support serialization, or else they can't be used from within Visual Studio. The error indicates the core issue: a parameterless constructor must exist so that a serialized test case can be deserialized, and it must also implement the serialization methods. Since this test case derives from `XunitTestCase` and does not have any private state, it simply needs the empty constructor, which can be decorated with attributes to prevent people from calling it programatically, like the constructor on [XunitTestCase](https://github.com/xunit/xunit/blob/560c77c3a48571fef3e4f129d93107f57b673261/src/xunit.execution/Sdk/Frameworks/XunitTestCase.cs#L22-L29) does:

```csharp
/// <summary/>
[EditorBrowsable(EditorBrowsableState.Never)]
[Obsolete("Called by the de-serializer; should only be called by deriving classes for de-serialization purposes")]
public SkipReasonTestCase()
{
    // No way for us to get access to the message sink on the execution deserialization path, but that should
    // be okay, because we assume all the issues were reported during discovery.
    diagnosticMessageSink = new NullMessageSink();
}
```

If it contained any private data, it would override [`Serialize` and `Deserialize`](https://github.com/xunit/xunit/blob/560c77c3a48571fef3e4f129d93107f57b673261/src/xunit.execution/Sdk/Frameworks/TestMethodTestCase.cs#L263-L277) to store and retrieve that state.

**Comment by ErikEJ** [comment]
Thanks so much Brad, I will create an issue in the EF repo!
