### ISSUE TITLE
Bug: Returning a default ImmutableArray as part of a MemberData throws

### ISSUE THREAD

**Issue by jamesqo** [xunit/xunit#1064]
I ran into this while attempting to refactor the `ImmutableArray<T>` tests in corefx. Here's a simple repro:

```cs
        [Theory]
        [MemberData(nameof(ReverseData))]
        public void Reverse(IEnumerable<int> source)
        {
        }

        public static IEnumerable<object[]> ReverseData()
        {
            yield return new object[] { default(ImmutableArray<int>) };
        }
```

Attempting to run this test results in the following stack trace (copied from VS):

```
Test Name:	XunitTesting.UnitTest1.Reverse
Test FullName:	XunitTesting.UnitTest1.Reverse
Test Source:	 : line 0
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result StackTrace:	
at System.Collections.Immutable.ImmutableArray`1.ThrowInvalidOperationIfNotInitialized()
   at System.Collections.Immutable.ImmutableArray`1.System.Collections.IEnumerable.GetEnumerator()
   at System.Linq.Enumerable.<CastIterator>d__35`1.MoveNext()
   at System.Linq.Enumerable.<TakeIterator>d__199`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
Result Message:	System.InvalidOperationException : This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.

```

Looks like `GetEnumerator` is being called on the `ImmutableArray`, which in turn is causing it to throw because it's a default/null instance. Maybe there should be error handling setup in case `GetEnumerator` throws?

**Comment by jamesqo** [comment]
Ok, I think I found where the exception is coming from (albeit not having access to the full stack trace). `XunitTheoryTestCaseRunner` tries to resolve the display name [here](https://github.com/xunit/xunit/blob/297e3c74e6634d1cd67578ac571e13b8e1cbe098/src/xunit.execution/Sdk/Frameworks/Runners/XunitTheoryTestCaseRunner.cs#L87)

```
var theoryDisplayName = TestCase.TestMethod.Method.GetDisplayNameWithArguments(DisplayName, convertedDataRow, resolvedTypes);
```

That method is located [here,](https://github.com/xunit/xunit/blob/297e3c74e6634d1cd67578ac571e13b8e1cbe098/src/xunit.execution/Sdk/TypeUtility.cs#L137) and calls

```cs
displayValues[idx] = ParameterToDisplayValue(GetParameterName(parameterInfos, idx), arguments[idx]);
```

`ParameterToDisplayValue` calls `ArgumentFormatter.Format` on the object. `Format` detects that the object is an enumerable [here](https://github.com/xunit/assert.xunit/blob/master/Sdk/ArgumentFormatter.cs#L106), and calls `Cast`, `Take`, and `ToList` on it, which matches what is shown in the stack trace.

**Comment by jamesqo** [comment]
Nice, looks like this is already fixed (https://github.com/xunit/assert.xunit/pull/5). Happily closing this.
