### ISSUE TITLE
XunitFrontController.Find throws "Could not load file or assembly" error (.NET Core 1.1.0)

### ISSUE THREAD

**Issue by VivekRagunathan** [xunit/xunit#1073]
I am using the xUnit's backend (`XunitFrontController`) to read and execute tests with .NET Core 1.1.0. I have to point to and dynamically load an assembly that has my tests.

```csharp
using System;
using System.Reflection;
using System.Runtime.Loader;
using Xunit;
using Xunit.Abstractions;

public class Program
{
	public static void Main(string[] args)
	{
		try
		{
			// The test assembly path will be provided to my app dynamically at run time.
			var asmPath = @"C:\Temp\Tests.dll"; 
			var xfc = new XunitFrontController(AppDomainSupport.IfAvailable, asmPath);
			var sink = new XSink();
			xfc.Find(true, sink, TestFrameworkOptions.ForDiscovery());
		}
		catch (Exception ex)
		{
			Console.WriteLine($"ERROR! {ex.Message}");
			Console.WriteLine($"{ ex.StackTrace}");
		}

		Console.ReadLine();
	}

	public class XSink : IMessageSink
	{
		public bool OnMessage(IMessageSinkMessage message)
		{
			Console.WriteLine($"{message.GetType().Name} ... {message}");
			return true;
		}
	}
}
```

The `XunitFrontController` gets instantiated with the specified assembly path but when the `xfc.Find(true, sink, TestFrameworkOptions.ForDiscovery());` method is called, the following exception is thrown:

```
ERROR! Could not load file or assembly 'Tests, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
at Xunit.Sdk.ReflectionAssemblyInfo..ctor(String assemblyFileName) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Reflection\ReflectionAssemblyInfo.cs:line 34                                                               --- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Xunit.AppDomainManager_NoAppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility\AppDomain\AppDomainManager_NoAppDomain.cs:line 29
at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility\Frameworks\v2\Xunit2Discoverer.cs:line 92
at Xunit.Xunit2..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyTestAssemblyExists) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility\Frameworks\v2\Xunit2.cs:line 43             
at Xunit.XunitFrontController.CreateInnerController() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 107
at Xunit.XunitFrontController.get_InnerController() in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 81
at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 135           
at Xoo.Program.Main(String[] args) in C:\Projects\CLR\Xoo\Runner\Program.cs
```

This is my `project.json`:

```json
{
	"version": "1.0.0-*",
	"buildOptions": {
		"debugType": "portable",
		"emitEntryPoint": true
	},

	"dependencies": {
                "xunit": "2.2.0-beta2-build3300",
		"xunit.core": "2.2.0-beta2-build3300",
		"xunit.runner.utility": "2.2.0-beta2-build3300",
		"dotnet-test-xunit": "2.2.0-preview2-build1029",
                "System.Runtime.Loader": "4.3.0",
	},
	"testRunner": "xunit",
	"frameworks": {
		"netcoreapp1.1": {
			"dependencies": {
				"Microsoft.NETCore.App": {
					"type": "platform",
					"version": "1.1.0"
				}
			},
			"imports": "dnxcore50"
		}
	}
}
```

I found that if I insert this line somewhere before the `Find` method is called it works fine.

```csharp
var asm = AssemblyLoadContext.Default.LoadFromAssemblyPath(@"C:\Temp\Tests.dll");
```

**However, I can do the above since my test assembly is dynamically provided.**

_BTW I am not using Visual Studio. I am using Visual Studio Code and command line_.

Your help in resolving this issue is highly appreciated.

@bradwilson

**Comment by VivekRagunathan** [comment]
@bradwilson Any suggestions on this one?

**Comment by bradwilson** [comment]
As near as I can tell, this issue doesn't belong to xUnit.net. We do not control the behavior of assembly loading.

**Comment by bradwilson** [comment]
Closed for age.

**Comment by rui-ktei** [comment]
> As near as I can tell, this issue doesn't belong to xUnit.net. We do not control the behavior of assembly loading.

Hmm, but if you look at the stacktrace, there is this line
```
Xunit.Sdk.ReflectionAssemblyInfo..ctor(String assemblyFileName)
```
which invokes this
```
System.Reflection.Assembly.Load(AssemblyName assemblyRef)
```
There is a difference between `Assembly.Load` and `Assembly.LoadFile/LoadFrom` because `Assembly.Load` loads assembly in the context of host assembly. If I have build a host project, and import some testing project DLLs from somewhere else, putting them under the same execution folder, then XunitFrontController will throw this exception.

Is it possible for xunner to accept Assembly other than trying to load Assebmly itself?

**Comment by bradwilson** [comment]
@rui-ktei The architecture of v3 pushes this problem aside, because test projects become executable (a stand-alone .exe file in the case of .NET Framework, or a program that can be `dotnet run` with .NET Core). The "meta-runners" (like the console runner, MSBuild runner, VS plugin, etc.) will no longer attempt to load a DLL into their own process space; they will launch each project as the executable that it is, in a separate process.
