### ISSUE TITLE
XUnit Console Runner exit codes

### ISSUE THREAD

**Issue by mabead** [xunit/xunit#1081]
The [following](http://xunit.github.io/docs/getting-started-desktop#console-return-codes) page documents the exit codes of the console runner **for 2.2**. In particular, it says that an exit code of 2 means:

> The help page was shown, either because it was requested, or because the user did not provide any command line arguments. 

I am using 2.1 (the latest version released) and I had an exit code of 2 for the following run:

```
Running tests for 19602-0 'C:\ws\Deployment\EndToEndTests\19602\EndToEndTests\build\RunEndToEndTests.ps1'
  Discovering: OrckestraCommerce.WebHooks.EndToEndTests
  Discovered:  OrckestraCommerce.WebHooks.EndToEndTests
  Starting:    OrckestraCommerce.WebHooks.EndToEndTests
    OrckestraCommerce.WebHooks.EndToEndTests.CustomerEventsTests.CreateAndUpdateUser_CallsWebHookSubscriber [FAIL]
      System.AggregateException : One or more errors occurred.
      ---- ServiceStack.WebServiceException : SqlException
      ---- The following constructor parameters did not have matching fixture data: Fixture fixture
      Stack Trace:
        
        ----- Inner Stack Trace #1 (ServiceStack.WebServiceException) -----
           at ServiceStack.InternalExtensions.GetSyncResponse[T](Task`1 task)
        D:\a\1\s\tests\OrckestraCommerce.WebHooks.EndToEndTests\Fixture.cs(70,0): at OrckestraCommerce.WebHooks.EndToEndTests.Fixture.CreateCustomer(String scopeId)
        D:\a\1\s\tests\OrckestraCommerce.WebHooks.EndToEndTests\Fixture.cs(32,0): at OrckestraCommerce.WebHooks.EndToEndTests.Fixture..ctor()
        ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
        
    OrckestraCommerce.WebHooks.EndToEndTests.CartEventsTests.PlayWithCart_CallsWebHookSubscriber [FAIL]
      ServiceStack.WebServiceException : InvalidOperationException
      Stack Trace:
           at ServiceStack.InternalExtensions.GetSyncResponse[T](Task`1 task)
        D:\a\1\s\tests\OrckestraCommerce.WebHooks.EndToEndTests\CartEventsTests.cs(84,0): at OrckestraCommerce.WebHooks.EndToEndTests.CartEventsTests.GetAnyProductInScope(String cultureName, String scope)
        D:\a\1\s\tests\OrckestraCommerce.WebHooks.EndToEndTests\CartEventsTests.cs(53,0): at OrckestraCommerce.WebHooks.EndToEndTests.CartEventsTests.PlayWithCart_CallsWebHookSubscriber()
  Finished:    OrckestraCommerce.WebHooks.EndToEndTests
=== TEST EXECUTION SUMMARY ===
   OrckestraCommerce.WebHooks.EndToEndTests  Total: 2, Errors: 0, Failed: 2, Skipped: 0, Time: 9.179s
```

Clearly, the exit code documented do not reflect the exit codes of 2.1 (the latest official release).

So my question is: what do the exit code of 2.1 actually mean?

**Comment by bradwilson** [comment]
They aren't 100% predictable, but they usually mean the number of failed tests.

**Comment by mabead** [comment]
Thanks @bradwilson. I think this should be documented [here](http://xunit.github.io/docs/getting-started-desktop#console-return-codes). I got caught by this mismatch from 2.1 and 2.2.

**Comment by bradwilson** [comment]
It's not documented because it's not 100% predictable.
