### ISSUE TITLE
Exception thrown in finally block means assertion failures aren't printed to the console

### ISSUE THREAD

**Issue by hughbe** [xunit/xunit#1196]
```
try
{
    Assert.Equal(0, 2);
}
finally
{
    throw new DivideByZeroException();
}
```

This only prints:
```
      System.DivideByZeroException : Attempted to divide by zero.
        Stack Trace:
              at System.Net.Tests.SimpleHttpTests.<ResponseOutputStream_WriteTooMuchOrTooLittle_ThrowsInvalidOperationException>d__24.MoveNext()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
           --- End of stack trace from previous location where exception was thrown ---
              at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
              at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
              at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

I suggest this also show the assertion failure - this is the actual cause of the failure

**Comment by bradwilson** [comment]
Unfortunately, this is like asking that the ground stays dry when it's pouring rain: wishing will not make it so. :-p

Assertions are just methods that throw exceptions. If you intercept the exception before we have a chance to see it, and replace it with something different, there's no way we can know that this happened.

**Comment by hughbe** [comment]
Yup, dammit! Annoying because the assertion failure is the cause of the disposal failure. I had an image in my mind that we track all assertion failures in a hashtable or something. Was getting assertion failures confused with the whole test failing.
