### ISSUE TITLE
Types with duplicate names cause fatal exception

### ISSUE THREAD

**Issue by philn5d** [xunit/xunit#1233]
XUnit 2.02 and VS 14 using test runner. No ReSharper.

vstest.discoveryengine.x86.exe keeps running after this exception:

```
------ Discover test started ------
[xUnit.net 00:00:00.0695166] Exception discovering tests from Emmis.TagStation.Tests: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Xunit.DiaSessionWrapperHelper..ctor(String assemblyFileName)$$RethrowMarker$$   at ExceptionExtensions.RethrowWithNoStackTraceLoss(Exception ex)
   at Xunit.AppDomainManager_AppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args)
   at Xunit.DiaSessionWrapper..ctor(String assemblyFilename)
   at Xunit.VisualStudioSourceInformationProvider..ctor(String assemblyFileName)
   at Xunit.XunitFrontController..ctor(AppDomainSupport appDomainSupport, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticMessageSink)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IEnumerable`1 sources, LoggerHelper logger, Func`4 visitorFactory, Action`4 visitComplete)
========== Discover test finished: 0 found (0:00:00.11) ==========
```

which causes no tests to be found in the entire project.
and build failures on subsequent ReBuilds.

(obfuscated)
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to copy file "....dll" to "....dll". The process cannot access the file '....dll' because it is being used by another process.	...	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	3963	
Error		Could not copy "....dll" to "...dll". Exceeded retry count of 10. Failed.	...	C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets	3963	
```

in which case I have to manually kill vstest.discoveryengine.x86.exe to rebuild the sln or otherwise proceed.

The code that is causing the exception in the first place:

```C#
using System;
using System.Collections.Generic;
using Xunit;

namespace Tests
{
    public class MyTests
    {
        List<dynamic> _list = new List<dynamic>();
        
        //seems to be the catalyst, has to be dynamic
        Action<dynamic> someOtherAction = o => { };

        //but only in conjunction with this
        Action<dynamic, List<dynamic>> seemsToCauseTheProblem = (o, l) => l.Add(o);

        public MyTests()
        {
            //when I do this, it hurts
            someOtherAction = o => { _list.Add(o); };
        }

        [Fact]
        public void ThatsSomeTest()
        {
            //nothing necessary here to cause the problem
        }
    }
}
```

**Comment by bradwilson** [comment]
The issue is that we're seeing two types with the same name (`Tests.MyTests+<>o__3`) which is causing [this line of code](https://github.com/xunit/xunit/blob/139de6ffff84a8efb127295c26348d092d1fb6fd/src/xunit.runner.utility/Utility/DiaSessionWrapperHelper.cs#L73) to throw an exception.

I'm working on a solution...
