### ISSUE TITLE
System.ArgumentException

### ISSUE THREAD

**Issue by gt2847c** [xunit/xunit#1316]
I looked through the open/closed items and haven't seen this (hopefully didn't overlook something)

Description:
When xunit VS test runner executes batch tests following build, Run All Tests, or running a subset of tests, a System.ArgumentException is thrown when certain tests are enabled.  It appears to be triggered when tests make use of Telerik JustMock, but Telerik's support did testing and evaluation points to this is a problem within xunit and not JustMock as they are unable to reproduce the problem with MSTest/MSTestv2 (they were able to reproduce the problem with xunit).  [See here for thread](http://www.telerik.com/forums/xunit-justmock-fatal-error---system-argumentexception).  The exception has not occurred when running individual tests (right click Run Selected Test), even those that trigger the event in batch.  To test this, I configured all unit tests to "Skip" except for a single test containing a specific Mock.Create<TaskService>().  Mocking items such as log4net ILog does not trigger it.
Other items of notice:
When all tests are enabled, the tests run and show as passed, but some subset of them show up in the Test Explorer window as grayed out.  They show as green "Passed" and have no errors in the details block of the Test Explorer.  The only indication other than the fact that they are grayed out is a message in the VS status bar "Unexpected error detected.  Check the Tests Output Pane for details."

Details:
VS 2017 Enterprise 15.2 (26430.12) Release
xunit 2.2
xunit.runner.visualstudio 2.2.0
JustMock 2017.2.530.3
Windows 10 Enterprise 1703 (15063.332)

Test output (shortened to remove all the "skips") - Test run triggered with Build (typically the same result for Run All).  Not every run will trigger the event, but does it so frequently that a clean run is an unusual occurrence..
```
------ Run test started ------
[xUnit.net 00:00:00.2451875]   Discovering: UnitTests
[xUnit.net 00:00:00.8848961]   Discovered:  UnitTests
[xUnit.net 00:00:01.2138083]   Starting:    UnitTests
[xUnit.net 00:00:02.2411832]     [FATAL ERROR] System.ArgumentException
[xUnit.net 00:00:02.2439611]       System.ArgumentException : 'this' type cannot be an interface itself.
[xUnit.net 00:00:02.2459056]       Stack Trace:
[xUnit.net 00:00:02.2466309]         
[xUnit.net 00:00:02.2472174]         Server stack trace: 
[xUnit.net 00:00:02.2477555]            at System.RuntimeTypeHandle.VerifyInterfaceIsImplemented(RuntimeTypeHandle handle, RuntimeTypeHandle interfaceHandle)
[xUnit.net 00:00:02.2483485]            at System.RuntimeTypeHandle.VerifyInterfaceIsImplemented(RuntimeTypeHandle interfaceHandle)
[xUnit.net 00:00:02.2488751]            at System.RuntimeType.GetInterfaceMap(Type ifaceType)
[xUnit.net 00:00:02.2494631]            at Telerik.JustMock.Core.MockingUtil.IsImplementedBy(MethodInfo interfaceMethod, MethodBase implMethod)
[xUnit.net 00:00:02.2500089]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.MatchTestClassDispose(MethodBase method, String[] testMethodAttributes)
[xUnit.net 00:00:02.2507104]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.<>c__DisplayClass31.<SetupStandardHierarchicalTestStructure>b__1f(MethodBase method)
[xUnit.net 00:00:02.2514609]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.<>c__DisplayClassa.<FindTestMethod>b__9(RepositoryOperationsBase repo)
[xUnit.net 00:00:02.2519930]            at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
[xUnit.net 00:00:02.2524022]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.<FindTestMethod>b__8(MethodBase method)
[xUnit.net 00:00:02.2527720]            at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
[xUnit.net 00:00:02.2531123]            at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
[xUnit.net 00:00:02.2534255]            at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
[xUnit.net 00:00:02.2537421]            at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
[xUnit.net 00:00:02.2540741]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.FindTestMethod(Int32& repoIdx, RepositoryOperationsBase& entryOps)
[xUnit.net 00:00:02.2544121]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.ResolveRepository(UnresolvedContextBehavior unresolvedContextBehavior)
[xUnit.net 00:00:02.2547353]            at Telerik.JustMock.Core.Context.MockingContext.ResolveRepository(UnresolvedContextBehavior unresolvedContextBehavior)
[xUnit.net 00:00:02.2550541]            at Telerik.JustMock.Core.ProfilerInterceptor.DispatchInvocation(Invocation invocation)
[xUnit.net 00:00:02.2554163]            at Telerik.JustMock.Core.ProfilerInterceptor.InterceptCall(RuntimeTypeHandle typeHandle, RuntimeMethodHandle methodHandle, Object[] data)
[xUnit.net 00:00:02.2557189]            at System.MarshalByRefObject..ctor()
[xUnit.net 00:00:02.2560196]            at System.IO.Stream..ctor()
[xUnit.net 00:00:02.2563450]            at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
[xUnit.net 00:00:02.2566894]            at System.IO.MemoryStream..ctor(Byte[] buffer)
[xUnit.net 00:00:02.2570691]            at System.Runtime.Remoting.Messaging.SmuggledMethodReturnMessage.FixupForNewAppDomain()
[xUnit.net 00:00:02.2574610]            at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(IMessage reqMsg)
[xUnit.net 00:00:02.2577805]         
[xUnit.net 00:00:02.2580838]         Exception rethrown at [0]: 
[xUnit.net 00:00:02.2584149]            at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
[xUnit.net 00:00:02.2587327]            at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
[xUnit.net 00:00:02.2607176] Catastrophic failure: System.ArgumentException : 'this' type cannot be an interface itself.
[xUnit.net 00:00:02.6030109]   Finished:    UnitTests
========== Run test finished: 35 run (0:00:02.7030692) ==========

```
Test that triggers the event (the most simplistic test):
```
        [Fact]
        public void TaskManager_NullLog_ArgumentNullException()
        {
            ILog nullLog = null;
            var taskService = Mock.Create<TaskService>();

            Assert.Throws<ArgumentNullException>(
                () => new TaskManager(nullLog, taskService, _validTaskName, _validExecutable));
        }
```

The test above can be whittled down to just the Mock.Create<TaskService>(); call and this is sufficient to trigger the event.

**Comment by bradwilson** [comment]
It sounds like JustMock is not safe for Task-based parallelization. This is a unique feature of xUnit.net that doesn't exist in MSTest, to run multiple tests in parallel (for better performance).

You can verify that by following these [directions](https://xunit.github.io/docs/configuring-with-json.html) to add a config file and set `parallelizeTestCollections` to `false`. If everything passes after doing this, then you know that fault is with JustMock not being Task-safe.

**Comment by gt2847c** [comment]
Added the json file and disabled parallelizeTestCollections and the error is still happening.  Additionally it appears to only be running some of the tests and not all of them.  There are 35 total tests at this point and it's running between 28 and 34 when I do a build or run all tests.

To make sure that I did this properly, here's the contents of the xunit.runner.json file:
```
{
  "parallelizeTestCollections":  false
}
```
Rebuild Solution:
```
------ Discover test started ------
[xUnit.net 00:00:00.2600951]   Discovering: UnitTests
[xUnit.net 00:00:00.5788860]   Discovered:  UnitTests
========== Discover test finished: 35 found (0:00:00.8216952) ==========
------ Run test started ------
[xUnit.net 00:00:00.2595722]   Discovering: UnitTests
[xUnit.net 00:00:00.9357532]   Discovered:  UnitTests
[xUnit.net 00:00:01.2488351]   Starting:    UnitTests
[xUnit.net 00:00:02.8133041]     [FATAL ERROR] System.ArgumentException
[xUnit.net 00:00:02.8162772]       System.ArgumentException : 'this' type cannot be an interface itself.
[xUnit.net 00:00:02.8182471]       Stack Trace:
[xUnit.net 00:00:02.8189153]         
[xUnit.net 00:00:02.8195724]         Server stack trace: 
[xUnit.net 00:00:02.8202597]            at System.RuntimeTypeHandle.VerifyInterfaceIsImplemented(RuntimeTypeHandle handle, RuntimeTypeHandle interfaceHandle)
[xUnit.net 00:00:02.8208974]            at System.RuntimeTypeHandle.VerifyInterfaceIsImplemented(RuntimeTypeHandle interfaceHandle)
[xUnit.net 00:00:02.8215096]            at System.RuntimeType.GetInterfaceMap(Type ifaceType)
[xUnit.net 00:00:02.8221397]            at Telerik.JustMock.Core.MockingUtil.IsImplementedBy(MethodInfo interfaceMethod, MethodBase implMethod)
[xUnit.net 00:00:02.8227314]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.MatchTestClassDispose(MethodBase method, String[] testMethodAttributes)
[xUnit.net 00:00:02.8233681]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.<>c__DisplayClass31.<SetupStandardHierarchicalTestStructure>b__1f(MethodBase method)
[xUnit.net 00:00:02.8239340]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.<>c__DisplayClassa.<FindTestMethod>b__9(RepositoryOperationsBase repo)
[xUnit.net 00:00:02.8245000]            at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
[xUnit.net 00:00:02.8250126]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.<FindTestMethod>b__8(MethodBase method)
[xUnit.net 00:00:02.8254691]            at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
[xUnit.net 00:00:02.8258719]            at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
[xUnit.net 00:00:02.8263598]            at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
[xUnit.net 00:00:02.8268575]            at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
[xUnit.net 00:00:02.8274750]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.FindTestMethod(Int32& repoIdx, RepositoryOperationsBase& entryOps)
[xUnit.net 00:00:02.8279173]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.ResolveRepository(UnresolvedContextBehavior unresolvedContextBehavior)
[xUnit.net 00:00:02.8284121]            at Telerik.JustMock.Core.Context.MockingContext.ResolveRepository(UnresolvedContextBehavior unresolvedContextBehavior)
[xUnit.net 00:00:02.8288166]            at Telerik.JustMock.Core.MocksRepository.GetMockMixin(Object obj, Type objType)
[xUnit.net 00:00:02.8292869]            at Telerik.JustMock.Core.Invocation..ctor(Object instance, MethodBase method, Object[] args)
[xUnit.net 00:00:02.8297050]            at Telerik.JustMock.Core.ProfilerInterceptor.InterceptCall(RuntimeTypeHandle typeHandle, RuntimeMethodHandle methodHandle, Object[] data)
[xUnit.net 00:00:02.8302140]            at System.MarshalByRefObject.GetIdentity(MarshalByRefObject obj, Boolean& fServer)
[xUnit.net 00:00:02.8306393]            at System.Runtime.Remoting.IdentityHolder.FindOrCreateServerIdentity(MarshalByRefObject obj, String objURI, Int32 flags)
[xUnit.net 00:00:02.8311603]            at System.Runtime.Remoting.RemotingServices.GetOrCreateIdentity(MarshalByRefObject Obj, String ObjURI, Boolean isInitializing)
[xUnit.net 00:00:02.8316577]            at System.Runtime.Remoting.RemotingServices.MarshalInternal(MarshalByRefObject Obj, String ObjURI, Type RequestedType, Boolean updateChannelData, Boolean isInitializing)
[xUnit.net 00:00:02.8321978]            at System.Runtime.Remoting.RemotingServices.MarshalInternal(MarshalByRefObject Obj, String ObjURI, Type RequestedType, Boolean updateChannelData)
[xUnit.net 00:00:02.8326119]            at System.Runtime.Remoting.RemotingServices.MarshalInternal(MarshalByRefObject Obj, String ObjURI, Type RequestedType)
[xUnit.net 00:00:02.8331901]            at System.Runtime.Remoting.Messaging.MessageSmuggler.FixupArg(Object arg, ArrayList& argsToSerialize)
[xUnit.net 00:00:02.8337629]            at System.Runtime.Remoting.Messaging.MessageSmuggler.FixupArgs(Object[] args, ArrayList& argsToSerialize)
[xUnit.net 00:00:02.8344023]            at System.Runtime.Remoting.Messaging.SmuggledMethodCallMessage..ctor(IMethodCallMessage mcm)
[xUnit.net 00:00:02.8348531]            at System.Runtime.Remoting.Messaging.SmuggledMethodCallMessage.SmuggleIfPossible(IMessage msg)
[xUnit.net 00:00:02.8352503]            at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(IMessage reqMsg)
[xUnit.net 00:00:02.8355983]         
[xUnit.net 00:00:02.8359416]         Exception rethrown at [0]: 
[xUnit.net 00:00:02.8363047]            at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
[xUnit.net 00:00:02.8366877]            at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
[xUnit.net 00:00:04.0637010]   Finished:    UnitTests
========== Run test finished: 30 run (0:00:04.148668) ==========
```

Another dump - Run All:
```
------ Run test started ------
[xUnit.net 00:00:00.2489634]   Discovering: UnitTests
[xUnit.net 00:00:00.8930313]   Discovered:  UnitTests
[xUnit.net 00:00:01.2228715]   Starting:    UnitTests
[xUnit.net 00:00:03.7437478]     [FATAL ERROR] System.ArgumentException
[xUnit.net 00:00:03.7467030]       System.ArgumentException : 'this' type cannot be an interface itself.
[xUnit.net 00:00:03.7486700]       Stack Trace:
[xUnit.net 00:00:03.7493967]         
[xUnit.net 00:00:03.7500205]         Server stack trace: 
[xUnit.net 00:00:03.7508050]            at System.RuntimeTypeHandle.VerifyInterfaceIsImplemented(RuntimeTypeHandle handle, RuntimeTypeHandle interfaceHandle)
[xUnit.net 00:00:03.7515740]            at System.RuntimeTypeHandle.VerifyInterfaceIsImplemented(RuntimeTypeHandle interfaceHandle)
[xUnit.net 00:00:03.7521736]            at System.RuntimeType.GetInterfaceMap(Type ifaceType)
[xUnit.net 00:00:03.7527706]            at Telerik.JustMock.Core.MockingUtil.IsImplementedBy(MethodInfo interfaceMethod, MethodBase implMethod)
[xUnit.net 00:00:03.7533577]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.MatchTestClassDispose(MethodBase method, String[] testMethodAttributes)
[xUnit.net 00:00:03.7614647]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.<>c__DisplayClass31.<SetupStandardHierarchicalTestStructure>b__1f(MethodBase method)
[xUnit.net 00:00:03.7621970]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.<>c__DisplayClassa.<FindTestMethod>b__9(RepositoryOperationsBase repo)
[xUnit.net 00:00:03.7629250]            at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
[xUnit.net 00:00:03.7635160]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.<FindTestMethod>b__8(MethodBase method)
[xUnit.net 00:00:03.7640740]            at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
[xUnit.net 00:00:03.7646703]            at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
[xUnit.net 00:00:03.7652465]            at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
[xUnit.net 00:00:03.7659219]            at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
[xUnit.net 00:00:03.7665841]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.FindTestMethod(Int32& repoIdx, RepositoryOperationsBase& entryOps)
[xUnit.net 00:00:03.7671642]            at Telerik.JustMock.Core.Context.HierarchicalTestFrameworkContextResolver.ResolveRepository(UnresolvedContextBehavior unresolvedContextBehavior)
[xUnit.net 00:00:03.7676927]            at Telerik.JustMock.Core.Context.MockingContext.ResolveRepository(UnresolvedContextBehavior unresolvedContextBehavior)
[xUnit.net 00:00:03.7682537]            at Telerik.JustMock.Core.ProfilerInterceptor.DispatchInvocation(Invocation invocation)
[xUnit.net 00:00:03.7688074]            at Telerik.JustMock.Core.ProfilerInterceptor.InterceptCall(RuntimeTypeHandle typeHandle, RuntimeMethodHandle methodHandle, Object[] data)
[xUnit.net 00:00:03.7692903]            at System.MarshalByRefObject..ctor()
[xUnit.net 00:00:03.7698333]            at System.IO.Stream..ctor()
[xUnit.net 00:00:03.7703152]            at System.IO.MemoryStream..ctor(Int32 capacity)
[xUnit.net 00:00:03.7707393]            at System.IO.MemoryStream..ctor()
[xUnit.net 00:00:03.7713376]            at System.AppDomain.Serialize(Object o)
[xUnit.net 00:00:03.7719789]            at System.AppDomain.MarshalObject(Object o)
[xUnit.net 00:00:03.7723910]            at System.Threading.Thread.InternalCrossContextCallback(Context ctx, IntPtr ctxID, Int32 appDomainID, InternalCrossContextDelegate ftnToCall, Object[] args)
[xUnit.net 00:00:03.7727730]            at System.Runtime.Remoting.Channels.CrossAppDomainSink.DoTransitionDispatch(Byte[] reqStmBuff, SmuggledMethodCallMessage smuggledMcm, SmuggledMethodReturnMessage& smuggledMrm)
[xUnit.net 00:00:03.7731203]            at System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage(IMessage reqMsg)
[xUnit.net 00:00:03.7734329]         
[xUnit.net 00:00:03.7737455]         Exception rethrown at [0]: 
[xUnit.net 00:00:03.7741080]            at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
[xUnit.net 00:00:03.7744427]            at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
[xUnit.net 00:00:03.7747843]            at MessageSinkMessageExtensions.Dispatch[TMessage](IMessageSinkMessage message, HashSet`1 messageTypes, MessageHandler`1 callback)
[xUnit.net 00:00:03.7751320]            at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
[xUnit.net 00:00:03.7755087]            at System.Runtime.Remoting.Messaging.StackBuilderSink.PrivateProcessMessage(RuntimeMethodHandle md, Object[] args, Object server, Object[]& outArgs)
[xUnit.net 00:00:03.7758414]            at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
[xUnit.net 00:00:03.7761510]         
[xUnit.net 00:00:03.7764864]         Exception rethrown at [1]: 
[xUnit.net 00:00:03.7768178]            at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
[xUnit.net 00:00:03.7772200]            at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
[xUnit.net 00:00:03.8426171]     [FATAL ERROR] System.ArgumentException
[xUnit.net 00:00:04.1074492]   Finished:    UnitTests
========== Run test finished: 34 run (0:00:04.2097283) ==========
```

**Comment by bradwilson** [comment]
Please re-open with a repro project.

**Comment by zein-makki** [comment]
We were able to solve the same issue using the `-noappdomain` switch in the xunit console runner (Or the alternative `denied` in the json configuration).  

@bradwilson Any idea of how the app domains can be related to this issue ?

**Comment by bradwilson** [comment]
Seeing app domains involved in the problem isn't too surprising given the bottom of the stack trace. Otherwise, without a repro project it's impossible for me to guess exactly what's going on, but I'm still leaning towards the issue being JustMock.
