### ISSUE TITLE
CSC : warning AD0001: Analyzer 'Xunit.Analyzers.InlineDataShouldBeUniqueWithinTheory' threw an exception of type 'System.InvalidOperationException' with message 'This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.'

### ISSUE THREAD

**Issue by paulomorgado** [xunit/xunit#1324]
I'm getting these exceptions thrown by the 0.4.0 analyzer on Visual Studio 2017 Update 2:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Warning	AD0001	Analyzer 'Xunit.Analyzers.InlineDataShouldBeUniqueWithinTheory' threw an exception of type 'System.InvalidOperationException' with message 'This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.'.	Foo.Tests		1	Active	Analyzer 'Xunit.Analyzers.InlineDataShouldBeUniqueWithinTheory' threw the following exception:
'Exception occurred with following context:
Compilation: Foo.Tests
ISymbol: TestFoo (Method)

System.InvalidOperationException: This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.
   at System.Collections.Immutable.ImmutableArray`1.ThrowInvalidOperationIfNotInitialized()
   at System.Collections.Immutable.ImmutableArray`1.System.Collections.IEnumerable.GetEnumerator()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at Xunit.Analyzers.InlineDataShouldBeUniqueWithinTheory.InlineDataUniquenessComparer.GetFlattenedArgumentPrimitives(IEnumerable`1 arguments)
   at Xunit.Analyzers.InlineDataShouldBeUniqueWithinTheory.InlineDataUniquenessComparer.GetFlattenedArgumentPrimitives(IEnumerable`1 arguments)
   at Xunit.Analyzers.InlineDataShouldBeUniqueWithinTheory.InlineDataUniquenessComparer.GetHashCode(AttributeData attributeData)
   at System.Collections.Generic.HashSet`1.InternalGetHashCode(T item)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at Xunit.Analyzers.InlineDataShouldBeUniqueWithinTheory.AnalyzeInlineDataAttributesWithinTheory(SymbolAnalysisContext context, IEnumerable`1 inlineDataAttributes)
   at Xunit.Analyzers.InlineDataShouldBeUniqueWithinTheory.AnalyzeMethod(SymbolAnalysisContext context, CompilationTypes compilationTypes)
   at Xunit.Analyzers.InlineDataShouldBeUniqueWithinTheory.<>c__DisplayClass2_0.<Initialize>b__1(SymbolAnalysisContext symbolContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass37_0.<ExecuteSymbolActionsCore>b__0()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

As far as I can see, it might be related to inline data.

**Comment by marcind** [comment]
Could you provide the declaration of your `TestFoo` method (the method signature and all the `InlineData` attributes)?

**Comment by wachulski** [comment]
While trying to establish the root cause I found that #1064 might be related somehow.

**Comment by wachulski** [comment]
I also spotted another flaw reported here: #1327.

**Comment by paulomorgado** [comment]
Something like:

```c#
[Theory]
[InlineData(null)]
[InlineData("")]
public void TestFoo(string data)
/// ...
```

**Comment by wachulski** [comment]
Thanks for the input. Oh dear, honestly, I expected a sophisticated edge case and it seems it's basics that crushes the analyzer. Fixing to be started shortly.

**Comment by marcind** [comment]
Fix available in [v.0.5.0](https://github.com/xunit/xunit.analyzers/releases/tag/v0.5.0)
