### ISSUE TITLE
Is xunit.runner.msbuild supposed to support VS2017 .NET Core xunit test project with msbuild.exe?

### ISSUE THREAD

**Issue by xied75** [xunit/xunit#1326]
Sorry if I missed this somewhere, I see there are some issues related to msbuild but still can't figure out.

To re-pro:

1, Visual Studio 2017 -> New Project -> .NET Core -> xUnit Test project.
2, following https://xunit.github.io/docs/running-tests-in-msbuild.html to add nuget package and modify csproj file pointing to test dll.
3, according to **Test Runner Compatibility**, update other nuget packages to higher version:
```
<PackageReference Include="xunit" Version="2.3.0-beta4-build3710" />
<PackageReference Include="xunit.runner.msbuild" Version="2.3.0-beta4-build3710" />
```
4, open a powershell console, run
```
PS C:\scratch\XUnitTestProject1\XUnitTestProject1> & 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe' /t:test
```

Expected:
Test discovered and run.

Result:
```
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 19/06/2017 12:10:02.
Project "C:\scratch\XUnitTestProject1\XUnitTestProject1\XUnitTestProject1.csproj" on node 1 (test target(s)).
Test:
  xUnit.net MSBuild Runner (32-bit Desktop .NET 4.0.30319.42000)
C:\scratch\XUnitTestProject1\XUnitTestProject1\XUnitTestProject1.csproj(20,5): error : System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, V
ersion=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
C:\scratch\XUnitTestProject1\XUnitTestProject1\XUnitTestProject1.csproj(20,5): error :    at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, In
tPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
C:\scratch\XUnitTestProject1\XUnitTestProject1\XUnitTestProject1.csproj(20,5): error :    at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int
32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
C:\scratch\XUnitTestProject1\XUnitTestProject1\XUnitTestProject1.csproj(20,5): error :    at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 m
ethodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
C:\scratch\XUnitTestProject1\XUnitTestProject1\XUnitTestProject1.csproj(20,5): error :    at System.Reflection.CustomAttributeData..ctor(RuntimeModule scope, CustomAttrib
uteRecord caRecord)
C:\scratch\XUnitTestProject1\XUnitTestProject1\XUnitTestProject1.csproj(20,5): error :    at System.Reflection.CustomAttributeData.GetCustomAttributes(RuntimeModule modul
e, Int32 tkTarget)
C:\scratch\XUnitTestProject1\XUnitTestProject1\XUnitTestProject1.csproj(20,5): error :    at System.Reflection.CustomAttributeData.GetCustomAttributesInternal(RuntimeAsse
mbly target)
C:\scratch\XUnitTestProject1\XUnitTestProject1\XUnitTestProject1.csproj(20,5): error :    at System.Reflection.RuntimeAssembly.GetCustomAttributesData()
C:\scratch\XUnitTestProject1\XUnitTestProject1\XUnitTestProject1.csproj(20,5): error :    at System.Reflection.Assembly.get_CustomAttributes()
C:\scratch\XUnitTestProject1\XUnitTestProject1\XUnitTestProject1.csproj(20,5): error :    at Xunit.Sdk.ReflectionAssemblyInfo.GetCustomAttributes(String assemblyQualified
AttributeTypeName)
...
```

So my question: is this usage supported? Or I did something wrong somewhere?

Best regards,

Dong

**Comment by bradwilson** [comment]
We experimented with making this work, but the plugin model for .NET Core MSBuild just wasn't going to be able to get things running correct.

For .NET Core MSBuild-based builds, we recommend you use either `dotnet xunit` or the console runner.
