### ISSUE TITLE
XUnit fails on AppVeyor + Cake

### ISSUE THREAD

**Issue by Antaris** [xunit/xunit#1345]
Hi,

I'm running `dotnet xunit` manually as part of a Cake build running both locally and on AppVeyor.

Here is my Cake build script:

```
Task("Test")
    .Description("Runs unit tests")
    .IsDependentOn("Build")
    .Does(() =>
    {
        var tests = GetFiles(folders.tests + "**/*.csproj");
        foreach (var test in tests)
        {
            string folder = System.IO.Path.GetDirectoryName(test.FullPath);
            string project = folder.Substring(folder.LastIndexOf('\\') + 1);
            string resultsFile = folders.testResults + project + ".xml";

            CreateDirectory(folders.testResults);
            using (var process = StartAndReturnProcess("dotnet", new ProcessSettings 
                {
                    Arguments = "xunit -xml ../" + resultsFile + " --no-build",
                    WorkingDirectory = folder
                }))
            {
                process.WaitForExit();

                if (AppVeyor.IsRunningOnAppVeyor)
                {
                    AppVeyor.UploadTestResults(resultsFile, AppVeyorTestResultsType.XUnit);
                }
            }
        }
    });
```

Cake does not have a built in alias for common dotnet tools, so we have to manually run the tool. The `folder` variable changes the working directory to that of the project, and we're outputting XML test results that we would then manually upload.

Running locally works fine, we get our test results, but running it on AppVeyor results in the following error:

```
========================================
Test
========================================
Executing task: Test
Creating directory C:/projects/framework/build/test-results
Detecting target frameworks in Alium.Core.Abstractions.Tests.csproj...
Locating binaries for framework netcoreapp1.1...
Running .NET Core tests for framework netcoreapp1.1...
Cake.exe : System.ComponentModel.Win32Exception: The directory name is invalid
At line:1 char:1
+ & "C:\projects\framework\build-template\tools\Cake\Cake.exe" "build.c ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Componen...name is invalid:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at
 Program.RunDotNetCoreProject(String outputPath, String assemblyName, String targetFileName, String extraArgs)
   at Program.RunTargetFramework(String testProject, String targetFramework, Boolean amendOutputFileNames)
   at Program.Execute(String[] args)
An error occurred when executing task '
Test
'.
Error: 
One or more errors occurred.
```

So I can see it is actually running `dotnet xunit`, but then an exception is thrown `Directory name is invalid`. Hard for me to debug on AppVeyor.

Any thoughts?

**Comment by bradwilson** [comment]
Please add `-internaldiagnostics` to the `dotnet xunit` command line and rerun the test. This should output more information that might give a clue as to what's going on.

**Comment by Antaris** [comment]
@bradwilson  Here is the output with `internaldiagnostics`:

```
========================================
Test
========================================
Executing task: Test
Creating directory C:/projects/framework/build/test-results
Detecting target frameworks in Alium.Core.Abstractions.Tests.csproj...
EXEC: "C:\Program Files\dotnet\dotnet.exe" msbuild "C:\projects\framework\tests\Alium.Core.Abstractions.Tests\Alium.Core.Abstractions.Tests.csproj" /nologo /verbosity:minimal "/p:_Xunit_ImportTargetsFile=C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0-beta2-build3683\lib\netcoreapp1.0\import.targets" /p:Configuration=Debug /t:_Xunit_GetTargetFrameworks "/p:_XunitInfoFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp2481.tmp"
Locating binaries for framework netcoreapp1.1...
EXEC: "C:\Program Files\dotnet\dotnet.exe" msbuild "C:\projects\framework\tests\Alium.Core.Abstractions.Tests\Alium.Core.Abstractions.Tests.csproj" /nologo /verbosity:minimal "/p:_Xunit_ImportTargetsFile=C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0-beta2-build3683\lib\netcoreapp1.0\import.targets" /p:Configuration=Debug /t:_Xunit_GetTargetValues "/p:_XunitInfoFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp26A5.tmp" "/p:TargetFramework=netcoreapp1.1"
Running .NET Core tests for framework netcoreapp1.1...
EXEC: "C:\Program Files\dotnet\dotnet.exe" exec "C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0-beta2-build3683\tools\netcoreapp1.0\xunit.console.dll" "Alium.Core.Abstractions.Tests.dll" -xml "C:\projects\framework\build\test-results\Alium.Core.Abstractions.Tests.xml" -internaldiagnostics
Cake.exe : System.ComponentModel.Win32Exception: The directory name is invalid
At line:1 char:1
+ & "C:\projects\framework\build-template\tools\Cake\Cake.exe" "build.c ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Componen...name is invalid:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at
 Program.RunDotNetCoreProject(String outputPath, String assemblyName, String targetFileName, String extraArgs)
   at Program.RunTargetFramework(String testProject, String targetFramework, Boolean amendOutputFileNames)
   at Program.Execute(String[] args)
An error occurred when executing task '
Test
'.
Error: 
One or more errors occurred.
```

**Comment by Antaris** [comment]
This *might* be an issue using the .NET Core 2.0 preview on AppVeyor, that's the only difference I can see :-/

**Comment by Antaris** [comment]
Nada, using latest preview image which targets same version as my local machine, and pinned SDK version in `global.json`, still doesn't yield the same result.

For reference, here is the key part to my project file:

```
<Project>
    <!-- Unit Test Packages -->
    <ItemGroup Condition="'$(HostType)' == 'UnitTest'">
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
        <PackageReference Include="xunit" Version="2.3.0-beta2-build3683" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.2.0" />
        <PackageReference Include="Moq" Version="4.7.63" />

        <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta2-build3683" />
    </ItemGroup>
</Project>
```

**Comment by Antaris** [comment]
Hmm, interestingly, the output isn't *quite* the same:

On AppVeyor:
```
Running .NET Core tests for framework netcoreapp1.1...
EXEC: "C:\Program Files\dotnet\dotnet.exe" exec "C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0-beta2-build3683\tools\netcoreapp1.0\xunit.console.dll" "Alium.Core.Abstractions.Tests.dll" -xml "C:\projects\framework\build\test-results\Alium.Core.Abstractions.Tests.xml" -internaldiagnostics
```

vs locally:
```
Running .NET Core tests for framework netcoreapp1.1...
EXEC: "C:\Program Files\dotnet\dotnet.exe" exec --depsfile "Alium.Core.Abstractions.Tests.deps.json" --runtimeconfig "Alium.Core.Abstraction
s.Tests.runtimeconfig.json" "C:\Users\matth\.nuget\packages\dotnet-xunit\2.3.0-beta2-build3683\tools\netcoreapp1.0\xunit.console.dll" "Alium
.Core.Abstractions.Tests.dll" -xml "X:\AliumFX\git\Framework\build\test-results\Alium.Core.Abstractions.Tests.xml" -internaldiagnostics
```

**Comment by bradwilson** [comment]
The lack of the `.deps.json` and `.runtimeconfig.json` makes me think that the build either didn't happen, or happened incorrectly. The lack of those files is definitely a serious issue. Do things work if you stop using `--no-build`?

**Comment by Antaris** [comment]
@bradwilson Sorry for the late reply - with the `--no-build` flag removed, it works on AppVeyor:

```
========================================
Test
========================================
Executing task: Test
Creating directory C:/projects/framework/build/test-results
Detecting target frameworks in Alium.Core.Abstractions.Tests.csproj...
EXEC: "C:\Program Files\dotnet\dotnet.exe" msbuild "C:\projects\framework\tests\Alium.Core.Abstractions.Tests\Alium.Core.Abstractions.Tests.csproj" /nologo /verbosity:minimal "/p:_Xunit_ImportTargetsFile=C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0-beta2-build3683\lib\netcoreapp1.0\import.targets" /p:Configuration=Debug /t:_Xunit_GetTargetFrameworks "/p:_XunitInfoFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp20B2.tmp"
Building for framework netcoreapp1.1...
EXEC: "C:\Program Files\dotnet\dotnet.exe" msbuild "C:\projects\framework\tests\Alium.Core.Abstractions.Tests\Alium.Core.Abstractions.Tests.csproj" /nologo /verbosity:minimal "/p:_Xunit_ImportTargetsFile=C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0-beta2-build3683\lib\netcoreapp1.0\import.targets" /p:Configuration=Debug /t:Build;_Xunit_GetTargetValues "/p:_XunitInfoFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp2391.tmp" "/p:TargetFramework=netcoreapp1.1"
  Alium.Core.Abstractions -> C:\projects\framework\src\Alium.Core.Abstractions\bin\Debug\netstandard1.4\Alium.Core.Abstractions.dll
  Alium.Core.Abstractions.Tests -> C:\projects\framework\tests\Alium.Core.Abstractions.Tests\bin\Debug\netcoreapp1.1\Alium.Core.Abstractions.Tests.dll
Running .NET Core tests for framework netcoreapp1.1...
EXEC: "C:\Program Files\dotnet\dotnet.exe" exec --depsfile "Alium.Core.Abstractions.Tests.deps.json" --runtimeconfig "Alium.Core.Abstractions.Tests.runtimeconfig.json" "C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0-beta2-build3683\tools\netcoreapp1.0\xunit.console.dll" "Alium.Core.Abstractions.Tests.dll" -xml "C:\projects\framework\build\test-results\Alium.Core.Abstractions.Tests.xml" -internaldiagnostics
xUnit.net Console Runner (64-bit .NET Core 4.6.25211.01)
  Discovering: Alium.Core.Abstractions.Tests
  Discovered:  Alium.Core.Abstractions.Tests
  Starting:    Alium.Core.Abstractions.Tests
  Finished:    Alium.Core.Abstractions.Tests
=== TEST EXECUTION SUMMARY ===
   Alium.Core.Abstractions.Tests  Total: 34, Errors: 0, Failed: 0, Skipped: 0, Time: 0.527s
Finished executing task: Test
========================================
```

**Comment by Antaris** [comment]
@bradwilson I tried this same setup on our internal Bamboo-based build environment and we get the same issue.

Without `--no-build` the tests seem to fail, but they work perfectly fine on the local machine.

**Comment by johncrim** [comment]
I'm seeing the same problem here: https://ci.appveyor.com/project/johncrim/logjam/build/1.1.0-netstandard0035#L440 . Unfortunately I can only reproduce it on appveyor.  This build includes `-internaldiagnostics`.

Snippet of the build output:
```
Detecting target frameworks in LogJam.UnitTests.csproj...
EXEC: "C:\Program Files\dotnet\dotnet.exe" msbuild "C:\projects\logjam\test\LogJam.UnitTests\LogJam.UnitTests.csproj" /nologo /verbosity:minimal "/p:_Xunit_ImportTargetsFile=C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0\lib\netcoreapp2.0\import.targets" /p:Configuration=Debug /t:_Xunit_GetTargetFrameworks "/p:_XunitInfoFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp9A52.tmp"
Locating binaries for framework netcoreapp2.0...
EXEC: "C:\Program Files\dotnet\dotnet.exe" msbuild "C:\projects\logjam\test\LogJam.UnitTests\LogJam.UnitTests.csproj" /nologo /verbosity:minimal "/p:_Xunit_ImportTargetsFile=C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0\lib\netcoreapp2.0\import.targets" /p:Configuration=Debug /t:_Xunit_GetTargetValues "/p:_XunitInfoFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp9C37.tmp" "/p:TargetFramework=netcoreapp2.0"
Running .NET Core 2.0.0 tests for framework netcoreapp2.0...
EXEC: "C:\Program Files\dotnet\dotnet.exe" exec --fx-version 2.0.0 "C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0\tools\netcoreapp2.0\xunit.console.dll" "LogJam.UnitTests.dll" -appveyor -internaldiagnostics
dotnet : System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
At C:\projects\logjam\test.ps1:4 char:3
+   dotnet xunit -nobuild -appveyor -internaldiagnostics $testProject.c ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Componen...name is invalid:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessS
tartInfo startInfo)
   at Program.RunDotNetCoreProject(String outputPath, String assemblyName, String targetFileName, String extraArgs, String fxVersion, String netCoreAppVersion) in C:\Dev\xunit\xunit\src\dotnet-xunit\Program.cs:line 390
   at Program.RunTargetFramework(String testProject, String targetFramework, Boolean amendOutputFileNames) in C:\Dev\xunit\xunit\src\dotnet-xunit\Program.cs:line 329
   at Program.Execute(String[] args) in C:\Dev\xunit\xunit\src\dotnet-xunit\Program.cs:line 130
```

The same powershell script containing `dotnet xunit` passed earlier today on appveyor:
https://ci.appveyor.com/project/johncrim/logjam/build/1.1.0-netstandard0031/tests

The only bit that changed was switching to a release build. I'll try reverting to debug build and see if the tests work.

**Comment by bradwilson** [comment]
@johncrim Does removing `--no-build` also fix it for you?

**Comment by johncrim** [comment]
That's the issue, at least for me (release build, followed by `dotnet xunit -nobuild`) causes this issue. 

Repro steps (in powershell):
```
git clone git@github.com:logjam2/logjam.git
cd logjam
git checkout feature/netstandard
dotnet build /p:Configuration=Release
.\test.ps1
```

My test.ps1 script:

```
$testProjects =  ( "LogJam.UnitTests", "LogJam.Internal.UnitTests", "LogJam.XUnit2.UnitTests" )
foreach ( $testProject in $testProjects) {
  pushd ".\test\$testProject"
  dotnet xunit -nobuild -appveyor -internaldiagnostics $testProject.csproj
  popd
}
```

You can check easily if this is the issue for your project in appveyor by commenting out the

```
#configuration: Release
```

in your appveyor.yml, and see if the tests pass. Alternatively, removing the `-nobuild` param also fixes the issue, presumably b/c the Debug configuration is built.

When I perform the same steps locally, `-internaldiagnostics` gives me additional info that clearly points to the issue, eg:

```
? .\test
Detecting target frameworks in LogJam.UnitTests.csproj...
EXEC: "C:\Program Files\dotnet\dotnet.exe" msbuild "C:\src\github\logjam\logjam\test\LogJam.UnitTests\LogJam.UnitTests.csproj" /nologo /verbosity:minimal "/p:_Xunit_ImportTargetsFile=C:\Users\jc\.nuget\packages\dotnet-xunit\2.3.0\lib\netcoreapp2.0\import.targets" /p:Configuration=Debug /t:_Xunit_GetTargetFrameworks "/p:_XunitInfoFile=C:\Users\jc\AppData\Local\Temp\tmp7558.tmp"
Locating binaries for framework netcoreapp2.0...
EXEC: "C:\Program Files\dotnet\dotnet.exe" msbuild "C:\src\github\logjam\logjam\test\LogJam.UnitTests\LogJam.UnitTests.csproj" /nologo /verbosity:minimal "/p:_Xunit_ImportTargetsFile=C:\Users\jc\.nuget\packages\dotnet-xunit\2.3.0\lib\netcoreapp2.0\import.targets" /p:Configuration=Debug /t:_Xunit_GetTargetValues "/p:_XunitInfoFile=C:\Users\jc\AppData\Local\Temp\tmp7847.tmp" "/p:TargetFramework=netcoreapp2.0"
Running .NET Core 2.0.0 tests for framework netcoreapp2.0...
EXEC: "C:\Program Files\dotnet\dotnet.exe" exec --fx-version 2.0.0 "C:\Users\jc\.nuget\packages\dotnet-xunit\2.3.0\tools\netcoreapp2.0\xunit.console.dll" "LogJam.UnitTests.dll" -appveyor -internaldiagnostics
error: file not found: LogJam.UnitTests.dll
   at Xunit.ConsoleClient.CommandLine.Parse(Predicate`1 fileExists) in C:\Dev\xunit\xunit\src\xunit.console\CommandLine.cs:line 123
   at Xunit.ConsoleClient.CommandLine..ctor(IReadOnlyList`1 reporters, String[] args, Predicate`1 fileExists) in C:\Dev\xunit\xunit\src\xunit.console\CommandLine.cs:line 24
   at Xunit.ConsoleClient.ConsoleRunner.EntryPoint(String[] args) in C:\Dev\xunit\xunit\src\xunit.console\ConsoleRunner.cs:line 53
```

**Comment by bradwilson** [comment]
When you changed from Release to Debug, do the `dotnet pack` commands stay in Release, or are they too done with Debug? I wonder if that command is somehow eradicating/moving the .deps.json file that we need to be able to run your tests.

**Comment by bradwilson** [comment]
A Release build does generate `.deps.json` files (it's not possible for _anything_ in .NET Core to run without that, so obviously it must always get generated):

```
PS> dir -r -fi *.deps.json | select FullName

FullName
--------
C:\Dev\xunit\xunit\src\dotnet-xunit\bin\Release\netcoreapp1.0\dotnet-xunit.deps.json
C:\Dev\xunit\xunit\src\dotnet-xunit\bin\Release\netcoreapp2.0\dotnet-xunit.deps.json
C:\Dev\xunit\xunit\src\xunit.assert\bin\Release\netstandard1.1\xunit.assert.deps.json
C:\Dev\xunit\xunit\src\xunit.console\bin\Release\netcoreapp1.0\xunit.console.deps.json
C:\Dev\xunit\xunit\src\xunit.console\bin\Release\netcoreapp2.0\xunit.console.deps.json
C:\Dev\xunit\xunit\src\xunit.console\bin\Release_x86\netcoreapp1.0\xunit.console.x86.deps.json
C:\Dev\xunit\xunit\src\xunit.console\bin\Release_x86\netcoreapp2.0\xunit.console.x86.deps.json
C:\Dev\xunit\xunit\src\xunit.core\bin\Release\netstandard1.1\xunit.core.deps.json
C:\Dev\xunit\xunit\src\xunit.execution\bin\Release\netstandard1.1\xunit.execution.dotnet.deps.json
C:\Dev\xunit\xunit\src\xunit.runner.reporters\bin\Release\netcoreapp1.0\xunit.runner.reporters.netcoreapp10.deps.json
C:\Dev\xunit\xunit\src\xunit.runner.reporters\bin\Release\netstandard1.1\xunit.runner.reporters.netstandard11.deps.json
C:\Dev\xunit\xunit\src\xunit.runner.reporters\bin\Release\netstandard1.5\xunit.runner.reporters.netstandard15.deps.json
C:\Dev\xunit\xunit\src\xunit.runner.reporters\bin\Release_x86\netcoreapp1.0\xunit.runner.reporters.netcoreapp10.deps.json
C:\Dev\xunit\xunit\src\xunit.runner.utility\bin\Release\netcoreapp1.0\xunit.runner.utility.netcoreapp10.deps.json
C:\Dev\xunit\xunit\src\xunit.runner.utility\bin\Release\netstandard1.1\xunit.runner.utility.netstandard11.deps.json
C:\Dev\xunit\xunit\src\xunit.runner.utility\bin\Release\netstandard1.5\xunit.runner.utility.netstandard15.deps.json
C:\Dev\xunit\xunit\src\xunit.runner.utility\bin\Release_x86\netcoreapp1.0\xunit.runner.utility.netcoreapp10.deps.json
C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\bin\Release\netcoreapp1.0\xunit.runner.visualstudio.dotnetcore.testadapter.deps.json
C:\Dev\xunit\xunit\test\test.harness\bin\Release\netcoreapp1.0\test.harness.deps.json
C:\Dev\xunit\xunit\test\test.harness\bin\Release\netcoreapp1.1\test.harness.deps.json
C:\Dev\xunit\xunit\test\test.harness\bin\Release\netcoreapp2.0\test.harness.deps.json
C:\Dev\xunit\xunit\test\test.testcasefilter\bin\Release\netcoreapp1.0\test.testcasefilter.deps.json
C:\Dev\xunit\xunit\test\test.utility\bin\Release\netstandard1.5\test.utility.deps.json
```

**Comment by johncrim** [comment]
`dotnet pack` is done with Release: https://ci.appveyor.com/project/johncrim/logjam/build/1.1.0-netstandard0035#L429

Appveyor runs `msbuild *.sln` first (without `/p:Configuration=Release`, so it must be in an environment variable); then `dotnet pack *.csproj --configuration Release --include-symbols`; then the test script.

**Comment by johncrim** [comment]
The `.deps.json` files are present before `dotnet xunit` is called. I added your powershell line to dump the deps.json files before calling `dotnet xunit`. From https://ci.appveyor.com/project/johncrim/logjam/build/1.1.0-netstandard0037#L244

```
.\test.ps1
FullName                                                                                                       
--------                                                                                                       
C:\projects\logjam\src\LogJam\bin\Release\netstandard1.3\LogJam.deps.json                                      
C:\projects\logjam\src\LogJam.XUnit2\bin\Release\netstandard1.3\LogJam.XUnit2.deps.json                        
C:\projects\logjam\test\LogJam.ConsoleTester\bin\Release\netcoreapp2.0\LogJam.ConsoleTester.deps.json          
C:\projects\logjam\test\LogJam.Internal.UnitTests\bin\Release\netcoreapp2.0\LogJam.Internal.UnitTests.deps.json
C:\projects\logjam\test\LogJam.Test.Shared\bin\Release\netcoreapp2.0\LogJam.Test.Shared.deps.json              
C:\projects\logjam\test\LogJam.UnitTests\bin\Release\netcoreapp2.0\LogJam.UnitTests.deps.json                  
C:\projects\logjam\test\LogJam.XUnit2.UnitTests\bin\Release\netcoreapp2.0\LogJam.XUnit2.UnitTests.deps.json    
Detecting target frameworks in LogJam.UnitTests.csproj...
EXEC: "C:\Program Files\dotnet\dotnet.exe" msbuild "C:\projects\logjam\test\LogJam.UnitTests\LogJam.UnitTests.csproj" /nologo /verbosity:minimal "/p:_Xunit_ImportTargetsFile=C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0\lib\netcoreapp2.0\import.targets" /p:Configuration=Debug /t:_Xunit_GetTargetFrameworks "/p:_XunitInfoFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp6514.tmp"
Locating binaries for framework netcoreapp2.0...
EXEC: "C:\Program Files\dotnet\dotnet.exe" msbuild "C:\projects\logjam\test\LogJam.UnitTests\LogJam.UnitTests.csproj" /nologo /verbosity:minimal "/p:_Xunit_ImportTargetsFile=C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0\lib\netcoreapp2.0\import.targets" /p:Configuration=Debug /t:_Xunit_GetTargetValues "/p:_XunitInfoFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp6728.tmp" "/p:TargetFramework=netcoreapp2.0"
Running .NET Core 2.0.0 tests for framework netcoreapp2.0...
EXEC: "C:\Program Files\dotnet\dotnet.exe" exec --fx-version 2.0.0 "C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0\tools\netcoreapp2.0\xunit.console.dll" "LogJam.UnitTests.dll" -internaldiagnostics
dotnet : System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
At C:\projects\logjam\test.ps1:7 char:3
+   dotnet xunit -nobuild -internaldiagnostics $testProject.csproj
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Componen...name is invalid:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessS
tartInfo startInfo)
   at Program.RunDotNetCoreProject(String outputPath, String assemblyName, String targetFileName, String extraArgs, String fxVersion, String netCoreAppVersion) in C:\Dev\xunit\xunit\src\dotnet-xunit\Program.cs:line 390
   at Program.RunTargetFramework(String testProject, String targetFramework, Boolean amendOutputFileNames) in C:\Dev\xunit\xunit\src\dotnet-xunit\Program.cs:line 329
   at Program.Execute(String[] args) in C:\Dev\xunit\xunit\src\dotnet-xunit\Program.cs:line 130
Detecting target frameworks in LogJam.Internal.UnitTests.csproj...
EXEC: "C:\Program Files\dotnet\dotnet.exe" msbuild "C:\projects\logjam\test\LogJam.Internal.UnitTests\LogJam.Internal.UnitTests.csproj" /nologo /verbosity:minimal "/p:_Xunit_ImportTargetsFile=C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0\lib\netcoreapp2.0\import.targets" /p:Configuration=Debug /t:_Xunit_GetTargetFrameworks "/p:_XunitInfoFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp6C77.tmp"
Locating binaries for framework netcoreapp2.0...
EXEC: "C:\Program Files\dotnet\dotnet.exe" msbuild "C:\projects\logjam\test\LogJam.Internal.UnitTests\LogJam.Internal.UnitTests.csproj" /nologo /verbosity:minimal "/p:_Xunit_ImportTargetsFile=C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0\lib\netcoreapp2.0\import.targets" /p:Configuration=Debug /t:_Xunit_GetTargetValues "/p:_XunitInfoFile=C:\Users\appveyor\AppData\Local\Temp\1\tmp6E7B.tmp" "/p:TargetFramework=netcoreapp2.0"
Running .NET Core 2.0.0 tests for framework netcoreapp2.0...
EXEC: "C:\Program Files\dotnet\dotnet.exe" exec --fx-version 2.0.0 "C:\Users\appveyor\.nuget\packages\dotnet-xunit\2.3.0\tools\netcoreapp2.0\xunit.console.dll" "LogJam.Internal.UnitTests.dll" -internaldiagnostics
dotnet : System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
At C:\projects\logjam\test.ps1:7 char:3
+   dotnet xunit -nobuild -internaldiagnostics $testProject.csproj
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Componen...name is invalid:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessS
tartInfo startInfo)
   at Program.RunDotNetCoreProject(String outputPath, String assemblyName, String targetFileName, String extraArgs, String fxVersion, String netCoreAppVersion) in C:\Dev\xunit\xunit\src\dotnet-xunit\Program.cs:line 390
   at Program.RunTargetFramework(String testProject, String targetFramework, Boolean amendOutputFileNames) in C:\Dev\xunit\xunit\src\dotnet-xunit\Program.cs:line 329
   at Program.Execute(String[] args) in C:\Dev\xunit\xunit\src\dotnet-xunit\Program.cs:line 130
```

**Comment by johncrim** [comment]
One interesting bit about the `.deps.json` dump above compared to the xunit project is that when it's run in appveyor (and when I run `dotnet build` locally), I'm only seeing one `.deps.json` file per project, even though each of the projects is multi-targeted.

In @bradwilson s xunit build, there are multiple `.deps.json` files per project.

**Comment by johncrim** [comment]
I was able to workaround this issue by adding `-configuration $env:Configuration` to my `dotnet xunit` call. Things appear to work as expected when `-configuration` is correctly set.

Here's my revised `test.ps1` script:

https://github.com/logjam2/logjam/blob/f529c0943a0c8ddeb226358cf0f1021117ecba11/test.ps1#L12-L24

**Comment by bradwilson** [comment]
Jeez, I don't know why I didn't think of that myself. The default configuration is `Debug`. /faceplam

**Comment by johncrim** [comment]
Thanks for the help. I'll bet $1 that @Antaris 's problem.

**Comment by bradwilson** [comment]
I'm going to update the `-internaldiagnostics` output to indicate the working folder; that would've immediately set off warning bells for me (and probably everybody else).

**Comment by bradwilson** [comment]
Done: 59a667a42659445a0ec664f7013c3e1231e9a4c2
