### ISSUE TITLE
xunit Theory is not executed because test case cannot be deserialized 

### ISSUE THREAD

**Issue by Faizan2304** [xunit/xunit#1353]
_From @feO2x on June 17, 2017_
## Description
While writing tests for my open source project today, I discovered that an xunit theory was (silently) not executed, both in VS Test Runner and CLI dotnet-test, because the test runner is "Unable to de-serialize test case". According to https://github.com/Microsoft/vstest/issues/300 this should be fixed - is this just not published to the current version of VS and dotnet CLI or is something wrong with my theory so that the corresponding test cases cannot be deserialized?

## Steps to reproduce
* Clone the Git repository https://github.com/feO2x/Light.GuardClauses
* Checkout the tag "DeserializeTestCaseError" in a new local branch
* Open "Light.GuardClauses.sln" in Visual Studio 2017 
* Build the whole solution, then open Test Explorer and run all tests
* Open a command prompt, navigate to the folder where "Light.GuardClauses.Tests.csproj" resides and run `dotnet test --filter "FullyQualifiedName=Light.GuardClauses.Tests.IsEquivalentToTests.GenericTypes"`

## Expected behavior
* All tests should run in VS Test Explorer
* The test should run on dotnet CLI without throwing exceptions

## Actual behavior
The theory `Light.GuardClauses.Tests.IsEquivalentTests.GenericTypes` is (silently) not executed in VS Test Explorer:
<img src="https://raw.githubusercontent.com/feO2x/Light.GuardClauses/master/Images/xunit-DeserializeTestCaseError-TestExplorer.PNG" alt="Theory not executed in VS Test Explorer" height="400" />

The dotnet CLI shows an exception that the test case could not be deserialized:
![Test Case Cannot Be Deserialized in .NET Core CLI](https://raw.githubusercontent.com/feO2x/Light.GuardClauses/master/Images/xunit-DeserializeTestCaseError-dotnetTest.PNG)

Please note that I reduced the runs of the theory to eight for the dotnet CLI image to keep everything on one screen. I also removed the `DisplayName` for the theory.

## Environment
Operating System: Windows 10 Pro 1703 (Build 15063.413)
Visual Studio Version: 15.2 (26430.13)
dotnet --version: 1.0.4 (latest SDK release from https://www.microsoft.com/net/download/core)
The test project is a .NET Core 1.1 app (created with `dotnet new xunit`).

_Copied from original issue: https://github.com/Microsoft/vstest/issues/874_

**Comment by Faizan2304** [comment]
_From @feO2x on June 17, 2017_

For the sake of completeness, here is the exception message from the .NET CLI in plain text:

```
[xUnit.net 00:00:02.0911303] Unable to de-serialize test case Light.GuardClauses.Tests.IsEquivalentToTests.GenericTypes(type: typeof(GenericType`1), other: typeof(Light.GuardClauses.Tests.GenericType<>), expected: True): System.ArgumentException: String cannot have zero length.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
[xUnit.net 00:00:02.1032448]   Starting:    Light.GuardClauses.Tests
   at System.Linq.Enumerable.<>c__DisplayClass151_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Xunit.Sdk.SerializationHelper.GetType(String assemblyQualifiedTypeName)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeTriple(String value)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeTriple(String value)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue)
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.Deserialize(LoggerHelper logger, ITestFrameworkExecutor executor, TestCase testCase)
```

**Comment by Faizan2304** [comment]
_From @feO2x on June 18, 2017_

I dug a little deeper into the problem. The theory that is not working looks like this:

```csharp
[Trait("Category", Traits.FunctionalTests)]
public sealed class IsEquivalentToTests
{
    // Other tests that are irrelevant to this error are here.

    [Theory(DisplayName = "IsEquivalentTo must return true when one type is a constructed generic type and the other one is the corresponding generic type definition.")]
    [MemberData(nameof(GenericTypesData))]
    public void GenericTypes(Type type, Type other, bool expected)
    {
        var result = type.IsEquivalentTo(other);

        result.Should().Be(expected);
    }

    public static TestData GenericTypesData =>
        new[]
        {
            // Please note: this set of parameters actually contains more entries in the actual code, 
            // but these are only variants of the ones you see below where I swapped 
            // parameter 1 and parameter 2 (to ensure that the tested method works no matter 
            // the order of the parameters)

            // Simple type tests
            new object[] { typeof(List<>), typeof(List<>), true },
            new object[] { typeof(IList<string>), typeof(IList<string>), true },

            // Base types of generic types
            new object[] { typeof(SubTypeA<>).GetTypeInfo().BaseType, typeof(GenericType<>), true },
            new object[] { typeof(SubTypeA<int>).GetTypeInfo().BaseType, typeof(GenericType<int>), true },
            new object[] { typeof(SubTypeA<int>).GetTypeInfo().BaseType, typeof(GenericType<>), true },
            new object[] { typeof(SubTypeB).GetTypeInfo().BaseType, typeof(GenericType<string>), true },
            new object[] { typeof(SubTypeB).GetTypeInfo().BaseType, typeof(GenericType<>), true },
            new object[] { typeof(SubTypeB).GetTypeInfo().BaseType, typeof(List<>), false },

             // Return types of generic methods
            new object[] { CreateDictionaryOfTKeyTValue.ReturnType, typeof(Dictionary<,>), true },
            new object[] { CreateDictionaryOfTKey.ReturnType, typeof(Dictionary<,>), true },
            new object[] { CreateDictionaryOfTKey.ReturnType, CreateDictionaryOfTKeyTValue.ReturnType, false }
        };

    public class GenericType<T> { }

    public class SubTypeA<T> : GenericType<T> { }

    public class SubTypeB : GenericType<string> { }

    public static Dictionary<TKey, TValue> CreateDictionaryA<TKey, TValue>()
    {
        return new Dictionary<TKey, TValue>();
    }

    public static Dictionary<TKey, object> CreateDictionaryB<TKey>()
    {
        return new Dictionary<TKey, object>();
    }

    private static readonly MethodInfo CreateDictionaryOfTKeyTValue;
    private static readonly MethodInfo CreateDictionaryOfTKey;

    static IsEquivalentToTests()
    {
        var typeInfo = typeof(IsEquivalentToTests).GetTypeInfo();
        CreateDictionaryOfTKeyTValue = typeInfo.DeclaredMethods.First(m => m.IsStatic && m.Name.StartsWith(nameof(CreateDictionaryA)));
        CreateDictionaryOfTKey = typeInfo.DeclaredMethods.First(m => m.IsStatic && m.Name.StartsWith(nameof(CreateDictionaryB)));
    }
}
```
Now the sets of parameters that cause the issue are the following: the first one of the **Base types of generic types** group and all of the **Return types of generic methods** group (see next). All other sets of parameters work fine (no errors in VS Test Explorer or with dotnet test)

```
new object[] { typeof(SubTypeA<>).GetTypeInfo().BaseType, typeof(GenericType<>), true },
new object[] { CreateDictionaryOfTKeyTValue.ReturnType, typeof(Dictionary<,>), true },
new object[] { CreateDictionaryOfTKey.ReturnType, typeof(Dictionary<,>), true },
new object[] { CreateDictionaryOfTKey.ReturnType, CreateDictionaryOfTKeyTValue.ReturnType, false }
```

I now think this is rather an error of the xunit test runner rather than an issue with vstest. Maybe @bradwilson can take a look?

**Comment by Faizan2304** [comment]
_From @whoisj  on June 23, 2017_

I hit this issue as well. It was resolved (at least for me) by switching the xunit.runner.json configuration for "appDomain" from "denied" to "ifAvailable".

**Comment by Faizan2304** [comment]
_From @msfreed on June 26, 2017_

I am also experiencing this issue. Setting "appDomain" to "ifAvailable" did not resolve the issue for me.

**Comment by Faizan2304** [comment]
_From @msfreed on July 7, 2017_

Some additional data,

- xunit 2.2.0
- xunit.runner.visualstudio 2.2.0

I got the same results running with the 2.3.x beta packages. Initially the error was,

```
[xUnit.net 00:00:00.1732696] Unable to de-serialize test case ValidateCspRequest(test: Test { Description = "Expired token", ExpectValid = False, Params = [[_v, cHJvdGVjdGVkOgAgZtxevNMIAwAAAA]] }): System.InvalidOperationException: Could not de-serialize type 'CspReportValidatorTests+Test' because it lacks a parameterless constructor.

Server stack trace: 
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeTriple(String value)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeTriple(String value)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue)
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue)
   at Xunit.Sdk.TestFrameworkExecutor`1.Deserialize(String value)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
```

So I added a parameter-less constructor and got this,

```
[xUnit.net 00:00:00.1606624] Unable to de-serialize test case ValidateCspRequest(test: Test { Description = "Expired token", ExpectValid = False, Params = [[_v, cHJvdGVjdGVkOgAgZtxevNMIAwAAAA]] }): System.NotImplementedException: The method or operation is not implemented.

Server stack trace: 
   at CspReportValidatorTests.Test.Deserialize(IXunitSerializationInfo info) in CspReportValidatorTests.cs:line 117
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeTriple(String value)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeTriple(String value)
   at Xunit.Serialization.XunitSerializationInfo.DeserializeSerializable(Type type, String serializedValue)
   at Xunit.Serialization.XunitSerializationInfo.Deserialize(Type type, String serializedValue)
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue)
   at Xunit.Sdk.TestFrameworkExecutor`1.Deserialize(String value)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
```

**Comment by samirem** [comment]
This issue, or something related, breaks the Live Unit Testing feature for me.

Getting the following error message:
```
- TestDriver - [TestRunner 1] [xUnit.net 00:00:00.6185847] TestProject: Catastrophic error during deserialization: System.ArgumentException: Could not load type 
Parametername: serializedValue
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue)
   at Xunit.Sdk.TestFrameworkExecutor`1.Deserialize(String value)
   at Xunit.DefaultTestCaseBulkDeserializer.<BulkDeserialize>b__2_0(String serialization)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Xunit.DefaultTestCaseBulkDeserializer.BulkDeserialize(List`1 serializations)
   at Xunit.Xunit2.BulkDeserialize(List`1 serializations)
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)
```

**Comment by bradwilson** [comment]
@samirem Please open a new issue with a repro. Thanks!

**Comment by bradwilson** [comment]
@Faizan2304 This behavior is by design. The Visual Studio test adapter requires test cases to be serializable. Any custom implementation must (a) derive from `MarshalByRefObject` (or, ideally, our `LongLivedMarshalByRefObject`), and (b) implement the `IXunitSerializable` interface.
