### ISSUE TITLE
Please support `dotnet xunit project.csproj`

### ISSUE THREAD

**Issue by borrrden** [xunit/xunit#1360]
Even the command `dotnet help xunit` throws this.  I think it is not taking the argument for the project file to use:

> Unhandled Exception: System.InvalidOperationException: Specify which project file to use because this 'D:\Development\couchbase-lite-net-2\src\Couchbase.Lite.Tests.NetCore' contains more than one project file.
   at Microsoft.DotNet.Cli.Utils.ProjectFactory.GetMSBuildProjPath(String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectFactory.GetMSBuildProj(String projectDirectory, NuGetFramework framework, String configuration, String outputPath)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
   at Microsoft.DotNet.Tools.Help.HelpCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

Obviously, I also tried saying something like `dotnet xunit project.csproj` with the same results

Version: 2.3.0-beta1-build3642
Platform: Mac and Windows so far

**Comment by bradwilson** [comment]
There's no xUnit.net code in that stack trace. I'm not sure why you think this is our bug. This looks like a bug in the .NET SDK CLI.

**Comment by borrrden** [comment]
Well, when I run (for example) `dotnet restore project.csproj` things will work, but when I run `dotnet xunit project.csproj` that happens.  Furthermore, when I remove one of the projects and then that same command, it says I passed an invalid parameter.  There seems to be no way to specify a project file for dotnet xunit to run, and that is a requirement of the dotnet CLI if more than one project is present from what I can tell.  If I don't specify the project for restore or anything else, I get the same exception.

**Comment by bradwilson** [comment]
This bug was written quite strangely, if that was your intention. Allow me to re-write the bug title for you.

**Comment by bradwilson** [comment]
The InvalidOperation stuff is unrelated noise that diverts away from your actual request.

**Comment by borrrden** [comment]
Sorry about that!  Thanks for the edit.

**Comment by jchannon** [comment]
Is it a case of adding a command line argument option for example`-project foo.csproj` and then tweaking the code here? https://github.com/xunit/xunit/blob/master/src/dotnet-xunit/Program.cs#L83-L97

**Comment by bradwilson** [comment]
I honestly don't know. I haven't looked at it yet.

**Comment by qmfrederik** [comment]
It's a limitation of the .NET Core CLI. When you run `dotnet <tool>`, it will open your `.csproj` file to see which tools you've installed and which tool it needs to invoke.

The CLI doesn't attempt to parse any of the arguments and hence is unable to figure out what to do if you have two `.csproj` files.

If you want this fixed, your best bet is to upvote dotnet/cli#4808

**Comment by bradwilson** [comment]
Closing as external.
