### ISSUE TITLE
Test discovery error on .net core 2.0 preview 2

### ISSUE THREAD

**Issue by denisvlah** [xunit/xunit#1367]
I have .net core 2.0 preview 2 installed.

And I a test ported from .nunit to xunit.  Project compiles without errors.
When I try to issue command 
dotnet test 
I get the following error in the logs:

[7/18/2017 2:28:24 AM Error] [xUnit.net 00:00:05.7259262] EpyDoc.Sdk.Document.Test.netcore: Error creating Visual Studio test case for EpyDoc.D1.D2.QueryAllDocumentsWithNameAndModifiedAtWorks: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at Xunit.Sdk.TraitDiscoverer.<GetTraits>d__0.MoveNext()
   at Xunit.Sdk.XunitTestCase.Initialize()
   at Xunit.Sdk.TestMethodTestCase.get_DisplayName()
   at Xunit.Runner.VisualStudio.TestAdapter.VsDiscoverySink.CreateVsTestCase(String source, ITestFrameworkDiscoverer discoverer, ITestCase xunitTestCase, Boolean forceUniqueName, LoggerHelper logger, Boolean designMode)

After this error the test don't start and the dotnet cli command hangs.

My .csproj file is in attachments
[EpyDoc.Sdk.Document.Test.netcore.txt](https://github.com/xunit/xunit/files/1155418/EpyDoc.Sdk.Document.Test.netcore.txt)

I have this problem only in 1 class. If I remove the problematic class everything starts to work.

The class has about 165 facts, constructor , Dispose. There is no traits or extra attributes.
I have no idea how to workaround this problem.

**Comment by denisvlah** [comment]
It was my own bug, I had an attribute in the class that was implementing the ITrait interface
