### ISSUE TITLE
dotnet xunit fails with System.BadImageFormatException 

### ISSUE THREAD

**Issue by DemoBytom** [xunit/xunit#1382]
In the *.csproj-based project, the problem is if you try to test an executable project/web app, referencing `Microsoft.AspNetCore.Server.Kestrel` (or any project that indirectly references that package, like a `Microsoft.AspNetCore` package for example), `dotnet xunit` fails with `System.BadImageFormatException`

# Steps to reproduce:
Create ConsoleApp with this as a ConsoleApp1.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.1.2" />
  </ItemGroup>
</Project>
```
Test class in the console app that will be tested:
```
namespace ConsoleApp1
{
    public class ConsoleClass
    {
        public int Method()
        {
            return 123;
        }
    }
}
```
Create xUnit test project with this as .csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="xunit" Version="2.3.0-beta3-build3705" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta3-build3705" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta3-build3705" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ConsoleApp1\ConsoleApp1.csproj" />
  </ItemGroup>  
</Project>
```
The test method class:
```
using ConsoleApp1;
using Xunit;

namespace XUnitTestProject1
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            var consoleTest = new ConsoleClass();
            var returned = consoleTest.Method();
            Assert.Equal(123, returned);
        }
    }
}
```
# Expected behavior
running `dotnet xunit` causes test to pass.
# Actual behavior
running `dontet xunit` causes the test to fail
`dotnet xunit` output:
```
Detecting target frameworks in XUnitTestProject1.csproj...
Building for framework net461...
  ConsoleApp1 -> d:\michal\Documents\Visual Studio 2017\Projects\CoreXUnitNet461\ConsoleApp1\bin\Debug\net461\ConsoleApp1.exe
  XUnitTestProject1 -> d:\michal\Documents\Visual Studio 2017\Projects\CoreXUnitNet461\XUnitTestProject1\bin\Debug\net461\XUnitTestProject1.dll
Running desktop CLR tests for framework net461...
xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
  Discovering: XUnitTestProject1
  Discovered:  XUnitTestProject1
  Starting:    XUnitTestProject1
    XUnitTestProject1.UnitTest1.Test1 [FAIL]
      System.BadImageFormatException : Nie można załadować pliku lub zestawu 'ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' lub jednej z jego zależności. Próbowano załadować program w niepoprawnym formacie.
      Stack Trace:
           w XUnitTestProject1.UnitTest1.Test1()
  Finished:    XUnitTestProject1
=== TEST EXECUTION SUMMARY ===
   XUnitTestProject1  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0,137s
```

Removing the `Microsoft.AspNetCore.Server.Kestrel` reference from the Console App causes the test to pass
Changing the project type from `Console Application` to `Class Library`, even with the  `Microsoft.AspNetCore.Server.Kestrel` reference present, causes the test to pass
Running `dotnet test` causes the tests to pass as well

# Environment Data
`dotnet info` output:
```
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.4
```

# Additional notes
Running tests in Visual Studio 2017 works properly every time, only the cli tools seem to be broken

I tried running tests with different versions of a `dotnet-xunit` package as well as different versions of `Microsoft.AspNetCore.Server.Kestrel` package. The results were always the same.

I made a [simple test repo](https://github.com/DemoBytom/xUnitNet461Problem) that has 5 projects, showcasing different project type/references combination:
* 3 executable projects, 1 without Kestrel reference
* 1 Class library project with Kestrel reference
* xUnit test project with 4 test methods

Running tests with dotnet xunit causes 2 out of 4 test methods to fail with `System.BadImageFormatException`

also reported on the [dotnet/cli](https://github.com/dotnet/cli/issues/3103#issuecomment-318621205)

**Comment by bradwilson** [comment]
You can't load a 32-bit binary into a 64-bit process.

You have two choices:

- Convert the test project to 64-bit, or
- Add `-x86` to the `dotnet xunit` command line

**Comment by DemoBytom** [comment]
Well, changing all projects to x64 or Any CPU indeed fixed the issue. I wasn't aware that the projects defaulted to x86

**Comment by MisinformedDNA** [comment]
My code and test projects were both x86 and I was getting the above exception. Changed them to AnyCPU and sure enough, the issue went away.

For curiosity, what process requires x64?

**Comment by bradwilson** [comment]
If you install the 64-bit .NET SDK, then everything you run through `dotnet.exe` is 64-bit. The only way to run things in 32-bit is to (a) install the 32-bit .NET SDK, and then (b) make sure you're running the 32-bit version of `dotnet.exe`.

**Comment by mwpowellhtx** [comment]
I'm trying to run a ``x64`` and receiving the same. Does not even discover test cases.

```
[10/25/2018 11:01:57 AM Warning] [xUnit.net 00:00:00.74] Exception discovering tests from Kingdom.OrTools.ConstraintSolver.Samples.Tests: System.BadImageFormatException: Could not load file or assembly 'Kingdom.OrTools.ConstraintSolver.Samples.Tests, Version=3.0.1.19744, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'Kingdom.OrTools.ConstraintSolver.Samples.Tests, Version=3.0.1.19744, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Xunit.Sdk.ReflectionAssemblyInfo..ctor(String assemblyFileName) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionAssemblyInfo.cs:line 33   at Xunit.AppDomainManager_AppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args) in C:\Dev\xunit\xunit\src\xunit.runner.utility\AppDomain\AppDomainManager_AppDomain.cs:line 84
   at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2Discoverer.cs:line 101
   at Xunit.XunitFrontController.CreateInnerController() in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 136
   at Xunit.XunitFrontController.EnsureInitialized() in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 163
   at Xunit.Runner.VisualStudio.VsTestRunner.DiscoverTestsInSource[TVisitor](XunitFrontController framework, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, Func`4 visitorFactory, Action`4 visitComplete, String assemblyFileName, Boolean shadowCopy, TestAssemblyConfiguration configuration) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 280
```

See [attached](https://github.com/xunit/xunit/files/2515604/xunit-test-explorer-18-10-25-0001.txt), full log.

I am trying to load a ``net472`` test assembly built for ``x64``. That I know of all of the assemblies involved are either ``x64`` or ``AnyCPU``.

**Comment by bradwilson** [comment]
@mwpowellhtx `dotnet xunit` is no longer supported.

**Comment by mwpowellhtx** [comment]
@bradwilson I'm not sure what that means. Unit tests for 64-bit ``net472``?

**Comment by bradwilson** [comment]
Are you sure you're responding to the correct issue? This one's title clearly talks about `dotnet xunit` (which, yes, could run desktop CLR tests).

**Comment by mwpowellhtx** [comment]
@bradwilson The waters are a bit muddy, so if necessary I'll file a new issue. I'm responding in the sense that I've also received a ``BadImageFormatException``, running an ``x64`` assembly targeting ``net472``. I'm not sure what *Test Explorer* uses under the hood, is that ``dotnet xunit``?

**Comment by bradwilson** [comment]
No, it's `xunit.runner.visualstudio`. And if it runs fine w/ our console runner but does not run with the Visual Studio, then 9x out of 10 it's going to end up being something for the VSTest team rather than us.

**Comment by mwpowellhtx** [comment]
Thanks for the clarification. I'm not sure what it is with desktop framework, but the tests seem to be happier in the ``netcoreapp`` scenario. They are actually running, anyway, no BIF exceptions at any rate. Further, the assemblies I coalesce to that point are for the most part ``netstandard`` targets.
