### ISSUE TITLE
AD0001: AssertCollectionContainsShouldNotUseBoolCheck fails with ArgumentException

### ISSUE THREAD

**Issue by natemcmaster** [xunit/xunit#1406]
**Repro**

1. Clone https://github.com/natemcmaster/KestrelHttpServer/tree/xunit-beta4
6. Execute `build.cmd /t:Compile`

**Error**
```
Error AD0001 Analyzer 'Xunit.Analyzers.AssertCollectionContainsShouldNotUseBoolCheck' threw an exception of type 'System.ArgumentException' with message 'Wrong number of type arguments
Parameter name: typeArguments'.	Kestrel.Core.Tests(net461)

Analyzer 'Xunit.Analyzers.AssertCollectionContainsShouldNotUseBoolCheck' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.AspNetCore.Server.Kestrel.Core.Tests
SyntaxTree: C:\dev\aspnet\KestrelHttpServer\test\Kestrel.Core.Tests\FrameConnectionTests.cs
SyntaxNode: Assert.True(pairs.ContainsKey("ConnectionId" ... [InvocationExpressionSyntax]@[24279..24325) (550,12)-(550,58)

System.ArgumentException: Wrong number of type arguments
Parameter name: typeArguments
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Construct(ImmutableArray`1 arguments, Boolean unbound)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.ConstructWithoutModifiers(ImmutableArray`1 arguments, Boolean unbound)
   at Microsoft.CodeAnalysis.CSharp.Symbols.NamedTypeSymbol.Microsoft.CodeAnalysis.INamedTypeSymbol.Construct(ITypeSymbol[] arguments)
   at Xunit.Analyzers.AssertCollectionContainsShouldNotUseBoolCheck.IsCollectionContainsMethod(SyntaxNodeAnalysisContext context, SymbolInfo symbolInfo)
   at Xunit.Analyzers.AssertCollectionContainsShouldNotUseBoolCheck.Analyze(SyntaxNodeAnalysisContext context, InvocationExpressionSyntax invocation, IMethodSymbol method)
   at Xunit.Analyzers.AssertUsageAnalyzerBase.<>c__DisplayClass5_0.<Initialize>b__1(SyntaxNodeAnalysisContext syntaxContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

cc @marcind

**Comment by marcind** [comment]
Paging @ErikSchierboom

**Comment by jamesqo** [comment]
@marcind Is it OK if I grab this issue?

**Comment by marcind** [comment]
Yes.

**Comment by ErikSchierboom** [comment]
Thanks @jamesqo !

**Comment by natemcmaster** [comment]
Wow, fast turnaround on getting a fix. Thanks everyone!

**Comment by marcind** [comment]
We aim to please. Plus, you might be our biggest customer right now.

**Comment by nulltoken** [comment]
For the next person who's going to stumble upon this, adding the following change to the test `.csproj` files might be a handy workaround until next release of xUnit is published.

```diff
diff --git a/test/My.Tests/My.Tests.csproj b/test/My.Tests/My.Tests.csproj
index d295116..79cfbcb 100644
--- a/test/My.Tests/My.Tests.csproj
+++ b/test/My.Tests/My.Tests.csproj
@@ -42,6 +42,13 @@
     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
     <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta4-build3742" />
     <PackageReference Include="xunit" Version="2.3.0-beta4-build3742" />
+
+    <!-- 
+      Temporary workaround until fix is embbeded in a future xunit package 
+      cf. https://github.com/xunit/xunit/issues/1406
+    -->
+    <PackageReference Include="xunit.analyzers" Version="0.6.1" />
+
     <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.0.0" />
     <PackageReference Include="Microsoft.CodeCoverage" Version="1.0.3" />
```
