### ISSUE TITLE
AD0001: TheoryMethodMustUseAllParameters throws ArgumentNullException

### ISSUE THREAD

**Issue by natemcmaster** [xunit/xunit#1409]
**Repro**
1. Clone https://github.com/natemcmaster/AspNetCommon/tree/xunit-beta4
2. Execute `build.cmd /t:Compile`

**Error**
```
Analyzer 'Xunit.Analyzers.TheoryMethodMustUseAllParameters' threw an exception of type 'System.ArgumentNullException' with message 'Value cannot be null.
Parameter name: firstStatement'.	Microsoft.Extensions.CommandLineUtils.Tests(net461)		1	Active	Analyzer 'Xunit.Analyzers.TheoryMethodMustUseAllParameters' threw the following exception:
'Exception occurred with following context:
Compilation: Microsoft.Extensions.CommandLineUtils.Tests
SyntaxTree: C:\dev\aspnet\Common\test\Microsoft.Extensions.CommandLineUtils.Tests\ArgumentEscaperTests.cs
SyntaxNode: [Theory] [InlineData(new[] { "one" ... [MethodDeclarationSyntax]@[293..1109) (9,8)-(19,82)

System.ArgumentNullException: Value cannot be null.
Parameter name: firstStatement
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.ValidateStatementRange(StatementSyntax firstStatement, StatementSyntax lastStatement)
   at Microsoft.CodeAnalysis.CSharp.SyntaxTreeSemanticModel.AnalyzeDataFlow(StatementSyntax firstStatement, StatementSyntax lastStatement)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.AnalyzeDataFlow(StatementSyntax statement)
   at Xunit.Analyzers.TheoryMethodMustUseAllParameters.AnalyzeTheoryParameters(SyntaxNodeAnalysisContext context, MethodDeclarationSyntax methodSyntax, IMethodSymbol methodSymbol)
   at Xunit.Analyzers.TheoryMethodMustUseAllParameters.<>c__DisplayClass2_0.<Initialize>b__1(SyntaxNodeAnalysisContext syntaxNodeContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)

```

**Details**
Using xunit.analyzers 0.6.1 and xunit 2.3.0-beta4-build3742

cc @marcind @jamesqo

**Comment by natemcmaster** [comment]
You guessed right. Changing to braces fixes it.

**Comment by jamesqo** [comment]
@marcind Can we prefix analyzer names with their ID so it's obvious where the faulty analyzer's methods are in the stack trace? e.g. `X1026_TheoryMethodMustUseAllParameters`? This would also have the benefit of making it easier to find the file of an analyzer from its ID.

**Comment by marcind** [comment]
There are a number of analyzers that emit multiple different diagnostics, so the prefix is not a scalable pattern. The name of the analyzer was in the first line of the error message (`Analyzer 'Xunit.Analyzers.TheoryMethodMustUseAllParameters' threw an exception`) so it's pretty obvious to me where to look for the problem.

**Comment by jskeet** [comment]
Any idea when this might make it into a build? It's unfortunate that if any analyzers throw exceptions, that makes the package unusable at the moment - something the Roslyn team might want to think about...

**Comment by natemcmaster** [comment]
@jskeet I was able to work around this by adding AD0001 to NoWarn list. 

```xml
 <NoWarn>$(NoWarn);AD0001</NoWarn>
```

**Comment by jskeet** [comment]
@natemcmaster: Good call, will do that for now.

**Comment by jamesqo** [comment]
@natemcmaster That's strange, the rule should have an ID of xUnit1026, not AD0001.

**Comment by natemcmaster** [comment]
AD0001 is the warning number csc emits when an analyzer throws an unhandled exception.

**Comment by jamesqo** [comment]
@natemcmaster Got it.

**Comment by marcind** [comment]
Shipping in [0.7.0](https://www.nuget.org/packages/xunit.analyzers/0.7.0)

**Comment by marcind** [comment]
@jskeet shipping in [0.7.0](https://www.nuget.org/packages/xunit.analyzers/0.7.0)
