### ISSUE TITLE
Assert.Throws failed with System.InvalidProgramException

### ISSUE THREAD

**Issue by lextm** [xunit/xunit#1458]
Similar to #1457.
```
    class Program
    {
        static void Main(string[] args)
        {
            Assert.Throws<ArgumentNullException>(() => SpanExtension.Test(null));
        }
    }

    public static class SpanExtension
    {
        public static Span<byte> Test(this Span<byte> stream)
        {
            if (stream == null)
                throw new ArgumentNullException(nameof(stream));
            
            return new Span<byte>();
        }
    }
```
The console app would crash with
```
Unhandled Exception: Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.ArgumentNullException)
Actual:   typeof(System.InvalidProgramException): Common Language Runtime detected an invalid program.
   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\projects\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 148
   at Xunit.Assert.Throws[T](Func`1 testCode) in C:\projects\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 41
   at ConsoleApp1.Program.Main(String[] args) in F:\sharpsnmplib\ConsoleApp1\Program.cs:line 17
```

**Comment by lextm** [comment]
A workaround is to use `Assert.ThrowsAsync` (in the sample C# 7.1 is used),
```
class Program
    {
        static async Task Main(string[] args)
        {
            await Assert.ThrowsAsync<ArgumentNullException>(async () => SpanExtension.Test(null));
            Console.WriteLine("Finished");
        }
    }

    public static class SpanExtension
    {
        public static Span<byte> Test(this Span<byte> stream)
        {
            if (stream == null)
                throw new ArgumentNullException(nameof(stream));
            
            return new Span<byte>();
        }
    }
```

**Comment by bradwilson** [comment]
Neither of those two things makes sense. 😝

**Comment by lextm** [comment]
It seems to be related to https://github.com/dotnet/corefx/issues/21629
