### ISSUE TITLE
xunit 2.3.0 and VS 2017 15.4 not discovering tests for <TargetFramework>net461</TargetFramework>

### ISSUE THREAD

**Issue by soeron** [xunit/xunit#1518]
Project.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="xunit" Version="2.3.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0" />
  </ItemGroup>

</Project>
```
Test class
```
using System;
using Xunit;

namespace XunitProject
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
            Assert.True( false );
        }
    }
}
```
Test log
```
[ Informational] ------ Discover test started ------
[ Informational] ========== Discover test finished: 0 found (0:00:00,0313293) ==========
```
Deleting %TEMP%\VisualStudioTestExplorerExtensions doesn't help, neither setting debug symbols to full.
Downgrading to 2.2.0 doesn't help either.

**Comment by bradwilson** [comment]
Is this the Visual Studio UI? Does `dotnet test` from the command line work or not?

**Comment by soeron** [comment]
This is the UI. The dotnet test command works.

**Comment by bradwilson** [comment]
I cannot repro this:

![VS 2017 15.4](https://user-images.githubusercontent.com/16944/31628632-20ade536-b266-11e7-96c8-53de79aa5055.png)

We do regularly test this scenario (and several others) with our [test-explorer integration project](https://github.com/xunit/xunit.integration/tree/master/test-explorer). It would be interesting to see if you can successfully discover or run any of the tests in this project.

The fact that `dotnet test` works is a little confounding. I've honestly never heard of anybody having this exact problem (UI broken, command line functional) for any reason other than the broken temp cache (which you said you already cleared). ☹️

**Comment by soeron** [comment]
Are you running vs2017 15.4.0 ?

**Comment by soeron** [comment]
Cloned and build the solution. 
I don't have UWP sdk installed so some project are not loaded at all.
I forgot to mention that netcoreapp2.0 is working ok in the UI.
Obviously this is problem with my VS so I will try to repair and reinstall.

This is the diagnostics result in tests log.
```
[16.10.2017 22:03:51 Diagnostic] Pausing Queue..., current operation is: no current operation
[16.10.2017 22:03:51 Diagnostic] About to Enqueue operation 'WaitForBuildOperation', hashcode:62894434 
[16.10.2017 22:03:51 Diagnostic] Enqueue operation 'WaitForBuildOperation', hashcode:62894434 
[16.10.2017 22:03:51 Diagnostic] Operation left in the the queue: 1
[16.10.2017 22:03:51 Diagnostic] 	'WaitForBuildOperation', hashcode:62894434
[16.10.2017 22:03:51 Diagnostic] 

[16.10.2017 22:03:51 Diagnostic] Processing Queue .....
[16.10.2017 22:03:51 Diagnostic] Operation Dequeue : 'WaitForBuildOperation'
[16.10.2017 22:03:51 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetStarted, operationInProgress=False
[16.10.2017 22:03:51 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetStarted, InProgress=False
[16.10.2017 22:03:53 Diagnostic] Firing BuildCompleted event...
[16.10.2017 22:03:53 Diagnostic] Container Discoverer 'Microsoft.VisualStudio.TestWindow.Extensions.CPSTestContainerDiscoverer' has container changes
[16.10.2017 22:03:53 Diagnostic] Firing BuildCompleted event...
[16.10.2017 22:03:53 Diagnostic] Container Discoverer 'Microsoft.VisualStudio.TestWindow.VsAdapters.VsProjectOutputContainerDiscoverer' has container changes
[16.10.2017 22:03:53 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetFinished, operationInProgress=False
[16.10.2017 22:03:53 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetFinished, InProgress=False
[16.10.2017 22:03:53 Diagnostic] test container discoverer executor://cpsprojectoutputtestcontainerdiscoverer/v2, discovered 0 containers
[16.10.2017 22:03:53 Diagnostic] No containers found from 'Microsoft.VisualStudio.TestWindow.Extensions.CPSTestContainerDiscoverer' :
[16.10.2017 22:03:53 Diagnostic] Container discoverer 'Microsoft.VisualStudio.TestWindow.Extensions.CPSTestContainerDiscoverer' has no containers
[16.10.2017 22:03:54 Diagnostic] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.IsManagedProject(ITWProject project, ILogger logger)
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.<>c__DisplayClass19_0.<GetTargetFrameworkMoniker>b__0()
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.InvokeProjectAPIHandlesExceptionProperly(Action action, ILogger logger)
[16.10.2017 22:03:54 Diagnostic] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.IsManagedProject(ITWProject project, ILogger logger)
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.<>c__DisplayClass19_0.<GetTargetFrameworkMoniker>b__0()
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.InvokeProjectAPIHandlesExceptionProperly(Action action, ILogger logger)
[16.10.2017 22:03:54 Diagnostic] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.IsManagedProject(ITWProject project, ILogger logger)
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.<>c__DisplayClass19_0.<GetTargetFrameworkMoniker>b__0()
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.InvokeProjectAPIHandlesExceptionProperly(Action action, ILogger logger)
[16.10.2017 22:03:54 Diagnostic] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.IsManagedProject(ITWProject project, ILogger logger)
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.<>c__DisplayClass19_0.<GetTargetFrameworkMoniker>b__0()
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.InvokeProjectAPIHandlesExceptionProperly(Action action, ILogger logger)
[16.10.2017 22:03:55 Diagnostic] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.IsManagedProject(ITWProject project, ILogger logger)
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.<>c__DisplayClass19_0.<GetTargetFrameworkMoniker>b__0()
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.InvokeProjectAPIHandlesExceptionProperly(Action action, ILogger logger)
[16.10.2017 22:03:55 Diagnostic] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.IsManagedProject(ITWProject project, ILogger logger)
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.<>c__DisplayClass19_0.<GetTargetFrameworkMoniker>b__0()
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.InvokeProjectAPIHandlesExceptionProperly(Action action, ILogger logger)
[16.10.2017 22:03:56 Diagnostic] test container discoverer executor://vsprojectoutputcontainerdiscoverer/v1, discovered 11 containers
[16.10.2017 22:03:56 Diagnostic] Containers from 'Microsoft.VisualStudio.TestWindow.VsAdapters.VsProjectOutputContainerDiscoverer' :
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\MSTest_and_v2x\bin\Debug\MSTest_and_v2x.dll:executor://vsprojectoutputcontainerdiscoverer/v1
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\NUnit_and_v2x\bin\Debug\NUnit_and_v2x.dll:executor://vsprojectoutputcontainerdiscoverer/v1
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v1_net20\bin\Debug\v1_net20.dll:executor://vsprojectoutputcontainerdiscoverer/v1
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v1_net45\bin\Debug\v1_net45.dll:executor://vsprojectoutputcontainerdiscoverer/v1
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v21_net45\bin\Debug\v21_net45.dll:executor://vsprojectoutputcontainerdiscoverer/v1
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v2x_net452\bin\Debug\v2x_net452.dll:executor://vsprojectoutputcontainerdiscoverer/v1
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v2x_net452_DotNetSdk\bin\Debug\net452\v2x_net452_DotNetSdk.dll:executor://vsprojectoutputcontainerdiscoverer/v1
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v2x_net452_ReferencingProject\bin\Debug\v2x_net452_ReferencingProject.dll:executor://vsprojectoutputcontainerdiscoverer/v1
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v2x_netcoreapp1.0\bin\Debug\netcoreapp1.0\v2x_netcoreapp1.0.dll:executor://vsprojectoutputcontainerdiscoverer/v1
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v2x_netcoreapp1.1\bin\Debug\netcoreapp1.1\v2x_netcoreapp1.1.dll:executor://vsprojectoutputcontainerdiscoverer/v1
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v2x_netcoreapp2.0\bin\Debug\netcoreapp2.0\v2x_netcoreapp2.0.dll:executor://vsprojectoutputcontainerdiscoverer/v1
[16.10.2017 22:03:56 Diagnostic] About to Enqueue operation 'DiscoverSelectedOperation', hashcode:16322816 
[16.10.2017 22:03:56 Diagnostic] Enqueue operation 'DiscoverSelectedOperation', hashcode:16322816 
[16.10.2017 22:03:56 Diagnostic] Operation left in the the queue: 1
[16.10.2017 22:03:56 Diagnostic] 	'DiscoverSelectedOperation', hashcode:16322816
[16.10.2017 22:03:56 Diagnostic] 

[16.10.2017 22:03:56 Diagnostic] Processing Queue .....
[16.10.2017 22:03:56 Diagnostic] Operation Dequeue : 'DiscoverSelectedOperation'
[16.10.2017 22:03:56 Diagnostic] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.IsManagedProject(ITWProject project, ILogger logger)
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.<>c__DisplayClass19_0.<GetTargetFrameworkMoniker>b__0()
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.InvokeProjectAPIHandlesExceptionProperly(Action action, ILogger logger)
[16.10.2017 22:03:56 Diagnostic] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.IsManagedProject(ITWProject project, ILogger logger)
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.<>c__DisplayClass19_0.<GetTargetFrameworkMoniker>b__0()
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.InvokeProjectAPIHandlesExceptionProperly(Action action, ILogger logger)
[16.10.2017 22:03:56 Diagnostic] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.IsManagedProject(ITWProject project, ILogger logger)
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.<>c__DisplayClass19_0.<GetTargetFrameworkMoniker>b__0()
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.InvokeProjectAPIHandlesExceptionProperly(Action action, ILogger logger)
[16.10.2017 22:03:56 Diagnostic] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.IsManagedProject(ITWProject project, ILogger logger)
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.<>c__DisplayClass19_0.<GetTargetFrameworkMoniker>b__0()
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.InvokeProjectAPIHandlesExceptionProperly(Action action, ILogger logger)
[16.10.2017 22:03:56 Diagnostic] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.IsManagedProject(ITWProject project, ILogger logger)
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.<>c__DisplayClass19_0.<GetTargetFrameworkMoniker>b__0()
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.InvokeProjectAPIHandlesExceptionProperly(Action action, ILogger logger)
[16.10.2017 22:03:56 Diagnostic] System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.IsManagedProject(ITWProject project, ILogger logger)
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.<>c__DisplayClass19_0.<GetTargetFrameworkMoniker>b__0()
   at Microsoft.VisualStudio.Shell.Interop.TWProjectExtensions.InvokeProjectAPIHandlesExceptionProperly(Action action, ILogger logger)
[16.10.2017 22:03:56 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetStarted, operationInProgress=False
[16.10.2017 22:03:56 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetStarted, InProgress=False
[16.10.2017 22:03:56 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=ChangeDetectionStarting, operationInProgress=True
[16.10.2017 22:03:56 Diagnostic] TestDiscoveryStats.OperationStateChanged State=ChangeDetectionStarting, InProgress=False
[16.10.2017 22:03:56 Diagnostic] DiscoveryOperation<DiscoverSelectedOperation> FinishedChangedCotainers, changed container count is 11
[16.10.2017 22:03:56 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=ChangeDetectionFinished, operationInProgress=False
[16.10.2017 22:03:56 Diagnostic] TestDiscoveryStats.OperationStateChanged State=ChangeDetectionFinished, InProgress=False
[16.10.2017 22:03:56 Diagnostic] Discovering the following containers :
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\MSTest_and_v2x\bin\Debug\MSTest_and_v2x.dll
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\NUnit_and_v2x\bin\Debug\NUnit_and_v2x.dll
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v1_net20\bin\Debug\v1_net20.dll
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v1_net45\bin\Debug\v1_net45.dll
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v21_net45\bin\Debug\v21_net45.dll
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v2x_net452\bin\Debug\v2x_net452.dll
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v2x_net452_DotNetSdk\bin\Debug\net452\v2x_net452_DotNetSdk.dll
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v2x_net452_ReferencingProject\bin\Debug\v2x_net452_ReferencingProject.dll
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v2x_netcoreapp1.0\bin\Debug\netcoreapp1.0\v2x_netcoreapp1.0.dll
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v2x_netcoreapp1.1\bin\Debug\netcoreapp1.1\v2x_netcoreapp1.1.dll
[16.10.2017 22:03:56 Diagnostic] 	D:\Projects\Visual Studio\xunit.integration\test-explorer\v2x_netcoreapp2.0\bin\Debug\netcoreapp2.0\v2x_netcoreapp2.0.dll
[16.10.2017 22:03:56 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=DiscoveryStarting, operationInProgress=False
[16.10.2017 22:03:56 Diagnostic] TestDiscoveryStats.OperationStateChanged State=DiscoveryStarting, InProgress=True
[16.10.2017 22:03:56 Informational] ------ Discover test started ------
[16.10.2017 22:03:56 Diagnostic] ***    Discover TestCase using 'InMemoryUnitTestWriter' ***
[16.10.2017 22:03:56 Diagnostic] RunSettings Content:
<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>D:\Projects\Visual Studio\xunit.integration\test-explorer\TestResults</ResultsDirectory>
    <SolutionDirectory>D:\Projects\Visual Studio\xunit.integration\test-explorer\</SolutionDirectory>
    <TargetPlatform>X86</TargetPlatform>
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>
  </RunConfiguration>
</RunSettings>
[16.10.2017 22:03:56 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=DiscoveryStarted, operationInProgress=False
[16.10.2017 22:03:56 Diagnostic] TestDiscoveryStats.OperationStateChanged State=DiscoveryStarted, InProgress=True
[16.10.2017 22:03:56 Diagnostic] Checking switching: StorageMode=Dynamic, newExpectedTestCount=2, StorageParameters.DynamicSwitchThreshold=100000
[16.10.2017 22:03:56 Diagnostic] RunSettings Content:
<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>D:\Projects\Visual Studio\xunit.integration\test-explorer\TestResults</ResultsDirectory>
    <SolutionDirectory>D:\Projects\Visual Studio\xunit.integration\test-explorer\</SolutionDirectory>
    <TargetPlatform>X86</TargetPlatform>
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>
  </RunConfiguration>
</RunSettings>
[16.10.2017 22:04:57 Error] Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '1.0.5'.

[16.10.2017 22:05:57 Error] Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '1.1.2'.

[16.10.2017 22:05:58 Informational] [xUnit.net 00:00:00.4625373]   Discovering: v2x_netcoreapp2.0 (method display = ClassAndMethod)
[16.10.2017 22:05:58 Informational] [xUnit.net 00:00:00.5648470]   Discovered:  v2x_netcoreapp2.0 (running 6 test cases)
[16.10.2017 22:05:58 Diagnostic] Checking switching: StorageMode=Dynamic, newExpectedTestCount=8, StorageParameters.DynamicSwitchThreshold=100000
[16.10.2017 22:05:58 Informational] ========== Discover test finished: 8 found (0:02:01,6945593) ==========
[16.10.2017 22:05:58 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=DiscoveryFinished, operationInProgress=False
[16.10.2017 22:05:58 Diagnostic] TestDiscoveryStats.OperationStateChanged State=DiscoveryFinished, InProgress=False
[16.10.2017 22:05:58 Diagnostic] VirtualReadOnlyTestDataStore.OperationStateChanged State=OperationSetFinished, operationInProgress=False
[16.10.2017 22:05:58 Diagnostic] TestDiscoveryStats.OperationStateChanged State=OperationSetFinished, InProgress=False
```

**Comment by bradwilson** [comment]
Was the `v2x_net452` project working or broken?

> Are you running vs2017 15.4.0 ?

Yes.

> `It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.`
> `It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.1.2' was not found.`

These are to be expected if you don't have .NET Core 1.0 or 1.1 installed.

**Comment by soeron** [comment]
It was working, but didn't managed to find any tests in it. Actually I don't have .NET Core 1.0 or 1.1 which explains the error messages. But I have 2.0 installed, which should be upgrade to the first two ... at least I think so. I am repairing at the moment and will see if something changes.

**Comment by bradwilson** [comment]
.NET Core applications don't automatically "upgrade" from 1.x to 2.x (and maybe not even 1.0.x to 1.1.x, though I'm less sure about this one). It's expected that you can and would have any versions installed that you needed (since they all live side by side).

**Comment by soeron** [comment]
Repaired VS and tests are now discoverable!
Thank you very much for your support.
