### ISSUE TITLE
On Linux getting System.IO.FileNotfoundException when adding and using Moq in tests

### ISSUE THREAD

**Issue by VictorGavrish** [xunit/xunit#1531]
Repro here:

https://github.com/VictorGavrish/XunitBugRepro

## Steps to reproduce:

1. `git clone https://github.com/VictorGavrish/XunitBugRepro.git`
2. `docker pull microsoft/dotnet:2.0-sdk`
3. `docker run -itv "$(pwd)"/XunitBugRepro:/XunitBugRepro --rm microsoft/dotnet:2.0-sdk`
4. `cd XunitBugRepro/UnitTests`
5. `dotnet restore`
6. `dotnet xunit`

## Expected result:
Test runs successfully

## Actual result:
```
    UnitTests.Class1.PassingTest [FAIL]
      System.IO.FileNotFoundException : Could not load file or assembly 'Moq, Version=4.7.142.0, Culture=neutral, PublicKeyToken=69f491c39445e920'. The system cannot find the file specified.
      
      ---- System.IO.FileNotFoundException : Could not load file or assembly 'Moq, Version=4.7.142.0, Culture=neutral, PublicKeyToken=69f491c39445e920'. The system cannot find the file specified.
      
      Stack Trace:
        
        ----- Inner Stack Trace -----
           at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
           at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
           at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
           at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
           at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
           at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
  Finished:    UnitTests
=== TEST EXECUTION SUMMARY ===
   UnitTests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.173s
```

## Notes

This used to work without a problem with version `2.3.0-beta4-build3742`, but fails with `2.3.0`. There is another project in the repo which runs successfully, and the only change is the older version of xunit. It also works without problems on Windows.

**Comment by bradwilson** [comment]
Please re-test with `2.3.1-rc2-build3844`.

**Comment by VictorGavrish** [comment]
Yes, it works in the pre-release version. Thanks.
