### ISSUE TITLE
Tests failing with Visual Studio runner versions after 2.1.0

### ISSUE THREAD

**Issue by dougbu** [xunit/xunit#1533]
The https://github.com/aspnet/AspNetWebStack repo contains a small `RuntimePortable.sln` with two .NET 4.5.2 test projects. Both projects test smoothly in Visual Studio 2017 with the currently-configured VS runner (v2.1.0). Both projects fail to run any tests after upgrading the VS runner to 2.2.0, 2.3.0, or 2.3.1 RC2.

The VS Test output pane contains information about load failures (see below). However, the mentioned assemblies are in the same directory as the test assembly and any needed binding redirects are in place. It's as if information in the xunit.runner.json file or {test assembly}.config files is ignored. That is, But, test discovery works perfectly still.

Any debugging suggestions, workarounds, et cetera much appreciated.

#### VS Test output pane
```
[2017-10-25 21:58:28 Informational] ------ Load Playlist started ------
[2017-10-25 21:58:28 Informational] ========== Load Playlist finished (0:00:00.0040055) ==========
[2017-10-25 21:58:28 Informational] ------ Discover test started ------
[2017-10-25 21:58:30 Informational] [xUnit.net 00:00:00.3023729]   Discovering: Microsoft.TestCommon (app domain = on [no shadow copy], method display = ClassAndMethod)
[2017-10-25 21:58:30 Informational] [xUnit.net 00:00:00.3539477]   Discovered:  Microsoft.TestCommon (running 0 test cases)
[2017-10-25 21:58:30 Informational] [xUnit.net 00:00:00.5270138]   Discovering: System.Net.Http.Formatting.NetCore.Test (app domain = on [no shadow copy], method display = ClassAndMethod)
[2017-10-25 21:58:30 Informational] [xUnit.net 00:00:01.2727104]   Discovered:  System.Net.Http.Formatting.NetCore.Test (running 763 test cases)
[2017-10-25 21:58:31 Informational] [xUnit.net 00:00:01.4905415]   Discovering: System.Net.Http.Formatting.NetStandard.Test (app domain = on [no shadow copy], method display = ClassAndMethod)
[2017-10-25 21:58:31 Informational] [xUnit.net 00:00:02.2316925]   Discovered:  System.Net.Http.Formatting.NetStandard.Test (running 763 test cases)
[2017-10-25 21:58:32 Informational] ========== Discover test finished: 1526 found (0:00:04.3930913) ==========
[2017-10-25 21:58:39 Informational] ------ Run test started ------
[2017-10-25 21:58:39 Warning] [xUnit.net 00:00:00.1718097] Skipping: System.Net.Http.Formatting.NetCore.Test (could not find dependent assembly 'System.Net.Http.Primitives, Version=1.5.0')
[2017-10-25 21:58:39 Warning] [xUnit.net 00:00:00.2625715] Exception discovering tests from System.Net.Http.Formatting.NetStandard.Test: System.TypeLoadException: Method 'get_CanWriteAnyTypes' on type 'System.Net.Http.Formatting.Mocks.MockMediaTypeFormatter' from assembly 'System.Net.Http.Formatting.NetStandard.Test, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' is overriding a method that is not visible from that assembly.
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at Xunit.Sdk.ReflectionAssemblyInfo.GetTypes(Boolean includePrivateTypes)
   at Xunit.Sdk.TestCollectionFactoryHelper.GetTestCollectionDefinitions(IAssemblyInfo assemblyInfo, IMessageSink diagnosticMessageSink)
   at Xunit.Sdk.CollectionPerClassTestCollectionFactory..ctor(ITestAssembly testAssembly, IMessageSink diagnosticMessageSink)
   at Xunit.Sdk.ExtensibilityPointFactory.GetXunitTestCollectionFactory(IMessageSink diagnosticMessageSink, IAttributeInfo collectionBehaviorAttribute, ITestAssembly testAssembly)
   at Xunit.Sdk.XunitTestFrameworkDiscoverer..ctor(IAssemblyInfo assemblyInfo, ISourceInformationProvider sourceProvider, IMessageSink diagnosticMessageSink, IXunitTestCollectionFactory collectionFactory)
   at Xunit.Sdk.XunitTestFramework.CreateDiscoverer(IAssemblyInfo assemblyInfo)
   at Xunit.Sdk.TestFramework.GetDiscoverer(IAssemblyInfo assemblyInfo)
   at Xunit.Sdk.TestFrameworkProxy.GetDiscoverer(IAssemblyInfo assembly)
   at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk)
   at Xunit.XunitFrontController.CreateInnerController()
   at Xunit.XunitFrontController.EnsureInitialized()
   at Xunit.Runner.VisualStudio.VsTestRunner.DiscoverTestsInSource[TVisitor](XunitFrontController framework, LoggerHelper logger, TestPlatformContext testPlatformContext, Func`4 visitorFactory, Action`4 visitComplete, String assemblyFileName, Boolean shadowCopy, TestAssemblyConfiguration configuration)
[2017-10-25 21:58:39 Warning] No test is available in C:\dd\dnx\Universe++\AspNetWebStack\bin\Debug\Test\NetCore\System.Net.Http.Formatting.NetCore.Test.dll C:\dd\dnx\Universe++\AspNetWebStack\bin\Debug\Test\NetStandard\System.Net.Http.Formatting.NetStandard.Test.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[2017-10-25 21:58:40 Informational] ========== Run test finished: 0 run (0:00:00.9864462) ==========
```

#### xunit.runner.json
``` json
{
  "appDomain": "denied",
  "diagnosticMessages": true,
  "preEnumerateTheories": false,
  "shadowCopy":  false
}
```

#### System.Net.Http.Formatting.NetCore.Test.dll.config
``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-7.0.0.0" newVersion="7.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Primitives" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.2.13.0" newVersion="4.2.13.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Extensions" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.13.0" newVersion="2.2.13.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

#### System.Net.Http.Formatting.NetStandard.Test.dll.config
``` xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by bradwilson** [comment]
This line is the clue:

`[2017-10-25 21:58:39 Warning] [xUnit.net 00:00:00.1718097] Skipping: System.Net.Http.Formatting.NetCore.Test (could not find dependent assembly 'System.Net.Http.Primitives, Version=1.5.0')`

You're using binding redirects, which **_require_** app domains. Without an app domain, the binding redirects in use will be those that belong to the launching process (which is `vstest.executionengine.x86.exe` or one of its brethren). We need the app domain to feed it your custom configuration file (in this case, `System.Net.Http.Formatting.NetCore.Test.dll.config`) so that the system will honor your binding redirect request.

FWIW, your tests (as they are today) won't run with ANY runner except the 2.1 (or older) Visual Studio runner. Here is what you'd see trying to run them with the 2.1 console runner:

```
 PS> C:\Users\Brad\.nuget\packages\xunit.runner.console\2.1.0\tools\xunit.console.x86.exe bin\Debug\Test\NetCore\System.Net.Http.Formatting.NetCore.Test.dll

xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
```

So, why do they pass with 2.1?

The Visual Studio runner has historically ignored requests to turn off app domains, because they have always been required (along with shadow copying) to prevent DLLs from being locked, which breaks your ability to rebuild them inside of VS.

About a year ago, for performance reasons we changed this behavior (in consultation with the VSTest team). They pass us a flag to let us know that we don't need an app domain to prevent file locks, and then honor your request in your `xunit.runner.json` to prevent creating a _second_ app domain when it's not necessary. This can help performance when writing desktop CLR unit tests which _don't_ use any binding redirects and/or `System.Configuration`.

Solution: Remove `"appDomain": "denied"`.

**Comment by dougbu** [comment]
@bradwilson thanks very much for the help.

Looks as if we were aware of some AppDomain requirements: That setting is overridden when we execute the MSBuild xUnit runner i.e. `appDomain` was `denied` only when using the VS runner, where it was previously ignored 😦
