### ISSUE TITLE
VS2017 15.4.2 - Unable to run tests for projects targeting .NET Framework 4.6.x

### ISSUE THREAD

**Issue by felpel** [xunit/xunit#1542]
Following a brief question on xUnit's Slack, I'm creating the following issue.

We're using xUnit as our main test framework in multiple .NET core/.NET framework test projects. Since I've updated Visual Studio to 15.4.2, I'm unable to run some tests within Visual Studio.

I'm unable to run xUnit tests with the following conditions:

- Visual Studio 2017 **`15.4.2`**;
- Target .NET framework `4.6.x` (doesn't work either in .NET core project or .NET framework);

I'm always stuck with this exception thrown in the Output panel:

```
[2017-11-02 11:59:13 AM Warning] [xUnit.net 00:00:00.0067634] Skipping: AutoVu.SaaS.Ptms.Dss.Functions.ApiTests (could not find dependent assembly 'Microsoft.Extensions.DependencyModel, Version=1.1.0')
[2017-11-02 11:59:13 AM Informational] [xUnit.net 00:00:00.2942063]   Discovering: AutoVu.SaaS.Ptms.Dss.Functions.ApiTests
[2017-11-02 11:59:14 AM Informational] [xUnit.net 00:00:00.7375313]   Discovered:  AutoVu.SaaS.Ptms.Dss.Functions.ApiTests
[2017-11-02 11:59:14 AM Informational] ========== Discover test finished: 33 found (0:00:00.8979395) ==========
[2017-11-02 11:59:23 AM Informational] ------ Run test started ------
[2017-11-02 11:59:23 AM Error] [xUnit.net 00:00:00.0231355] AutoVu.SaaS.Ptms.Dss.Functions.ApiTests: Catastrophic failure: System.TypeInitializationException: The type initializer for 'Xunit.DiaSession' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Xunit.DiaSession..cctor()
   --- End of inner exception stack trace ---
   at Xunit.DiaSession..ctor(String assemblyFileName)
   at Xunit.DiaSessionWrapper..ctor(String assemblyFilename)
   at Xunit.XunitFrontController..ctor(AppDomainSupport appDomainSupport, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticMessageSink)
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)
[2017-11-02 11:59:23 AM Informational] ========== Run test finished: 0 run (0:00:00.0725536) ==========
```

Notes: 
- I'm able to run successfully the tests from the command line (or in our CI build process):
```posh
. "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" AutoVu.SaaS.Ptms.Dss
.Functions.ApiTests.dll /Logger:trx /InIsolation 
```
- I've already tried to remove the suggested folder `%TEMP%\VisualStudioTestExplorerExtensions` and restart VS without any success.

Thanks in advance for your help!

**Comment by bradwilson** [comment]
Please provide a repro project. I am unable to reproduce following the [Getting Started](https://xunit.github.io/docs/getting-started-desktop.html) directions, targeting .NET 4.6.2:

![VS2017 15.4.2](https://user-images.githubusercontent.com/16944/32348537-50a553be-bfd1-11e7-82fc-3b31f087df53.png)

**Comment by felpel** [comment]
Are you working with the mentioned Visual Studio version? I've been able to revert back to VS2017 15.3.5 and run successfully those assemblies.

**Comment by bradwilson** [comment]
![image](https://user-images.githubusercontent.com/16944/32349453-5a12fdf4-bfd4-11e7-874d-6210ea39baf4.png)

**Comment by felpel** [comment]
@bradwilson I think I might have found the source of my problem.

In `%TEMP%\VisualStudioTestExplorerExtensions`, there were two folders, one for the `2.2.0` runner and another one for the updated `2.3.1`. I've consolidated the versions in my solution for the `xunit.runner.visualstudio` package to point to the latest one and everything seems fine now.

**Comment by bradwilson** [comment]
Yep, this is a limitation within Visual Studio.

**Comment by mclagett** [comment]
We are experiencing the "The type initializer for 'Xunit.DiaSession' threw an exception. " issue having updated Windows 10 to the Windows Creator version (Version 1709 -- OS Build 16299.64), Visual Studio to 15.4.5, and xUnit to version 2.3.1.  I even tried updating to 2.4.0-beta1-build3891, but I still get the issue.  I tried deleting contents of %TEMP%\VisualStudioTestExplorerExtensions, but I still get the problem.   Interesting thing:  unlike felpel above, I still only ever see a folder for the 2.2.0 runner added to %TEMP%\VisualStudioTestExplorerExtensions, never one for the updated 2.3.1.  Wondering if that might have something to do with the problem?  Wondering if anyone has any ideas for me?

**Comment by bradwilson** [comment]
Open a new bug with a repro project.

**Comment by mclagett** [comment]
Thank you for your reply.  When I went to create a simple repo project, the folder for 2.3.1 was added to %TEMP%\VisualStudioTestExplorerExtensions and the repo project did not have the problem.  So before submitting a bug I will try to work on figuring why our project (which is really very large and complex) doesn't cause the 2.3.1 extensions files to be loaded.

**Comment by bradwilson** [comment]
Two things to consider:

- Make sure all your projects are upgraded; only a single version of the `xunit.runner.visualstudio` package is supported (no mixing & matching)
- After you do an update on the package, you MUST shut down Visual Studio; it caches and uses the previous version even after you've updated

**Comment by zijianhuang** [comment]
It seemly happened after Windows 10 update, however, it could be just coincident. I have 1 VS sln with all tests failed with the error mentioned in the OP, while other VS sln are fine. I believe the culprit is in some corrupted or locked files in %temp%. I had to restart computer first, then delete all files in %temp%. Then all tests work again.

**Comment by bradwilson** [comment]
@zijianhuang: https://xunit.github.io/docs/getting-started-dotnet-core.html#run-tests-visualstudio

![image](https://user-images.githubusercontent.com/16944/33862121-2a99bea6-de96-11e7-91bb-6433de823188.png)

**Comment by Aparna-Gaddam** [comment]
Hi ,

Are you able to debug the testmethods?
I am able to run the test methods as showin in command promt.
