### ISSUE TITLE
Trailing empty trait value causes IndexOutOfRangeException

### ISSUE THREAD

**Issue by genlu** [xunit/xunit#1562]
The test discovery crashes with the attached project. When running in VS, the test explorer indicator would just keep spinning w/o any error message (this is probably a separate issue for https://github.com/microsoft/vstest/).
```
Starting test execution, please wait...
[xUnit.net 00:00:00.4795126]   Discovering: XUnitTestProject1
[xUnit.net 00:07:02.0036778] Exception discovering tests from XUnitTestProject1: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Xunit.TestCaseDescriptor..ctor(String descriptorText) in C:\Users\gel\Documents\GitHub\xunit\src\xunit.runner.utility\Descriptor\TestCaseDescriptor.cs:line 70
   at Xunit.Xunit2Discoverer.<>c.<GetTestCaseDescriptors>b__33_0(String x) in C:\Users\gel\Documents\GitHub\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2Discoverer.cs:line 202
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Xunit.Xunit2Discoverer.GetTestCaseDescriptors(List`1 testCases, Boolean includeSerialization) in C:\Users\gel\Documents\GitHub\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2Discoverer.cs:line 202
   at Xunit.XunitFrontController.GetTestCaseDescriptors(List`1 testCases, Boolean includeSerialization) in C:\Users\gel\Documents\GitHub\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 176
   at Xunit.Runner.VisualStudio.VsTestRunner.GetVsTestCases(String source, ITestFrameworkDiscoverer discoverer, VsExecutionDiscoverySink visitor, LoggerHelper logger, TestPlatformContext testPlatformContext) in C:\Users\gel\Documents\GitHub\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 762
   at Xunit.Runner.VisualStudio.VsTestRunner.<>c__DisplayClass17_1.<RunTestsInAssembly>b__1(String source, ITestFrameworkDiscoverer discoverer, ITestFrameworkDiscoveryOptions discoveryOptions, VsExecutionDiscoverySink visitor) in C:\Users\gel\Documents\GitHub\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 472
   at Xunit.Runner.VisualStudio.VsTestRunner.DiscoverTestsInSource[TVisitor](XunitFrontController framework, LoggerHelper logger, TestPlatformContext testPlatformContext, Func`4 visitorFactory, Action`4 visitComplete, String assemblyFileName, Boolean shadowCopy, TestAssemblyConfiguration configuration) in C:\Users\gel\Documents\GitHub\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 274
```

In this particular case, the value of `descriptorText` that passed to the constructor of `TestCaseDescriptor` is 

```
"C XUnitTestProject1.UnitTest1\nM Test1\nU 3f3c043bdf78a63296371ac98053e61a39926096\nD XUnitTestProject1.UnitTest1.Test1\nT Category\n\n"
```

Repro project:
https://1drv.ms/u/s!AkbPBE3d3Hv-hLtGkL_fzuc6vMNPLw

**Comment by bradwilson** [comment]
The problem appears to be trait values which are empty/null.

The work around for right now is to not use such values.
