### ISSUE TITLE
XUnit tests fail on Linux with error -> Could not load file or assembly Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.0.1.0

### ISSUE THREAD

**Issue by jsacapdev** [xunit/xunit#1583]
Repository: https://github.com/Capgemini/CoreXPlatform

Build fails on local development machine and Travis CI: https://travis-ci.org/Capgemini/CoreXPlatform

The command that is being run to invoke the tests is:

`dotnet xunit -configuration Release -diagnostics -stoponfail --fx-version 2.0.0`

Note, it works on Windows: https://ci.appveyor.com/project/jsacapdev/corexplatform

I am not sure if this is related to https://github.com/xunit/xunit/issues/1573. I have tried:
--fx-version 2.0.0
--fx-version 2.0.3
<RuntimeFrameworkVersion>2.0.0</RuntimeFrameworkVersion>
<RuntimeFrameworkVersion>2.0.3</RuntimeFrameworkVersion>

With no success.

The Web API being tested is being complied against the ASPNET Core NuGet meta package 2.0.3.

Output from tests:

```
Detecting target frameworks in CoreXPlatform.API.Tests.csproj...
Building for framework netcoreapp2.0...
  CoreXPlatform.API -> /home/tda/git/CoreXPlatform/src/CoreXPlatform.API/bin/Release/netcoreapp2.0/CoreXPlatform.API.dll
  CoreXPlatform.API.Tests -> /home/tda/git/CoreXPlatform/test/CoreXPlatform.API.Tests/bin/Release/netcoreapp2.0/CoreXPlatform.API.Tests.dll
Running .NET Core 2.0.0 tests for framework netcoreapp2.0...
xUnit.net Console Runner (64-bit .NET Core 4.6.00001.0)
  Discovering: CoreXPlatform.API.Tests (method display = ClassAndMethod)
  Discovered:  CoreXPlatform.API.Tests (running 1 test case)
  Starting:    CoreXPlatform.API.Tests (parallel test collections = on, max threads = 1)
    CoreXPlatform.API.Tests.ValuesControllerTests.ValuesController_Get_Ok [FAIL]
      System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

      ---- System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.AspNetCore.Mvc.ViewFeatures, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

      Stack Trace:

        ----- Inner Stack Trace -----
           at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
           at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
           at System.Reflection.Assembly.Load(AssemblyName assemblyRef, IntPtr ptrLoadContextBinder)
           at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
           at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
           at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
  Finished:    CoreXPlatform.API.Tests
Canceling due to test failure...
=== TEST EXECUTION SUMMARY ===
   CoreXPlatform.API.Tests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.195s```

**Comment by YLPeng** [comment]
How did you fix this problem?
