### ISSUE TITLE
Newer platforms (macOS 10.13, Ubuntu 17, Debian 9) are broken with `dotnet xunit`

### ISSUE THREAD

**Issue by andreabalducci** [xunit/xunit#1585]
Platform: MacOs
Dotnet version: 2.0.0

Upgrading xunit-runner from 2.3.0-beta1-build3642 to 2.3.0 breaks SqlClient (2.3.1 is broken too).

Repro: https://github.com/andreabalducci/xunit-issue

```
using System;
using System.Data.SqlClient;
using Xunit;

namespace xunit_issue
{
    public class Sqltest
    {
        [Fact]
        public void should_connect()
        {
            var ex = Assert.Throws<InvalidOperationException>(() =>
             {
                 using (var connection = new SqlConnection())
                 {
                     using (var cmd = new SqlCommand("SELECT 1"))
                     {
                         cmd.ExecuteNonQuery();
                     }
                 }
             });

             Assert.True(ex.Message.StartsWith("ExecuteNonQuery: Connection property"));
        }
    }
}
```

```
Running .NET Core 2.0.0 tests for framework netcoreapp2.0...
xUnit.net Console Runner (64-bit .NET Core 4.6.00001.0)
  Discovering: xunit-issue
  Discovered:  xunit-issue
  Starting:    xunit-issue
    xunit_issue.Sqltest.should_connect [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.InvalidOperationException)
      Actual:   typeof(System.PlatformNotSupportedException): System.Data.SqlClient is not supported on this platform.
      Stack Trace:
           at System.Data.SqlClient.SqlConnection..ctor()
        /Users/andrea/dev/xunit-issue/Sqltest.cs(14,0): at xunit_issue.Sqltest.<>c.<should_connect>b__0_0()
  Finished:    xunit-issue
=== TEST EXECUTION SUMMARY ===
   xunit-issue  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0,271s
```

**Comment by bradwilson** [comment]
This appears to be a bug in .NET Core.

When you run `dotnet xunit -internaldiagnostics`, the reported runtime graph is:

`
[DependencyContextAssemblyCache..ctor] Runtime graph: ['osx-x64','osx','osx.10.10','osx.10.10-x64','osx.10.11','osx.10.11-x64','osx.10.12','osx.10.12-x64','osx-corert','osx-x64-corert','osx.10.10-corert','osx.10.10-x64-corert','osx.10.11-corert','osx.10.11-x64-corert','osx.10.12-corert','osx.10.12-x64-corert']
DependencyContextAssemblyCache..ctor] Compatible runtimes: ['osx.10.13-x64','']
`

The dependency inside the `.deps.json` file shows `unix` as the runtime ID:

```json
"System.Data.SqlClient/4.4.0": {
  "dependencies": {
    "Microsoft.Win32.Registry": "4.4.0",
    "System.Security.Principal.Windows": "4.4.0",
    "System.Text.Encoding.CodePages": "4.4.0",
    "runtime.native.System.Data.SqlClient.sni": "4.4.0"
  },
  "runtime": {
    "lib/netstandard2.0/System.Data.SqlClient.dll": {}
  },
  "runtimeTargets": {
    "runtimes/unix/lib/netstandard2.0/System.Data.SqlClient.dll": {
      "rid": "unix",
      "assetType": "runtime"
    },
    "runtimes/win/lib/netstandard2.0/System.Data.SqlClient.dll": {
      "rid": "win",
      "assetType": "runtime"
    }
  }
}
```

This has the appearance of being a bug with .NET Core for failing to list `unix` as a compatible runtime for OS X/macOS. I verified this with macOS 10.13 and both .NET SDK 2.0.0 and 2.0.3.

Also, you forgot to upgrade the `dotnet-xunit` runner to `2.3.1`.

**Comment by bradwilson** [comment]
I take it back. It appears that the runtime graph functionality is broken with macOS 10.13. Here's what I get running on Ubuntu:

```
[DependencyContextAssemblyCache..ctor] Runtime graph: ['linux-arm','linux-x64','tizen.4.0.0-armel','linux','linux-x86','linux-armel','linux-arm64','rhel','rhel-x64','rhel.7','rhel.7-x64','rhel.7.0','rhel.7.0-x64','rhel.7.1','rhel.7.1-x64','rhel.7.2','rhel.7.2-x64','rhel.7.3','rhel.7.3-x64','rhel.7.4','rhel.7.4-x64','ol','ol-x64','ol.7','ol.7-x64','ol.7.0','ol.7.0-x64','ol.7.1','ol.7.1-x64','ol.7.2','ol.7.2-x64','centos','centos-x64','centos.7','centos.7-x64','debian','debian-x64','debian-x86','debian-arm','debian-armel','debian-arm64','debian.8','debian.8-x64','debian.8-x86','debian.8-arm','debian.8-armel','debian.8-arm64','tizen','tizen-armel','ubuntu','ubuntu-x64','ubuntu-x86','ubuntu-arm','ubuntu-arm64','ubuntu.14.04','ubuntu.14.04-x64','ubuntu.14.04-x86','ubuntu.14.04-arm','ubuntu.14.10','ubuntu.14.10-x64','ubuntu.14.10-x86','ubuntu.14.10-arm','ubuntu.15.04','ubuntu.15.04-x64','ubuntu.15.04-x86','ubuntu.15.04-arm','ubuntu.15.10','ubuntu.15.10-x64','ubuntu.15.10-x86','ubuntu.15.10-arm','ubuntu.16.04','ubuntu.16.04-x64','ubuntu.16.04-x86','ubuntu.16.04-arm','ubuntu.16.04-arm64','ubuntu.16.10','ubuntu.16.10-x64','ubuntu.16.10-x86','ubuntu.16.10-arm','ubuntu.16.10-arm64','linuxmint.17','linuxmint.17-x64','linuxmint.17.1','linuxmint.17.1-x64','linuxmint.17.2','linuxmint.17.2-x64','linuxmint.17.3','linuxmint.17.3-x64','linuxmint.18','linuxmint.18-x64','linuxmint.18.1','linuxmint.18.1-x64','fedora','fedora-x64','fedora.23','fedora.23-x64','fedora.24','fedora.24-x64','fedora.25','fedora.25-x64','fedora.26','fedora.26-x64','opensuse','opensuse-x64','opensuse.13.2','opensuse.13.2-x64','opensuse.42.1','opensuse.42.1-x64','linux-corert','linux-x64-corert','linux-arm-corert','linux-arm64-corert','rhel-corert','rhel-x64-corert','rhel.7-corert','rhel.7-x64-corert','rhel.7.0-corert','rhel.7.0-x64-corert','rhel.7.1-corert','rhel.7.1-x64-corert','rhel.7.2-corert','rhel.7.2-x64-corert','ol-corert','ol-x64-corert','ol.7-corert','ol.7-x64-corert','ol.7.0-corert','ol.7.0-x64-corert','ol.7.1-corert','ol.7.1-x64-corert','centos-corert','centos-x64-corert','centos.7-corert','centos.7-x64-corert','debian-corert','debian-x64-corert','debian-arm-corert','debian-arm64-corert','debian.8-corert','debian.8-x64-corert','debian.8-arm-corert','debian.8-arm64-corert','ubuntu-corert','ubuntu-x64-corert','ubuntu.14.04-corert','ubuntu.14.04-x64-corert','ubuntu.14.10-corert','ubuntu.14.10-x64-corert','ubuntu.15.04-corert','ubuntu.15.04-x64-corert','ubuntu.15.10-corert','ubuntu.15.10-x64-corert','ubuntu.16.04-corert','ubuntu.16.04-x64-corert','ubuntu.16.10-corert','ubuntu.16.10-x64-corert','linuxmint.17-corert','linuxmint.17-x64-corert','linuxmint.17.1-corert','linuxmint.17.1-x64-corert','linuxmint.17.2-corert','linuxmint.17.2-x64-corert','linuxmint.17.3-corert','linuxmint.17.3-x64-corert','linuxmint.18-corert','linuxmint.18-x64-corert','fedora-corert','fedora-x64-corert','fedora.23-corert','fedora.23-x64-corert','fedora.24-corert','fedora.24-x64-corert','opensuse-corert','opensuse-x64-corert','opensuse.13.2-corert','opensuse.13.2-x64-corert','opensuse.42.1-corert','opensuse.42.1-x64-corert']
[DependencyContextAssemblyCache..ctor] Compatible runtimes: ['ubuntu.16.04','ubuntu-x64','ubuntu','debian-x64','debian','linux-x64','linux','unix-x64','unix','any','base','ubuntu.16.04-x64','']
```

Notice how the compatible runtimes is filled out correctly, and includes `unix`.

**Comment by natemcmaster** [comment]
How are you determining this list? `unix` should be an "import" included in the list of RIDs:

https://github.com/dotnet/corefx/blob/v2.0.0/pkg/Microsoft.NETCore.Platforms/runtime.json#L183-L185

**Comment by natemcmaster** [comment]
It looks like only `osx-10.10`, `osx-10.11`, and `osx-10.12` are included in the list. Might make sense for xunit to fallback to the latest `osx-*` when running on newer versions of macOS. Not sure what the runtime does though...

**Comment by bradwilson** [comment]
@natemcmaster I get this list from the runtime itself (from `DependencyContext.RuntimeGraph`).

**Comment by bradwilson** [comment]
https://github.com/xunit/xunit/blob/b7c3bedaeecc03f2e578c59f2403a8a5a8e2aa62/src/xunit.runner.utility/Utility/DependencyContextAssemblyCache.cs#L40-L49

**Comment by bradwilson** [comment]
I'm pretty sure you're the one who told me to do it this way. 😉

**Comment by bradwilson** [comment]
@natemcmaster What should my fallback strategy be? What are the official parts of the runtime ID, and is there an official parser? Which things should I drop, and in what order?

**Comment by bradwilson** [comment]
Looks like the official format is here: https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md

`[os].[version]-[architecture]-[additional qualifiers]`

It's not clear looking at [runtime.json](https://github.com/dotnet/corefx/blob/master/pkg/Microsoft.NETCore.Platforms/runtime.json) whether a simple fallback to `[os]` is sufficient, given that there are many permutations here, and I don't want to guess.

**Comment by natemcmaster** [comment]
If you're trying to imitate corehost, you can follow what they do: hard-code a fallback RID to use when you can't find the current RID in the given list of runtime graphs. I looked into how the runtime does this...here are the details.

In a portable .NET Core 2.0.0 app, `DependencyContext.Default.RuntimeGraph` will give you a group of items like this:
```
Runtime = Fallbacks
--------------------
osx-x64 = osx,unix-x64,unix,any,base
osx = unix,any,base
osx.10.10 = osx,unix,any,base
osx.10.10-x64 = osx.10.10,osx-x64,osx,unix-x64,unix,any,base
osx.10.11 = osx.10.10,osx,unix,any,base
osx.10.11-x64 = osx.10.11,osx.10.10-x64,osx.10.10,osx-x64,osx,unix-x64,unix,any,base
osx.10.12 = osx.10.11,osx.10.10,osx,unix,any,base
osx.10.12-x64 = osx.10.12,osx.10.11-x64,osx.10.11,osx.10.10-x64,osx.10.10,osx-x64,osx,unix-x64,unix,any,base
osx-corert = unix-corert,osx,corert,unix,any,base
osx-x64-corert = osx-corert,unix-x64-corert,osx-x64,unix-corert,osx,unix-x64,corert,unix,any,base
osx.10.10-corert = osx-corert,osx.10.10,unix-corert,osx,corert,unix,any,base
osx.10.10-x64-corert = osx.10.10-corert,osx-x64-corert,osx.10.10-x64,osx-corert,osx.10.10,unix-x64-corert,osx-x64,unix-corert,osx,unix-x64,corert,unix,any,base
osx.10.11-corert = osx.10.10-corert,osx.10.11,osx-corert,osx.10.10,unix-corert,osx,corert,unix,any,base
osx.10.11-x64-corert = osx.10.11-corert,osx.10.10-x64-corert,osx.10.11-x64,osx.10.10-corert,osx.10.11,osx-x64-corert,osx.10.10-x64,osx-corert,osx.10.10,unix-x64-corert,osx-x64,unix-corert,osx,unix-x64,corert,unix,any,base
osx.10.12-corert = osx.10.11-corert,osx.10.12,osx.10.10-corert,osx.10.11,osx-corert,osx.10.10,unix-corert,osx,corert,unix,any,base
osx.10.12-x64-corert = osx.10.12-corert,osx.10.11-x64-corert,osx.10.12-x64,osx.10.11-corert,osx.10.12,osx.10.10-x64-corert,osx.10.11-x64,osx.10.10-corert,osx.10.11,osx-x64-corert,osx.10.10-x64,osx-corert,osx.10.10,unix-x64-corert,osx-x64,unix-corert,osx,unix-x64,corert,unix,any,base
```

The problem is that `RuntimeEnvironment.GetRuntimeIdentifier()` will give you `osx.10.13-x64`, which is not defined in this list. I looked up how the runtime handles this and found this:

https://github.com/dotnet/core-setup/blob/863047f3ca16bada3ffc82493d1dbad6e560b80a/src/corehost/cli/deps_format.cpp#L147-L157
```c++
    // If the current RID is not present in the RID fallback graph, then the platform
    // is unknown to us. At this point, we will fallback to using the base RIDs and attempt
    // asset lookup using them.
    //
    // We do the same even when the RID is empty.
    if (currentRid.empty() || (rid_fallback_graph.count(currentRid) == 0))
    {
        currentRid = pal::get_current_os_fallback_rid() + pal::string_t(_X("-")) + get_arch();

        trace::info(_X("Falling back to base HostRID: %s"), currentRid.c_str());
    }
```

The return value of get_current_os_fallback_rid() is hard-coded.

https://github.com/dotnet/core-setup/blob/863047f3ca16bada3ffc82493d1dbad6e560b80a/src/corehost/common/pal.h#L53-L73
```c
// When running on a platform that is not supported in RID fallback graph (because it was unknown
// at the time the SharedFX in question was built), we need to use a reasonable fallback RID to allow
// consuming the native assets.
//
// For Windows and OSX, we will maintain the last highest RID-Platform we are known to support for them as the 
// degree of compat across their respective releases is usually high.
//
// We cannot maintain the same (compat) invariant for linux and thus, we will fallback to using lowest RID-Plaform.
#if defined(_WIN32)
#define LIB_PREFIX
#define MAKE_LIBNAME(NAME) (_X(NAME) _X(".dll"))
#define FALLBACK_HOST_RID _X("win10")
#elif defined(__APPLE__)
#define LIB_PREFIX _X("lib")
#define MAKE_LIBNAME(NAME) (LIB_PREFIX _X(NAME) _X(".dylib"))
#define FALLBACK_HOST_RID _X("osx.10.12")
#else
#define LIB_PREFIX _X("lib")
#define MAKE_LIBNAME(NAME) (LIB_PREFIX _X(NAME) _X(".so"))
#define FALLBACK_HOST_RID _X("linux")
#endif
```

**Comment by vassilvk** [comment]
The same issue is observed in [Microsoft's ASP.NET Core 2.0.4 latest Docker images](https://hub.docker.com/r/microsoft/aspnetcore-build/).

For example, using `System.Data.SqlClient` in an `xunit` test executed in a Docker container based on [`microsoft/aspnetcore-build:2.0.4-2.1.3`](https://github.com/aspnet/aspnet-docker/blob/master/2.0/stretch/sdk/Dockerfile) (which is also the `latest` at the moment), one gets the following when running `xunit` with `-internaldiagnostics`:

**Runtime graph:**
`[DependencyContextAssemblyCache..ctor] Runtime graph: ['linux-arm','linux-x64','rhel.6-x64','tizen.4.0.0-armel','linux','linux-x86','linux-armel','linux-arm64','rhel','rhel-x64','rhel.6','rhel.7','rhel.7-x64','rhel.7.0','rhel.7.0-x64','rhel.7.1','rhel.7.1-x64','rhel.7.2','rhel.7.2-x64','rhel.7.3','rhel.7.3-x64','rhel.7.4','rhel.7.4-x64','ol','ol-x64','ol.7','ol.7-x64','ol.7.0','ol.7.0-x64','ol.7.1','ol.7.1-x64','ol.7.2','ol.7.2-x64','centos','centos-x64','centos.7','centos.7-x64','debian','debian-x64','debian-x86','debian-arm','debian-armel','debian-arm64','debian.8','debian.8-x64','debian.8-x86','debian.8-arm','debian.8-armel','debian.8-arm64','tizen','tizen-armel','ubuntu','ubuntu-x64','ubuntu-x86','ubuntu-arm','ubuntu-arm64','ubuntu.14.04','ubuntu.14.04-x64','ubuntu.14.04-x86','ubuntu.14.04-arm','ubuntu.14.10','ubuntu.14.10-x64','ubuntu.14.10-x86','ubuntu.14.10-arm','ubuntu.15.04','ubuntu.15.04-x64','ubuntu.15.04-x86','ubuntu.15.04-arm','ubuntu.15.10','ubuntu.15.10-x64','ubuntu.15.10-x86','ubuntu.15.10-arm','ubuntu.16.04','ubuntu.16.04-x64','ubuntu.16.04-x86','ubuntu.16.04-arm','ubuntu.16.04-arm64','ubuntu.16.10','ubuntu.16.10-x64','ubuntu.16.10-x86','ubuntu.16.10-arm','ubuntu.16.10-arm64','linuxmint.17','linuxmint.17-x64','linuxmint.17.1','linuxmint.17.1-x64','linuxmint.17.2','linuxmint.17.2-x64','linuxmint.17.3','linuxmint.17.3-x64','linuxmint.18','linuxmint.18-x64','linuxmint.18.1','linuxmint.18.1-x64','fedora','fedora-x64','fedora.23','fedora.23-x64','fedora.24','fedora.24-x64','fedora.25','fedora.25-x64','fedora.26','fedora.26-x64','opensuse','opensuse-x64','opensuse.13.2','opensuse.13.2-x64','opensuse.42.1','opensuse.42.1-x64','linux-corert','linux-x64-corert','linux-arm-corert','linux-arm64-corert','rhel-corert','rhel-x64-corert','rhel.7-corert','rhel.7-x64-corert','rhel.7.0-corert','rhel.7.0-x64-corert','rhel.7.1-corert','rhel.7.1-x64-corert','rhel.7.2-corert','rhel.7.2-x64-corert','ol-corert','ol-x64-corert','ol.7-corert','ol.7-x64-corert','ol.7.0-corert','ol.7.0-x64-corert','ol.7.1-corert','ol.7.1-x64-corert','centos-corert','centos-x64-corert','centos.7-corert','centos.7-x64-corert','debian-corert','debian-x64-corert','debian-arm-corert','debian-arm64-corert','debian.8-corert','debian.8-x64-corert','debian.8-arm-corert','debian.8-arm64-corert','ubuntu-corert','ubuntu-x64-corert','ubuntu.14.04-corert','ubuntu.14.04-x64-corert','ubuntu.14.10-corert','ubuntu.14.10-x64-corert','ubuntu.15.04-corert','ubuntu.15.04-x64-corert','ubuntu.15.10-corert','ubuntu.15.10-x64-corert','ubuntu.16.04-corert','ubuntu.16.04-x64-corert','ubuntu.16.10-corert','ubuntu.16.10-x64-corert','linuxmint.17-corert','linuxmint.17-x64-corert','linuxmint.17.1-corert','linuxmint.17.1-x64-corert','linuxmint.17.2-corert','linuxmint.17.2-x64-corert','linuxmint.17.3-corert','linuxmint.17.3-x64-corert','linuxmint.18-corert','linuxmint.18-x64-corert','fedora-corert','fedora-x64-corert','fedora.23-corert','fedora.23-x64-corert','fedora.24-corert','fedora.24-x64-corert','opensuse-corert','opensuse-x64-corert','opensuse.13.2-corert','opensuse.13.2-x64-corert','opensuse.42.1-corert','opensuse.42.1-x64-corert']`

**Compatible runtimes:**
```
 [DependencyContextAssemblyCache..ctor] Compatible runtimes: ['debian.9-x64','']
 ```

**Exception**:
 ```
  System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.
```

The [ASP.NET Core 2.0.4 SDK images](https://hub.docker.com/r/microsoft/aspnetcore-build/) are based on Debian Stretch (hence `debian.9-x64`, which is
not in the runtime graph obtained by `xunit`.

Note that `unix` is also missing from the runtime graph generated on that image.

Running the code in the same container but directly through the `dotnet` host (outside of `xunit` runner), successfully loads `System.Data.SqlClient` with no exceptions.

**Comment by vassilvk** [comment]
For those trying to use `System.Data.SqlClient` in `xunit` tests running in a .NET 2.0.4 Docker image and getting this exception -- I found out that switching from the `latest` (`stretch`-based) image to the `jessie`-based image of the same version, solves the problem as `xunit` finds a compatible runtime there.

For example, running the same test in a `microsoft/dotnet:2.0.4-runtime-jessie`-based container passes with no issues.

I still think that `xunit` assembly resolution and runtime fallback strategy should match that of corehost, otherwise there is the potential of lots of false positives moving forward.

**Comment by bradwilson** [comment]
Verified with `2.4.0-beta1-build3894` and macOS 10.13.

```
Runtime graph: ['osx-x64','osx','osx.10.10','osx.10.10-x64','osx.10.11','osx.10.11-x64','osx.10.12','osx.10.12-x64','osx-corert','osx-x64-corert','osx.10.10-corert','osx.10.10-x64-corert','osx.10.11-corert','osx.10.11-x64-corert','osx.10.12-corert','osx.10.12-x64-corert']
Could not find runtime 'osx.10.13-x64', falling back to 'osx.10.12-x64'
Compatible runtimes: ['osx.10.12-x64','osx.10.12','osx.10.11-x64','osx.10.11','osx.10.10-x64','osx.10.10','osx-x64','osx','unix-x64','unix','any','base','']
```

**Comment by bradwilson** [comment]
Verified with Debian Stretch:

```
Runtime graph: ['linux-arm','linux-x64','tizen.4.0.0-armel','linux','linux-x86','linux-armel','linux-arm64','rhel','rhel-x64','rhel.7','rhel.7-x64','rhel.7.0','rhel.7.0-x64','rhel.7.1','rhel.7.1-x64','rhel.7.2','rhel.7.2-x64','rhel.7.3','rhel.7.3-x64','rhel.7.4','rhel.7.4-x64','ol','ol-x64','ol.7','ol.7-x64','ol.7.0','ol.7.0-x64','ol.7.1','ol.7.1-x64','ol.7.2','ol.7.2-x64','centos','centos-x64','centos.7','centos.7-x64','debian','debian-x64','debian-x86','debian-arm','debian-armel','debian-arm64','debian.8','debian.8-x64','debian.8-x86','debian.8-arm','debian.8-armel','debian.8-arm64','tizen','tizen-armel','ubuntu','ubuntu-x64','ubuntu-x86','ubuntu-arm','ubuntu-arm64','ubuntu.14.04','ubuntu.14.04-x64','ubuntu.14.04-x86','ubuntu.14.04-arm','ubuntu.14.10','ubuntu.14.10-x64','ubuntu.14.10-x86','ubuntu.14.10-arm','ubuntu.15.04','ubuntu.15.04-x64','ubuntu.15.04-x86','ubuntu.15.04-arm','ubuntu.15.10','ubuntu.15.10-x64','ubuntu.15.10-x86','ubuntu.15.10-arm','ubuntu.16.04','ubuntu.16.04-x64','ubuntu.16.04-x86','ubuntu.16.04-arm','ubuntu.16.04-arm64','ubuntu.16.10','ubuntu.16.10-x64','ubuntu.16.10-x86','ubuntu.16.10-arm','ubuntu.16.10-arm64','linuxmint.17','linuxmint.17-x64','linuxmint.17.1','linuxmint.17.1-x64','linuxmint.17.2','linuxmint.17.2-x64','linuxmint.17.3','linuxmint.17.3-x64','linuxmint.18','linuxmint.18-x64','linuxmint.18.1','linuxmint.18.1-x64','fedora','fedora-x64','fedora.23','fedora.23-x64','fedora.24','fedora.24-x64','fedora.25','fedora.25-x64','fedora.26','fedora.26-x64','opensuse','opensuse-x64','opensuse.13.2','opensuse.13.2-x64','opensuse.42.1','opensuse.42.1-x64','linux-corert','linux-x64-corert','linux-arm-corert','linux-arm64-corert','rhel-corert','rhel-x64-corert','rhel.7-corert','rhel.7-x64-corert','rhel.7.0-corert','rhel.7.0-x64-corert','rhel.7.1-corert','rhel.7.1-x64-corert','rhel.7.2-corert','rhel.7.2-x64-corert','ol-corert','ol-x64-corert','ol.7-corert','ol.7-x64-corert','ol.7.0-corert','ol.7.0-x64-corert','ol.7.1-corert','ol.7.1-x64-corert','centos-corert','centos-x64-corert','centos.7-corert','centos.7-x64-corert','debian-corert','debian-x64-corert','debian-arm-corert','debian-arm64-corert','debian.8-corert','debian.8-x64-corert','debian.8-arm-corert','debian.8-arm64-corert','ubuntu-corert','ubuntu-x64-corert','ubuntu.14.04-corert','ubuntu.14.04-x64-corert','ubuntu.14.10-corert','ubuntu.14.10-x64-corert','ubuntu.15.04-corert','ubuntu.15.04-x64-corert','ubuntu.15.10-corert','ubuntu.15.10-x64-corert','ubuntu.16.04-corert','ubuntu.16.04-x64-corert','ubuntu.16.10-corert','ubuntu.16.10-x64-corert','linuxmint.17-corert','linuxmint.17-x64-corert','linuxmint.17.1-corert','linuxmint.17.1-x64-corert','linuxmint.17.2-corert','linuxmint.17.2-x64-corert','linuxmint.17.3-corert','linuxmint.17.3-x64-corert','linuxmint.18-corert','linuxmint.18-x64-corert','fedora-corert','fedora-x64-corert','fedora.23-corert','fedora.23-x64-corert','fedora.24-corert','fedora.24-x64-corert','opensuse-corert','opensuse-x64-corert','opensuse.13.2-corert','opensuse.13.2-x64-corert','opensuse.42.1-corert','opensuse.42.1-x64-corert']
Could not find runtime 'debian.9-x64', falling back to 'linux-x64'
Compatible runtimes: ['linux-x64','linux','unix-x64','unix','any','base','']
```

**Comment by bradwilson** [comment]
Verified with Ubuntu 17.10:

```
Runtime graph: ['linux-arm','linux-x64','tizen.4.0.0-armel','linux','linux-x86','linux-armel','linux-arm64','rhel','rhel-x64','rhel.7','rhel.7-x64','rhel.7.0','rhel.7.0-x64','rhel.7.1','rhel.7.1-x64','rhel.7.2','rhel.7.2-x64','rhel.7.3','rhel.7.3-x64','rhel.7.4','rhel.7.4-x64','ol','ol-x64','ol.7','ol.7-x64','ol.7.0','ol.7.0-x64','ol.7.1','ol.7.1-x64','ol.7.2','ol.7.2-x64','centos','centos-x64','centos.7','centos.7-x64','debian','debian-x64','debian-x86','debian-arm','debian-armel','debian-arm64','debian.8','debian.8-x64','debian.8-x86','debian.8-arm','debian.8-armel','debian.8-arm64','tizen','tizen-armel','ubuntu','ubuntu-x64','ubuntu-x86','ubuntu-arm','ubuntu-arm64','ubuntu.14.04','ubuntu.14.04-x64','ubuntu.14.04-x86','ubuntu.14.04-arm','ubuntu.14.10','ubuntu.14.10-x64','ubuntu.14.10-x86','ubuntu.14.10-arm','ubuntu.15.04','ubuntu.15.04-x64','ubuntu.15.04-x86','ubuntu.15.04-arm','ubuntu.15.10','ubuntu.15.10-x64','ubuntu.15.10-x86','ubuntu.15.10-arm','ubuntu.16.04','ubuntu.16.04-x64','ubuntu.16.04-x86','ubuntu.16.04-arm','ubuntu.16.04-arm64','ubuntu.16.10','ubuntu.16.10-x64','ubuntu.16.10-x86','ubuntu.16.10-arm','ubuntu.16.10-arm64','linuxmint.17','linuxmint.17-x64','linuxmint.17.1','linuxmint.17.1-x64','linuxmint.17.2','linuxmint.17.2-x64','linuxmint.17.3','linuxmint.17.3-x64','linuxmint.18','linuxmint.18-x64','linuxmint.18.1','linuxmint.18.1-x64','fedora','fedora-x64','fedora.23','fedora.23-x64','fedora.24','fedora.24-x64','fedora.25','fedora.25-x64','fedora.26','fedora.26-x64','opensuse','opensuse-x64','opensuse.13.2','opensuse.13.2-x64','opensuse.42.1','opensuse.42.1-x64','linux-corert','linux-x64-corert','linux-arm-corert','linux-arm64-corert','rhel-corert','rhel-x64-corert','rhel.7-corert','rhel.7-x64-corert','rhel.7.0-corert','rhel.7.0-x64-corert','rhel.7.1-corert','rhel.7.1-x64-corert','rhel.7.2-corert','rhel.7.2-x64-corert','ol-corert','ol-x64-corert','ol.7-corert','ol.7-x64-corert','ol.7.0-corert','ol.7.0-x64-corert','ol.7.1-corert','ol.7.1-x64-corert','centos-corert','centos-x64-corert','centos.7-corert','centos.7-x64-corert','debian-corert','debian-x64-corert','debian-arm-corert','debian-arm64-corert','debian.8-corert','debian.8-x64-corert','debian.8-arm-corert','debian.8-arm64-corert','ubuntu-corert','ubuntu-x64-corert','ubuntu.14.04-corert','ubuntu.14.04-x64-corert','ubuntu.14.10-corert','ubuntu.14.10-x64-corert','ubuntu.15.04-corert','ubuntu.15.04-x64-corert','ubuntu.15.10-corert','ubuntu.15.10-x64-corert','ubuntu.16.04-corert','ubuntu.16.04-x64-corert','ubuntu.16.10-corert','ubuntu.16.10-x64-corert','linuxmint.17-corert','linuxmint.17-x64-corert','linuxmint.17.1-corert','linuxmint.17.1-x64-corert','linuxmint.17.2-corert','linuxmint.17.2-x64-corert','linuxmint.17.3-corert','linuxmint.17.3-x64-corert','linuxmint.18-corert','linuxmint.18-x64-corert','fedora-corert','fedora-x64-corert','fedora.23-corert','fedora.23-x64-corert','fedora.24-corert','fedora.24-x64-corert','opensuse-corert','opensuse-x64-corert','opensuse.13.2-corert','opensuse.13.2-x64-corert','opensuse.42.1-corert','opensuse.42.1-x64-corert']
Could not find runtime 'ubuntu.17.10-x64', falling back to 'linux-x64'
Compatible runtimes: ['linux-x64','linux','unix-x64','unix','any','base','']
```
