### ISSUE TITLE
Tests run on dotnet test but not on dotnet xunit similar to #1509

### ISSUE THREAD

**Issue by nismolo** [xunit/xunit#1595]
We are having an issue similar to #1509. We were using version 2.3.1 and also tried by updating to 2.4.0-beta1-build3894. 

X unit cannot find the dll for System.Text.Encoding.CodePages please note that mimekit is depended on 4.3.0 however for some reason an exception is thrown because version 4.0.2 is not found when running tests using xunit.

```
System.TypeInitializationException : The type initializer for 'MimeKit.ParserOptions' threw an exception.
                                                ---> System.TypeInitializationException : The type initializer for 'MimeKit.Utils.CharsetUtils' threw an exception.
                                                        ---> System.IO.FileNotFoundException : Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                                                                ---> System.IO.FileNotFoundException : Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
                                        at MailKit.Net.Imap.ImapEngine.<ParseMessageAsync>d__190.MoveNext() in C:\Git\Third Party\MailKit\MailKit\Net\Imap\ImapEngine.cs:line 2527
                                        --- End of stack trace from previous location where exception was thrown ---
                                        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by bradwilson** [comment]
Please re-open this issue with a repro project. Reproj projects are required when reporting issues.

**Comment by nismolo** [comment]
Hi as requested please find the repo to reproduce the above issue.

https://github.com/nismolo/xunit-issue
