### ISSUE TITLE
Cannot convert InlineData attribute to nullable decimal

### ISSUE THREAD

**Issue by hinho** [xunit/xunit#1616]
There is a problem with conversion of InlineData attribute if test method attribute type is nullable decimal. If I use nullable double, everything works fine. 

Simple example:
`
public class UnitTest1
    {

        [Theory]
        [InlineData(0, 0, null)]   //ok
        [InlineData(2, 5, 0)]       //fail
        public void TestMethod1(decimal a, decimal b, decimal? expectedResult)
        {
            Assert.True(Calculate(a, b) == expectedResult);
        }

        [Theory]
        [InlineData(0, 0, null)]    //ok
        [InlineData(2, 5, 0)]       //ok
        public void TestMethod2(decimal a, decimal b, double? expectedResult)
        {
            decimal? e = null;

            if (expectedResult.HasValue)
            {
                e = (decimal?)expectedResult;
            }

            Assert.True(Calculate(a, b) == e);
        }

        public decimal? Calculate(decimal a, decimal b)
        {
            if (a != 0 || b != 0)
            {
                return System.Math.Max(a - b, 0);
            }
            else
            {
                return null;
            }
        }
    }
`

**Comment by bradwilson** [comment]
Did you try using a decimal value, namely: `[InlineData(2, 5, 0m)]`?

**Comment by bradwilson** [comment]
The issue is that there's no conversion from int to nullable decimal built into C#, and you can't use a decimal with `InlineData` because of C# language rules.

- You could try a string: `[InlineData(2, 5, "0")]`
- You could use `MemberData` instead of `InlineData` and return a real decimal value

**Comment by hinho** [comment]
Hello bradwilson,

Thank you for quick response. I am not sure if C# has no conversion from int to nullable decimal, because I can do this with no problem:

`
decimal? x = null; 
int y = 3; 
x = y;
`

If I try string, it says: `The value is not convertible to the method parameter 'expectedResult' of type 'decimal?'.`

**Comment by bradwilson** [comment]
There is a difference between what can be done by the compiler and what can be done at runtime. The compiler has its own set of rules that are separate from the runtime conversions.

Here is the code which is equivalent to what's being done at runtime:

```csharp
using System;
using System.Reflection;

public class Program
{
    public static void Main()
    {
        var methodInfo = typeof(Program).GetMethod("Method", BindingFlags.Public | BindingFlags.Static);
        var args = new object[] { 123 };
        methodInfo.Invoke(null, args);
    }

    public static void Method(decimal? value)
    {
        Console.WriteLine(value);
    }
}
```

And here is the result of running that code:

```
Unhandled Exception: System.ArgumentException: Object of type 'System.Int32' cannot be converted to type 'System.Nullable`1[System.Decimal]'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Program.Main() in Program.cs:line 11
```
