### ISSUE TITLE
ExceptionAndOutputCaptureCommand uses StringBuilder, that isn't thread safe, as StdOut

### ISSUE THREAD

**Issue by HCanber** [xunit/xunit#164]
This is the same error in #113. It occurs in 1.9.2

I have tests that occasionally throws this exception:
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: chunkLength
   at System.Text.StringBuilder.ToString()
   at Xunit.Sdk.ExceptionAndOutputCaptureCommand.Execute(Object testClass)
   at Xunit.Sdk.TimedCommand.Execute(Object testClass)
   at Xunit.Sdk.TestClassCommandRunner.Execute(ITestClassCommand testClassCommand, List`1 methods, Predicate`1 startCallback, Predicate`1 resultCallback)
   at Xunit.Sdk.Executor.ThreadRunner(Object threadStart)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```
It's very hard to reproduce it in a small example, but I think I've narrowed it down to the following:

1. Thread 1: `ExceptionAndOutputCaptureCommand` creates a StringWriter, which uses a StringBuilder internally.
1. Thread 1: `ExceptionAndOutputCaptureCommand` changes stdout to the StringWriter: `Console.SetOut(outputWriter)`.
1. Thread 1: The test is run. The test creates Thread 2.
1. Thread 1: The test succeeds and execution is returned to `ExceptionAndOutputCaptureCommand`.
1. Thread 2: Starts to call `Console.Write`. It gets the TextWriter to write to. It gets the StringWriter created earlier. 
1. Thread 1: `ExceptionAndOutputCaptureCommand` changes stdout back to the original TextWriter. `Console.SetOut(oldOut)`
1. This happens in parallell:
  - Thread 1: `StringWriter.ToString()` is called which delegates to the internal StringBuilder.
  - Thread 2: uses the same StringWriter and writes to it, i.e. uses the StringBuilder.

According to this StackOverflow question
http://stackoverflow.com/questions/12645351/stringbuilder-tostring-throw-an-index-out-of-range-exception
StringBuilder isn't thread safe and that we should use locks when accessing it.

So I tried using this as a writer instead, and my tests haven't failed after that.

``` C#
internal class SafeStringWriter : StringWriter
{
    private readonly object _lock = new object();

    public override void Write(char value)
    {
        lock(_lock)
        {
            base.Write(value);
        }
    }

    public override void Write(char[] buffer, int index, int count)
    {
        lock(_lock)
        {
            base.Write(buffer, index, count);
        }
    }

    public override void Write(string value)
    {
        lock(_lock)
        {
            base.Write(value);
        }
    }

    public override string ToString()
    {
        lock(_lock)
        {
            return base.ToString();
        }
    }
}
```

A PR is on it's way...

**Comment by bradwilson** [comment]
We are not going to fix the 1.x codebase, since 2.x is imminent.
