### ISSUE TITLE
Using Traits with null or empty value parameter hangs Visual Studio test discovery

### ISSUE THREAD

**Issue by ntcolonel** [xunit/xunit#1644]
The Traits in my project use only the key parameter of the Trait and leave the value portion as an empty string.

I was originally using xunit.runner.visualstudio 2.3.1 with xunit 2.2.0 under Visual Studio 2017 (15.5.5). The project is a "Windows Classic Desktop" Class Library project. I did not check this in a .NET Core class library project.

Once I brought xunit up to 2.3.1 (still using the 2.3.1 Visual Studio runner), I started seeing the test discovery process hang in Studio. The tests are never listed and rebuilding the affected project is unsuccessful, with vstest.console.exe holding a filesystem lock on the assembly with the affected tests. This does not happen if I put some kind of data into the value parameter of the TraitAttribute.

Please see the class below as an example of what will hang test discovery in Studio.
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;

namespace XUnit_Traits
{
    // [Trait("Will not hang Test Discovery", " ")]
    // [Trait("Will also hang Test Discovery", null)]
    [Trait("Hang Test Discovery", "")]
    public class Class1
    {
        [Fact]
        public void AwwYea()
        {
            Assert.True(true);
        }
    }
}
```

I ran the affected assembly through vstest.console.exe on the command line and got the following output:

```Microsoft (R) Test Execution Command Line Tool Version 15.5.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.3526781]   Discovering: XUnit-Traits
[xUnit.net 00:00:00.4351980] Exception discovering tests from XUnit-Traits: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Xunit.TestCaseDescriptor..ctor(String descriptorText)
   at Xunit.Xunit2Discoverer.<>c.<GetTestCaseDescriptors>b__33_0(String x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Xunit.Xunit2Discoverer.GetTestCaseDescriptors(List`1 testCases, Boolean includeSerialization)
   at Xunit.XunitFrontController.GetTestCaseDescriptors(List`1 testCases, Boolean includeSerialization)
   at Xunit.Runner.VisualStudio.VsTestRunner.GetVsTestCases(String source, ITestFrameworkDiscoverer discoverer, VsExecutionDiscoverySink visitor, LoggerHelper logger, TestPlatformContext testPlatformContext)
   at Xunit.Runner.VisualStudio.VsTestRunner.<>c__DisplayClass17_1.<RunTestsInAssembly>b__2(String source, ITestFrameworkDiscoverer discoverer, ITestFrameworkDiscoveryOptions discoveryOptions, VsExecutionDiscoverySink visitor)
   at Xunit.Runner.VisualStudio.VsTestRunner.DiscoverTestsInSource[TVisitor](XunitFrontController framework, LoggerHelper logger, TestPlatformContext testPlatformContext, Func`4 visitorFactory, Action`4 visitComplete, String assemblyFileName, Boolean shadowCopy, TestAssemblyConfiguration configuration)
No test is available in C:\Repos\XUnit-Traits\XUnit-Traits\bin\Debug\XUnit-Traits.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

I also ran the affected assembly through the native xunit console runner, and the test executed normally.

I noticed someone else got Studio to hang during test discovery [#1586](https://github.com/xunit/xunit/issues/1586). The cause of the hang (error during discovery) may end up being the same.

**Comment by bradwilson** [comment]
Dup of #1591, which is already fixed in 2.4 beta 1.

**Comment by tate4490** [comment]
Y'all say this is fixed but I am experiencing the same issue today.

**Comment by tate4490** [comment]
You say this issue is fixed but I am still experiencing it.  I had to roll back to build 2.2.0 to get my tests to run.  They discover fine, just will not run.

**Comment by tate4490** [comment]
You say this issue is fixed but I am still experiencing it. I had to roll back to build 2.2.0 to get my tests to run. They discover fine, just will not run.

**Comment by bradwilson** [comment]
If you have a repro against 2.4 beta 1, please open a new issue with that repro. Thanks!
