### ISSUE TITLE
Wrong default DigestMethod of System.Security.Cryptography.Xml.Reference on net471

### ISSUE THREAD

**Issue by chuuddo** [xunit/xunit#1664]
Starting with the .NET Framework 4.7.1 SHA256 is enabled by default for some APIs. More info at https://github.com/Microsoft/dotnet/blob/master/Documentation/compatibility/Change-SignedXML-and-SignedCMS-default-algorithms-to-SHA256.md

Tests of DigestMethod of System.Security.Cryptography.Xml.Reference fails on net471 using xUnit, but passed using NUnit.

All code can be found at https://github.com/chuuddo/DigestMethodTest

This is log from AppVeyor of https://github.com/chuuddo/DigestMethodTest/blob/master/run.cmd

```[00:00:00] Build started
[00:00:00] git clone -q --branch=master https://github.com/chuuddo/DigestMethodTest.git C:\projects\digestmethodtest
[00:00:01] git checkout -qf e0595e9e2d76301ad87be61c1dacde89c5d60bd7
[00:00:01] run
[00:00:02] .NET Command Line Tools (2.1.100)
[00:00:02] 
[00:00:02] Product Information:
[00:00:02]  Version:            2.1.100
[00:00:02]  Commit SHA-1 hash:  b9e74c6520
[00:00:02] 
[00:00:02] Runtime Environment:
[00:00:02]  OS Name:     Windows
[00:00:02]  OS Version:  10.0.14393
[00:00:02]  OS Platform: Windows
[00:00:02]  RID:         win10-x64
[00:00:02]  Base Path:   C:\Program Files\dotnet\sdk\2.1.100\
[00:00:02] 
[00:00:02] Microsoft .NET Core Shared Framework Host
[00:00:02] 
[00:00:02]   Version  : 2.0.5
[00:00:02]   Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
[00:00:02] 
[00:00:02] Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
[00:00:02] Copyright (C) Microsoft Corporation. All rights reserved.
[00:00:02] 
[00:00:07]   Restoring packages for C:\projects\digestmethodtest\DigestMethodTest\DigestMethodTest.csproj...
[00:00:07]   Restoring packages for C:\projects\digestmethodtest\NUnitTests\NUnitTests.csproj...
[00:00:07]   Generating MSBuild file C:\projects\digestmethodtest\DigestMethodTest\obj\DigestMethodTest.csproj.nuget.g.props.
[00:00:07]   Generating MSBuild file C:\projects\digestmethodtest\DigestMethodTest\obj\DigestMethodTest.csproj.nuget.g.targets.
[00:00:07]   Restore completed in 103.83 ms for C:\projects\digestmethodtest\DigestMethodTest\DigestMethodTest.csproj.
[00:00:07]   Restoring packages for C:\projects\digestmethodtest\xUnitTests\xUnitTests.csproj...
[00:00:07]   Installing Microsoft.CodeCoverage 1.0.3.
[00:00:07]   Installing NUnit 3.10.1.
[00:00:07]   Installing NUnit3TestAdapter 3.10.0.
[00:00:07]   Installing Microsoft.NET.Test.Sdk 15.6.1.
[00:00:07]   Installing xunit.abstractions 2.0.1.
[00:00:07]   Installing xunit.extensibility.core 2.4.0-beta.1.build3958.
[00:00:07]   Installing xunit.extensibility.execution 2.4.0-beta.1.build3958.
[00:00:07]   Installing xunit.core 2.4.0-beta.1.build3958.
[00:00:07]   Installing xunit.analyzers 0.8.0.
[00:00:07]   Installing xunit.assert 2.4.0-beta.1.build3958.
[00:00:07]   Installing xunit 2.4.0-beta.1.build3958.
[00:00:07]   Installing xunit.runner.visualstudio 2.4.0-beta.1.build3958.
[00:00:08]   Generating MSBuild file C:\projects\digestmethodtest\xUnitTests\obj\xUnitTests.csproj.nuget.g.props.
[00:00:08]   Generating MSBuild file C:\projects\digestmethodtest\xUnitTests\obj\xUnitTests.csproj.nuget.g.targets.
[00:00:08]   Restore completed in 766.33 ms for C:\projects\digestmethodtest\xUnitTests\xUnitTests.csproj.
[00:00:08]   Restoring packages for C:\projects\digestmethodtest\xUnitTests\xUnitTests.csproj...
[00:00:08]   Generating MSBuild file C:\projects\digestmethodtest\NUnitTests\obj\NUnitTests.csproj.nuget.g.props.
[00:00:08]   Generating MSBuild file C:\projects\digestmethodtest\NUnitTests\obj\NUnitTests.csproj.nuget.g.targets.
[00:00:08]   Restore completed in 1.01 sec for C:\projects\digestmethodtest\NUnitTests\NUnitTests.csproj.
[00:00:12]   Installing Microsoft.NETCore.Jit 1.0.2.
[00:00:12]   Installing Microsoft.NETCore.Runtime.CoreCLR 1.0.2.
[00:00:12]   Installing Microsoft.NETCore.DotNetHostPolicy 1.0.1.
[00:00:12]   Installing Microsoft.NETCore.App 1.0.0.
[00:00:12]   Installing dotnet-xunit 2.4.0-beta.1.build3958.
[00:00:15]   Restore completed in 7.88 sec for C:\projects\digestmethodtest\xUnitTests\xUnitTests.csproj.
[00:00:17]   DigestMethodTest -> C:\projects\digestmethodtest\DigestMethodTest\bin\Release\net471\DigestMethodTest.exe
[00:00:18]   DigestMethodTest -> C:\projects\digestmethodtest\DigestMethodTest\bin\Release\net452\DigestMethodTest.exe
[00:00:20]   NUnitTests -> C:\projects\digestmethodtest\NUnitTests\bin\Release\net471\NUnitTests.dll
[00:00:20]   xUnitTests -> C:\projects\digestmethodtest\xUnitTests\bin\Release\net471\xUnitTests.dll
[00:00:20]   xUnitTests -> C:\projects\digestmethodtest\xUnitTests\bin\Release\net452\xUnitTests.dll
[00:00:20]   NUnitTests -> C:\projects\digestmethodtest\NUnitTests\bin\Release\net452\NUnitTests.dll
[00:00:20] 
[00:00:20] Build succeeded.
[00:00:20]     0 Warning(s)
[00:00:20]     0 Error(s)
[00:00:20] 
[00:00:20] Time Elapsed 00:00:17.91
[00:00:20] 
[00:00:20] On net452 XmlReference.GetDigestMethod() returns http://www.w3.org/2000/09/xmldsig#sha1
[00:00:20] On net471 XmlReference.GetDigestMethod() returns http://www.w3.org/2001/04/xmlenc#sha256
[00:00:20] 
[00:00:20] ==== NUnit TESTS ====
[00:00:20] 
[00:00:21] Test run for C:\projects\digestmethodtest\NUnitTests\bin\Release\net452\NUnitTests.dll(.NETFramework,Version=v4.5.2)
[00:00:21] Microsoft (R) Test Execution Command Line Tool Version 15.6.0-preview-20180109-01
[00:00:21] Copyright (c) Microsoft Corporation.  All rights reserved.
[00:00:21] 
[00:00:22] Starting test execution, please wait...
[00:00:24] NUnit Adapter 3.10.0.21: Test execution started
[00:00:24] Running all tests in C:\projects\digestmethodtest\NUnitTests\bin\Release\net452\NUnitTests.dll
[00:00:24] NUnit3TestExecutor converted 1 of 1 NUnit test cases
[00:00:24] NUnit Adapter 3.10.0.21: Test execution complete
[00:00:24] 
[00:00:24] Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
[00:00:24] Test Run Successful.
[00:00:24] Test execution time: 2.8256 Seconds
[00:00:24] Test run for C:\projects\digestmethodtest\NUnitTests\bin\Release\net471\NUnitTests.dll(.NETFramework,Version=v4.7.1)
[00:00:24] Microsoft (R) Test Execution Command Line Tool Version 15.6.0-preview-20180109-01
[00:00:24] Copyright (c) Microsoft Corporation.  All rights reserved.
[00:00:24] 
[00:00:25] Starting test execution, please wait...
[00:00:25] NUnit Adapter 3.10.0.21: Test execution started
[00:00:25] Running all tests in C:\projects\digestmethodtest\NUnitTests\bin\Release\net471\NUnitTests.dll
[00:00:26] NUnit3TestExecutor converted 1 of 1 NUnit test cases
[00:00:26] NUnit Adapter 3.10.0.21: Test execution complete
[00:00:26] 
[00:00:26] Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
[00:00:26] Test Run Successful.
[00:00:26] Test execution time: 1.2824 Seconds
[00:00:26] 
[00:00:26] ==== xUnit TESTS ====
[00:00:26] 
[00:00:27] Test run for C:\projects\digestmethodtest\xUnitTests\bin\Release\net452\xUnitTests.dll(.NETFramework,Version=v4.5.2)
[00:00:27] Microsoft (R) Test Execution Command Line Tool Version 15.6.0-preview-20180109-01
[00:00:27] Copyright (c) Microsoft Corporation.  All rights reserved.
[00:00:27] 
[00:00:27] Starting test execution, please wait...
[00:00:28] [xUnit.net 00:00:00.0057794] xUnit.net VSTest Adapter v2.4.0-beta.1.build3958 (32-bit Desktop .NET 4.0.30319.42000)
[00:00:28] [xUnit.net 00:00:00.3514890]   Discovering: xUnitTests
[00:00:28] [xUnit.net 00:00:00.4526653]   Discovered:  xUnitTests
[00:00:28] [xUnit.net 00:00:00.4576798]   Starting:    xUnitTests
[00:00:30] [xUnit.net 00:00:02.2486811]   Finished:    xUnitTests
[00:00:30] 
[00:00:30] Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
[00:00:30] Test Run Successful.
[00:00:30] Test execution time: 3.0200 Seconds
[00:00:30] Test run for C:\projects\digestmethodtest\xUnitTests\bin\Release\net471\xUnitTests.dll(.NETFramework,Version=v4.7.1)
[00:00:30] Microsoft (R) Test Execution Command Line Tool Version 15.6.0-preview-20180109-01
[00:00:30] Copyright (c) Microsoft Corporation.  All rights reserved.
[00:00:30] 
[00:00:30] Starting test execution, please wait...
[00:00:31] [xUnit.net 00:00:00.0031812] xUnit.net VSTest Adapter v2.4.0-beta.1.build3958 (32-bit Desktop .NET 4.0.30319.42000)
[00:00:31] [xUnit.net 00:00:00.2554039]   Discovering: xUnitTests
[00:00:31] [xUnit.net 00:00:00.3287171]   Discovered:  xUnitTests
[00:00:31] [xUnit.net 00:00:00.3325955]   Starting:    xUnitTests
[00:00:31] [xUnit.net 00:00:00.6019957]     xUnitTests.XmlReferenceTests.GetDigestMethod [FAIL]
[00:00:31] [xUnit.net 00:00:00.6022757]       Assert.Equal() Failure
[00:00:31] [xUnit.net 00:00:00.6023195]                                         (pos 21)
[00:00:31] [xUnit.net 00:00:00.6023616]       Expected: ���ttp://www.w3.org/2001/04/xmlenc#sha256
[00:00:31] [xUnit.net 00:00:00.6023954]       Actual:   ���ttp://www.w3.org/2000/09/xmldsig#sha1
[00:00:31] [xUnit.net 00:00:00.6024279]                                         (pos 21)
[00:00:31] [xUnit.net 00:00:00.6030625]       Stack Trace:
[00:00:31] [xUnit.net 00:00:00.6065305]         XmlReferenceTests.cs(17,0): at xUnitTests.XmlReferenceTests.GetDigestMethod()
[00:00:31] [xUnit.net 00:00:00.6163788]   Finished:    xUnitTests
[00:00:32] Failed   xUnitTests.XmlReferenceTests.GetDigestMethod
[00:00:32] Error Message:
[00:00:32]  Assert.Equal() Failure
[00:00:32]                                   (pos 21)
[00:00:32] Expected: ���ttp://www.w3.org/2001/04/xmlenc#sha256
[00:00:32] Actual:   ���ttp://www.w3.org/2000/09/xmldsig#sha1
[00:00:32]                                   (pos 21)
[00:00:32] Stack Trace:
[00:00:32]    at xUnitTests.XmlReferenceTests.GetDigestMethod() in C:\projects\digestmethodtest\xUnitTests\XmlReferenceTests.cs:line 17
[00:00:32] 
[00:00:32] Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
[00:00:32] Test Run Failed.
[00:00:32] Test execution time: 1.4067 Seconds
[00:00:32] Command exited with code 1

**Comment by bradwilson** [comment]
The behavior changes will not be picked up by our console runner, since it's compiled against `net452`, not `net471`. Unfortunately this is by design. We do not want to set overrides that might cause other users to have issues (your "bug" is someone else's "feature", unfortunately).

**Comment by bradwilson** [comment]
Subsumed by #1709.
