### ISSUE TITLE
Unable to run tests in 2.4.0-beta.2 due to desktop_and_uap duplicate adapter error

### ISSUE THREAD

**Issue by NickCraver** [xunit/xunit#1665]
I'm trying to use 2.4 to workaround #1601, hitting some snags. 

Using: **2.4.0-beta.2.build3967** from MyGet
I've got a repro branch set aside here: https://github.com/StackExchange/StackExchange.Redis/tree/craver/xunit-2.4

When doing a Run All in VS, I get the following:
```
[3/13/2018 8:45:49 PM Informational] ------ Run test started ------
[3/13/2018 8:45:49 PM Informational] [xUnit.net 00:00:00.0046120] xUnit.net VSTest Adapter v2.4.0-beta.2.build3967 (64-bit .NET Core 4.6.26011.01)
[3/13/2018 8:45:50 PM Informational] [xUnit.net 00:00:00.6225301]   Discovering: NRediSearch.Test
[3/13/2018 8:45:50 PM Informational] [xUnit.net 00:00:00.6897760]   Discovered:  NRediSearch.Test
[3/13/2018 8:45:50 PM Informational] [xUnit.net 00:00:00.6961249]   Starting:    NRediSearch.Test
[3/13/2018 8:45:50 PM Informational] [xUnit.net 00:00:01.0338226]   Finished:    NRediSearch.Test
[3/13/2018 8:45:51 PM Warning] Multiple test adapters with the same uri 'executor://xunit/VsTestRunner2/desktop_and_uap' were found. Ignoring adapter 'Xunit.Runner.VisualStudio.VsTestRunner'. Please uninstall the conflicting adapter(s) to avoid this warning.
[3/13/2018 8:45:51 PM Informational] [xUnit.net 00:00:00.0033535] xUnit.net VSTest Adapter v2.4.0-beta.2.build3967 (32-bit Universal Windows)
[3/13/2018 8:45:51 PM Error] [xUnit.net 00:00:00.0396810] StackExchange.Redis.Tests: Catastrophic failure: System.InvalidOperationException: The process has no package identity. (Exception from HRESULT: 0x80073D54)
   at Windows.ApplicationModel.Package.get_Current()
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)
[3/13/2018 8:45:51 PM Warning] No test is available in C:\git\StackExchange\StackExchange.Redis\StackExchange.Redis.Tests\bin\Release\net462\StackExchange.Redis.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
[3/13/2018 8:45:51 PM Informational] ========== Run test finished: 1 run (0:00:02.3495768) ==========
```

We thought this was related to #1643, but it hasn't helped this issue unfortunately. /cc @onovotny

**Comment by bradwilson** [comment]
If we're not using desktop for UAP discovery, then they do need separate URIs. That probably also means that we need to ensure the UAP discoverer doesn't try to run when it's inside a desktop CLR process.

**Comment by bradwilson** [comment]
For the latter, I mean updating this: https://github.com/xunit/xunit/blob/94ae1736405f22b86d274245d11c54c22b7d680d/src/xunit.runner.visualstudio/Utility/RunSettings.cs#L107-L115

**Comment by NickCraver** [comment]
Just confirmed this fix works, thanks!
