### ISSUE TITLE
Theory methods with parameters of type "params byte[]" cause runtime error

### ISSUE THREAD

**Issue by jameswilddev** [xunit/xunit#1670]
On building the following, the test will appear in the Visual Studio Test Explorer:

```
using Xunit;

namespace Testing
{
    public sealed class TestingClass
    {
        [Theory]
        [InlineData(2, 3, 4)]
        public void TestingMethod(params byte[] abc)
        {
            Assert.Equal(3, abc.Length);
        }
    }
}
```

But on running that test, the following error appears in the console:
```
[15/03/2018 17:12:10 Warning] [xUnit.net 00:00:00.3658269] Exception discovering tests from Testing: System.InvalidCastException: At least one element in the source array could not be cast down to the destination array type.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at Xunit.Sdk.TypeUtility.ResolveMethodArguments(MethodBase testMethod, Object[] arguments)
   at Xunit.Sdk.TestMethodTestCase.Initialize()
   at Xunit.Sdk.XunitTestCase.Initialize()
   at Xunit.Sdk.TestMethodTestCase.get_UniqueID()
   at Xunit.Sdk.TestCaseDescriptorFactory..ctor(Object discovererObject, Object testCasesObject, Object callbackObject)   at Xunit.AppDomainManager_AppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args)
   at Xunit.Xunit2Discoverer.GetTestCaseDescriptors(List`1 testCases, Boolean includeSerialization)
   at Xunit.XunitFrontController.GetTestCaseDescriptors(List`1 testCases, Boolean includeSerialization)
   at Xunit.Runner.VisualStudio.VsTestRunner.GetVsTestCases(String source, ITestFrameworkDiscoverer discoverer, VsExecutionDiscoverySink visitor, LoggerHelper logger, TestPlatformContext testPlatformContext)
   at Xunit.Runner.VisualStudio.VsTestRunner.<>c__DisplayClass17_1.<RunTestsInAssembly>b__2(String source, ITestFrameworkDiscoverer discoverer, ITestFrameworkDiscoveryOptions discoveryOptions, VsExecutionDiscoverySink visitor)
   at Xunit.Runner.VisualStudio.VsTestRunner.DiscoverTestsInSource[TVisitor](XunitFrontController framework, LoggerHelper logger, TestPlatformContext testPlatformContext, Func`4 visitorFactory, Action`4 visitComplete, String assemblyFileName, Boolean shadowCopy, TestAssemblyConfiguration configuration)
```

Changing the parameter type to "params int[]" is a workaround for this, but requires a cast inside the test.

Thanks!

**Comment by bradwilson** [comment]
This has nothing to do with xUnit.net. `int`s cannot be cast down to `byte`s implicitly by the system. The error very clearly tells you what the problem is.

You have two choices:

- Provide the data as a `byte`s instead of `int`s
- Change the signature of the method from `byte[]` to `int[]`

**Comment by jameswilddev** [comment]
Alright, yeah that's my current workaround.

This confuses me a bit because I can see that in the past changes were made to support implicit conversion, i.e. https://github.com/xunit/xunit/pull/1020

**Comment by bradwilson** [comment]
We can only convert data when:

- The CLR has a built-in conversion
- You are converting to/from a custom type under your control, that can be converted from a type that's present in the data

AFAIK, there is no built-in conversion _**at the CLR level**_ for `int` -> `byte`. The _**compiler**_ may happily do it, but that's a different code path.
