### ISSUE TITLE
VsTestRunner Catastrophic error during deserialization

### ISSUE THREAD

**Issue by maldworth** [xunit/xunit#1688]
Reproduction with a simple asp.net core 2.0 project here: https://github.com/maldworth/xunit-vs-runner-failure

I'm using the [Microsoft.Aspnetcore.Testhost](https://www.nuget.org/packages/Microsoft.AspNetCore.TestHost/2.0.2)

I'm on Windows 10.

1. If you open the project in VS2017 and click "Run All Tests"  VS2017, it will pass with a green checkmark.
2. Then click Run All again. It will fail, spit out errors in the output see below.
3. If you completely close the solution and re-open, it will pass the first time, then again more errors every time after.

```
[2018-04-22 21:01:03 Informational] ------ Load Playlist started ------
[2018-04-22 21:01:03 Informational] ========== Load Playlist finished (0:00:00.0204966) ==========
[2018-04-22 21:01:09 Informational] ------ Run test started ------
[2018-04-22 21:01:09 Error] System.IO.FileNotFoundException: C:\Users\myusername\AppData\Local\Temp\VisualStudioTestExplorerExtensions\2.3.1/build/netcoreapp1.0/xunit.runner.visualstudio.dotnetcore.testadapter.dll
   at Microsoft.VisualStudio.TestWindow.Controller.TestPlatformProvider.PerformShadowCopy(IEnumerable`1 testExtensions)
[2018-04-22 21:01:11 Informational] [xUnit.net 00:00:00.8308613]   Discovering: Ocas.AppSettings.IntegrationTests
[2018-04-22 21:01:11 Informational] [xUnit.net 00:00:00.9469089]   Discovered:  Ocas.AppSettings.IntegrationTests
[2018-04-22 21:01:11 Informational] [xUnit.net 00:00:00.9603712]   Starting:    Ocas.AppSettings.IntegrationTests
[2018-04-22 21:01:12 Informational] [xUnit.net 00:00:01.7117927]   Finished:    Ocas.AppSettings.IntegrationTests
[2018-04-22 21:01:12 Informational] ========== Run test finished: 1 run (0:00:03.311023) ==========
[2018-04-22 21:01:19 Informational] ------ Run test started ------
[2018-04-22 21:01:20 Warning] [xUnit.net 00:00:00.8145871] Ocas.AppSettings.IntegrationTests: Catastrophic error during deserialization: System.ArgumentException: De-serialized string is in the incorrect format.
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 35
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 59
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 522
[2018-04-22 21:01:20 Informational] [xUnit.net 00:00:00.8665055]   Starting:    Ocas.AppSettings.IntegrationTests
[2018-04-22 21:01:20 Informational] [xUnit.net 00:00:00.9157204]   Finished:    Ocas.AppSettings.IntegrationTests
[2018-04-22 21:01:20 Informational] ========== Run test finished: 0 run (0:00:01.583838) ==========
[2018-04-22 21:02:44 Informational] ------ Run test started ------
[2018-04-22 21:02:46 Warning] [xUnit.net 00:00:00.8390631] Ocas.AppSettings.IntegrationTests: Catastrophic error during deserialization: System.ArgumentException: De-serialized string is in the incorrect format.
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 35
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 59
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 522
[2018-04-22 21:02:46 Informational] [xUnit.net 00:00:00.8651070]   Starting:    Ocas.AppSettings.IntegrationTests
[2018-04-22 21:02:46 Informational] [xUnit.net 00:00:00.9237653]   Finished:    Ocas.AppSettings.IntegrationTests
[2018-04-22 21:02:46 Informational] ========== Run test finished: 0 run (0:00:01.7282324) ==========
```

**Comment by hjkl950217** [comment]
tks!  I have the same problem with you，After delete cache and using two package，fix it
