### ISSUE TITLE
Fails to find/run tests when test lib targets x86

### ISSUE THREAD

**Issue by SimonCropp** [xunit/xunit#1691]
So when running tests on a project that targets netcoreapp2.0 and x86

```
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
```

### Repro 

https://github.com/SimonCropp/X86XunitRepro

As a side note I actually experienced this (ie the same failure) when pulling in an assembly reference that targeted x86. i assume u dont need a diff repro for that?

### Environment

 * VS 2017 15.6.7
 * resharper 2018.1 (although can also repo with VS test runner and `dotnet test`)
 * Windows server 2012 R2
 * TargetFramework: netcoreapp2.0

### Nugets

```
<PackageReference Include="xunit" Version="2.3.1" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.0" />
```

### R# test runner

"Inconclusive: Test not run"

![image](https://user-images.githubusercontent.com/122666/39462020-e29320e0-4d51-11e8-9dc5-58f85d0f0542.png)

### VS test runner

```
 XUnitWithX86: Catastrophic failure: System.TypeInitializationException: The type initializer for 'Xunit.DiaSession' threw an exception. ---> 
 System.IO.FileNotFoundException: Could not load file or assembly 'System.Reflection.TypeExtensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
 or one of its dependencies. The system cannot find the file specified.
   at Xunit.DiaSession..cctor()
   --- End of inner exception stack trace ---
   at Xunit.DiaSession..ctor(String assemblyFileName)
   at Xunit.DiaSessionWrapper..ctor(String assemblyFilename) 
   in \xunit.runner.utility\Utility\DiaSessionWrapper_DotNet.cs:line 16
   at Xunit.XunitFrontController..ctor(AppDomainSupport appDomainSupport, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticMessageSink) 
   in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 66
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) 
   in \xunit.runner.visualstudio\VsTestRunner.cs:line 455
[1/05/2018 3:11:44 PM Warning] No test is available in \X86XunitRepro\XUnitSimple\bin\Debug\netcoreapp2.0\XUnitSimple.dll \X86XunitRepro\XUnitWithX86\bin\Debug\netcoreapp2.0\XUnitWithX86.dll. 
Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
```

### dotnet test

```

Microsoft (R) Test Execution Command Line Tool Version 15.6.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.4736536]   Discovering: XUnitSimple
[xUnit.net 00:00:00.5407738]   Discovered:  XUnitSimple
[xUnit.net 00:00:00.5474468]   Starting:    XUnitSimple
[xUnit.net 00:00:00.7209919]   Finished:    XUnitSimple

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 1.6353 Seconds
Build completed.

Test run for C:\Code\X86XunitRepro\XUnitWithX86\bin\Debug\netcoreapp2.0\XUnitWithX86.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.6.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.4565304] Exception discovering tests from XUnitWithX86:
System.BadImageFormatException: Could not load file or assembly 'XUnitWithX86, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
An attempt was made to load a program with an incorrect format.
File name: 'XUnitWithX86, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Xunit.Sdk.ReflectionAssemblyInfo..ctor(String assemblyFileName) 
   in \xunit.execution\Sdk\Reflection\ReflectionAssemblyInfo.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Xunit.AppDomainManager_NoAppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args) 
   in \xunit.runner.utility\AppDomain\AppDomainManager_NoAppDomain.cs:line 31
   at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk) 
   in \src\xunit.runner.utility\Frameworks\v2\Xunit2Discoverer.cs:line 100
   at Xunit.Xunit2..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyTestAssemblyExists) in \xunit.runner.utility\Frameworks\v2\Xunit2.cs:line 45
   at Xunit.XunitFrontController.CreateInnerController() 
   in \xunit.runner.utility\Frameworks\XunitFrontController.cs:line 136
   at Xunit.XunitFrontController.EnsureInitialized() 
   in \xunit.runner.utility\Frameworks\XunitFrontController.cs:line 155
   at Xunit.Runner.VisualStudio.VsTestRunner.DiscoverTestsInSource[TVisitor](XunitFrontController framework, LoggerHelper logger, TestPlatformContext testPlatformContext, Func`4 visitorFactory, Action`4 visitComplete, String assemblyFileName, Boolean shadowCopy, TestAssemblyConfiguration configuration) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 253


No test is available in C:\Code\X86XunitRepro\XUnitWithX86\bin\Debug\netcoreapp2.0\XUnitWithX86.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.

Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

**Comment by bradwilson** [comment]
There are several issues here:

- For desktop CLR, you need to choose to use the .x86 variant of the console runner (or use `-x86` with `dotnet xunit`).

- For .NET Core, you need to run the 32-bit version of dotnet.exe (after installing the 32-bit .NET SDK). This is the one in `C:\Program Files (x86)` rather than `C:\Program Files`.

- For Visual Studio, I'm honestly not sure how you tell them to use 32-bit instead of 64-bit. I didn't see anything obvious in Tools > Options.

**Comment by bradwilson** [comment]
Also, Resharper issues are not directly supported here. You should ask JetBrains how to ask for 32-bit instead of 64-bit test execution.

**Comment by Jones-Adam** [comment]
in Visual Studio the selector is found under Test->Test Settings->Default Process Architecture
