### ISSUE TITLE
Catastrophic error during deserialization during tests execution in Visual Studio

### ISSUE THREAD

**Issue by Kolan92** [xunit/xunit#1702]
### Problem:

After execution of xunit tests in Visual Studio, test runner reports warnings: `Catastrophic error during deserialization`.

#### Expected Results:

No warnings in output.

### Environment

  * OS: Windows 10
  * .Net version: netcoreapp2.0
  * xunit version: 2.3.1
  * xunit.runner.visualstudio version: 2.3.1
  
#### Steps to reproduce:
Sample repository with code, that generates warnings in after tests execution: https://github.com/Kolan92/XunitWarnings

  1. Create test method with attributes `[Theory] [MemberData(nameof(ArgumentsGenerator))]`
where ArgumentsGenerator is some method which generates arguments.
  2. Run tests

Removing cache suggested in [issue 1688](https://github.com/xunit/xunit/issues/1688) didn't help.
  
#### Observed Results:

* Resharper runner:
 After second test run 2 warnings are shown in output:
```
2018.05.10 09:08:27.457    WARN [xUnit.net 00:00:00.6090710] XunitFail: Catastrophic error deserializing item #1: System.ArgumentException: An item with the same key has already been added. Key: 6456c4c6ac0e91a2a0a316cc9fb766008ea3ebf8
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)
2018.05.10 09:08:27.897    WARN dotnet exited with exit code (1)
Output stream: Microsoft (R) Test Execution Command Line Tool Version 15.6.0
Copyright (c) Microsoft Corporation.  All rights reserved.

[xUnit.net 00:00:00.6592076]   Starting:    XunitFail
[xUnit.net 00:00:00.8459700]   Finished:    XunitFail

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test execution time: 1,6660 Seconds
Error stream: [xUnit.net 00:00:00.6090710] XunitFail: Catastrophic error deserializing item #1: System.ArgumentException: An item with the same key has already been added. Key: 6456c4c6ac0e91a2a0a316cc9fb766008ea3ebf8
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo)
Test Run Failed.
```

* Visual Studio Runner:
After first test run warnings are shown in output:
```
[10.05.2018 08:39:53 Informational] ------ Load Playlist started ------
[10.05.2018 08:39:53 Informational] ========== Load Playlist finished (0:00:00,0630023) ==========
[10.05.2018 08:51:46 Informational] ------ Run test started ------
[10.05.2018 08:51:49 Informational] [xUnit.net 00:00:00.5356519]   Discovering: XunitFail
[10.05.2018 08:51:49 Informational] [xUnit.net 00:00:00.6624280]   Discovered:  XunitFail
[10.05.2018 08:51:49 Informational] [xUnit.net 00:00:00.6685101]   Starting:    XunitFail
[10.05.2018 08:51:49 Informational] [xUnit.net 00:00:00.8422252]   Finished:    XunitFail
[10.05.2018 08:51:50 Informational] ========== Run test finished: 1 run (0:00:04,0214987) ==========
[10.05.2018 08:52:12 Informational] ------ Run test started ------
[10.05.2018 08:52:13 Warning] [xUnit.net 00:00:00.5440610] XunitFail: Catastrophic error during deserialization: System.ArgumentException: De-serialized string is in the incorrect format.
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 35
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 59
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 522
[10.05.2018 08:52:13 Informational] [xUnit.net 00:00:00.5935943]   Starting:    XunitFail
[10.05.2018 08:52:13 Informational] [xUnit.net 00:00:00.6481298]   Finished:    XunitFail
[10.05.2018 08:52:13 Informational] ========== Run test finished: 0 run (0:00:01,390991) ==========
[10.05.2018 08:52:28 Informational] ------ Run test started ------
[10.05.2018 08:52:29 Warning] [xUnit.net 00:00:00.5145153] XunitFail: Catastrophic error during deserialization: System.ArgumentException: De-serialized string is in the incorrect format.
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 35
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 59
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 522
[10.05.2018 08:52:29 Informational] [xUnit.net 00:00:00.5591585]   Starting:    XunitFail
[10.05.2018 08:52:29 Informational] [xUnit.net 00:00:00.6049972]   Finished:    XunitFail
[10.05.2018 08:52:29 Informational] ========== Run test finished: 0 run (0:00:01,288014) ==========
[10.05.2018 09:02:34 Informational] ------ Run test started ------
[10.05.2018 09:02:36 Informational] [xUnit.net 00:00:00.5732317]   Discovering: XunitFail
[10.05.2018 09:02:36 Informational] [xUnit.net 00:00:00.7002337]   Discovered:  XunitFail
[10.05.2018 09:02:36 Informational] [xUnit.net 00:00:00.7081062]   Starting:    XunitFail
[10.05.2018 09:02:36 Informational] [xUnit.net 00:00:00.8903516]   Finished:    XunitFail
[10.05.2018 09:02:36 Informational] ========== Run test finished: 1 run (0:00:01,6175086) ==========
[10.05.2018 09:13:50 Informational] ------ Run test started ------
[10.05.2018 09:13:51 Warning] [xUnit.net 00:00:00.5361458] XunitFail: Catastrophic error during deserialization: System.ArgumentException: De-serialized string is in the incorrect format.
   at Xunit.Sdk.SerializationHelper.Deserialize[T](String serializedValue) in C:\Dev\xunit\xunit\src\common\SerializationHelper.cs:line 35
   at Xunit.Sdk.XunitTestFrameworkExecutor.Deserialize(String value) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 59
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, IMessageSinkWithTypes reporterMessageHandler, AssemblyRunInfo runInfo) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 522
[10.05.2018 09:13:51 Informational] [xUnit.net 00:00:00.5831523]   Starting:    XunitFail
[10.05.2018 09:13:51 Informational] [xUnit.net 00:00:00.6332928]   Finished:    XunitFail
[10.05.2018 09:13:52 Informational] ========== Run test finished: 0 run (0:00:01,3875091) ==========
```

* Console
Command `dotnet test 2> error.txt`
Error.txt is empty. 

#### Notes
This problem make build fail in VSTS in step Visual Studio Test.
```
Vstest failed with error. Check logs for failures. There might be failed tests.
Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1
```

But all tests are finished without problem.

**Comment by bradwilson** [comment]
I'm not able to reproduce this with VS 2017 15.7.1.

![image](https://user-images.githubusercontent.com/16944/40313569-0806dfc8-5ccb-11e8-8302-a4218efcf7b9.png)

**Comment by bradwilson** [comment]
Please re-open with a repro.
