### ISSUE TITLE
Error Message gets cut by size

### ISSUE THREAD

**Issue by redknightlois** [xunit/xunit#1783]
I have pretty specific test cases that guard against allocators keeping memory around (leaking) and because of that we end up needing to capture the stack trace at the construction of the object to be thrown later when the condition happens. We then package the stack trace information onto the message of the thrown exception for further inspection. 

The output of xUnit runner gets cut down and we are not able to see the full call stack (in fact we only see the most uninteresting part which is the xUnit stuff). I am assuming xUnit runner is cutting short, could be something else in the chain though. 

```
Starting test execution, please wait...
The active test run was aborted. Reason: :/Dev/xunit/xunit/src/xunit.execution/Sdk/Frameworks/Runners/TestCaseRunner.cs:line 82
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<RunSummary> Xunit.Sdk.TestCaseRunner<TTestCase>.RunAsync()
   at Task<RunSummary> Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(IXunitTestCase testCase) in C:/Dev/xunit/xunit/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestMethodRunner.cs:line 45
   at async Task<RunSummary> Xunit.Sdk.TestMethodRunner<TTestCase>.RunTestCasesAsync() in C:/Dev/xunit/xunit/src/xunit.execution/Sdk/Frameworks/Runners/TestMethodRunner.cs:line 136
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<RunSummary> Xunit.Sdk.TestMethodRunner<TTestCase>.RunTestCasesAsync()
   at async Task<RunSummary> Xunit.Sdk.TestMethodRunner<TTestCase>.RunAsync() in C:/Dev/xunit/xunit/src/xunit.execution/Sdk/Frameworks/Runners/TestMethodRunner.cs:line 106
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<RunSummary> Xunit.Sdk.TestMethodRunner<TTestCase>.RunAsync()
   at async Task<RunSummary> Xunit.Sdk.TestClassRunner<TTestCase>.RunTestMethodsAsync() in C:/Dev/xunit/xunit/src/xunit.execution/Sdk/Frameworks/Runners/TestClassRunner.cs:line 213
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<RunSummary> Xunit.Sdk.TestClassRunner<TTestCase>.RunTestMethodsAsync()
   at async Task<RunSummary> Xunit.Sdk.TestClassRunner<TTestCase>.RunAsync() in C:/Dev/xunit/xunit/src/xunit.execution/Sdk/Frameworks/Runners/TestClassRunner.cs:line 171
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<RunSummary> Xunit.Sdk.TestClassRunner<TTestCase>.RunAsync()
   at async Task<RunSummary> Xunit.Sdk.TestCollectionRunner<TTestCase>.RunTestClassesAsync() in C:/Dev/xunit/xunit/src/xunit.execution/Sdk/Frameworks/Runners/TestCollectionRunner.cs:line 130
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<RunSummary> Xunit.Sdk.TestCollectionRunner<TTestCase>.RunTestClassesAsync()
   at async Task<RunSummary> Xunit.Sdk.TestCollectionRunner<TTestCase>.RunAsync() in C:/Dev/xunit/xunit/src/xunit.execution/Sdk/Frameworks/Runners/TestCollectionRunner.cs:line 101
   at void System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start<TStateMachine>(ref TStateMachine stateMachine)
   at Task<RunSummary> Xunit.Sdk.TestCollectionRunner<TTestCase>.RunAsync()
   at Task<RunSummary> Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionsAsync(IMessageBus messageBus, CancellationTokenSource cancellationTokenSource)+() => { } in C:/Dev/xunit/xunit/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestAssemblyRunner.cs:line 184
   at void System.Threading.Tasks.SynchronizationContextTaskScheduler.s_postCallback(object s)
   at void Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, object state) in C:/Dev/xunit/xunit/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 107
   at void Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc() in C:/Dev/xunit/xunit/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs:line 89
   at void System.Threading.Thread.ThreadMain_ParameterizedThreadStart(object parameter)
   at void System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state) End Construction Stack Trace
   at Sparrow.NativeAllocator`1.CheckForLeaks(NativeAllocator`1& allocator) in S:\Source\ravendb-40.git\src\Sparrow\Allocators.Native.cs:line 188
   at Sparrow.NativeAllocator`1.Dispose(NativeAllocator`1& allocator) in S:\Source\ravendb-40.git\src\Sparrow\Allocators.Native.cs:line 172
   at Sparrow.Allocator`1.Finalize() in S:\Source\ravendb-40.git\src\Sparrow\Allocators.cs:line 105

Total tests: Unknown. Passed: 2. Failed: 0. Skipped: 0.
Test Run Aborted.
```

**Comment by bradwilson** [comment]
We don't control this message (and whether it gets cut up or not). This message is generated by VSTest.

**Comment by bradwilson** [comment]
Can you provide a repro of the problem?

**Comment by bradwilson** [comment]
Please re-open with repro project
