### ISSUE TITLE
Generic Theory test fails on .NET Core 2.1 but passes on .NET Core 2.0

### ISSUE THREAD

**Issue by HenrikFrystykNielsen** [xunit/xunit#1803]
This test runs on .NET Core 2.0 but fails on .NET Core 2.1:

```
using Xunit;

namespace XUnitRepro
{
    public class TestClass
    {
        public static TheoryData<object> TestData
        {
            get
            {
                return new TheoryData<object>
                {
                    { "hello" }
                };
            }
        }

        [Theory]
        [MemberData(nameof(TestData))]
        public void Test<T>(T input)
        {
            Assert.NotNull(input);
        }
    }
}
```

The error message on .NET Core 2.1 is

```
Test Name:	XUnitRepro.TestClass.Test
Test FullName:	XUnitRepro.TestClass.Test
Test Source:	D:\dd\Scratch\NetCore\XUnitRepro\XUnitRepro\TestClass.cs : line 20
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result StackTrace:	
at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location where exception was thrown ---
Result Message:	System.NotSupportedException : Specified method is not supported.
```

Any ideas?

**Comment by HenrikFrystykNielsen** [comment]
That worked - thanks!
