### ISSUE TITLE
System.IO.FileNotFound exception when testing project compiled with reference assemblies against SDK

### ISSUE THREAD

**Issue by rjmholt** [xunit/xunit#1807]
Hi, I'm a maintainer of the [PowerShellEditorServices](https://github.com/PowerShell/PowerShellEditorServices) project.

I'm currently porting the project to netstandard2.0 and have been retargeting our tests for netcoreapp2.0 and net461 accordingly.

The project itself is used as a PowerShell module and is compiled against netstandard2.0 and the [PowerShell Standard](https://github.com/PowerShell/PowerShellStandard) reference assemblies -- the point being that at runtime the module hooks into the PowerShell runtime hosting it. That all works -- I've been able to manually test it.

But our tests are in xUnit, and in that case we need to simulate the underlying PowerShell runtime. From what I can tell, the best way to do that is to reference the [PowerShell (Core) SDK](https://powershell.myget.org/feed/powershell-core/package/nuget/Microsoft.PowerShell.SDK) in the test csproj files (we'd also do similar for the Windows PowerShell reference assemblies, but one step at a time).

I currently have it set up to do this ([test csproj](https://github.com/rjmholt/PowerShellEditorServices/blob/master/test/PowerShellEditorServices.Test/PowerShellEditorServices.Test.csproj)), but the tests fail at runtime, with an output like:
```
[xUnit.net 00:00:01.8378100]     PSLanguageService.Test.ScriptFilePositionTests.CanComposePositionOperations [FAIL]
Failed   Microsoft.PowerShell.EditorServices.Test.Extensions.ExtensionServiceTests.CanUnregisterCommand
Error Message:
 System.IO.FileNotFoundException : Could not load file or assembly 'System.Management.Automation, Version=6.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.

Stack Trace:
   at Microsoft.PowerShell.EditorServices.Test.PowerShellContextFactory.Create(ILogger logger)
   at Microsoft.PowerShell.EditorServices.Test.Extensions.ExtensionServiceTests.InitializeAsync() in /home/rob/Documents/Dev/Microsoft/PowerShellEditorServices/test/PowerShellEditorServices.Test/Extensions/ExtensionServiceTests.cs:line 41
Failed   Microsoft.PowerShell.EditorServices.Test.Extensions.ExtensionServiceTests.CanRegisterAndInvokeCommandWithCmdletName
Error Message:
 System.IO.FileNotFoundException : Could not load file or assembly 'System.Management.Automation, Version=6.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```

Other tests fail because `null` is returned, essentially because the reference assemblies return `default(T)` from all APIs; expected behaviour if there's no other assembly to resolve against.\

So basically I'm trying to get the tests to bind the netstandard2.0 library to the chosen PowerShell runtime, but haven't had any success yet.

In terms of what I've tried so far:
- I read https://github.com/dotnet/standard/issues/481 and added the following to my test csproj:
    ```csproj
    <PropertyGroup>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    </PropertyGroup>
    ```
- I upgraded to the latest 2.4.1-preview build of xUnit

Is there anything else I should/can try? Or maybe something I've missed that makes this expected behaviour?

**EDIT**: Meant to mention, I checked the System.Management.Automation 6.1.0-rc.1 assembly installed on my machine and it matches the full name given in the FileNotFoundException:
```powershell
> [System.Reflection.AssemblyName]::GetAssemblyName('/home/rob/.nuget/packages/microsoft.powershell.sdk/6.1.0-rc.1/ref/netstandard2.0/System.Management.Automation.dll').FullName
System.Management.Automation, Version=6.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
```

**Comment by rjmholt** [comment]
I've worked this out now.

In my src libraries, I needed to reference PowerShell Standard with `PrivateAssets="all"`, so that the dependency isn't passed on to xUnit.

Just thought I'd document it here in case anyone else has a similar hurdle!

Thanks!
