### ISSUE TITLE
dotnet-xunit fails on .net core 2.2-preview 3

### ISSUE THREAD

**Issue by shatl** [xunit/xunit#1835]
dotnet xunit fails to run netcoreapp2.1 targets with following exception

```
System.ArgumentException: Version string portion was too short or too long.
Parameter name: input
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Program.RunTargetFramework(String testProject, String targetFramework, Boolean amendOutputFileNames) in C:\projects\xunit\src\dotnet-xunit\Program.cs
:line 348
   at Program.Execute(String[] args) in C:\projects\xunit\src\dotnet-xunit\Program.cs:line 140
```

Command line: `dotnet xunit --fx-version 2.1.5` or `dotnet xunit`

**dotnet --info** output:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.100-preview3-009430
 Commit:    e0a11c9929

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.100-preview3-009430\

Host (useful for support):
  Version: 2.2.0-preview3-27014-02
  Commit:  525082ca3e

.NET Core SDKs installed:
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.2.100-preview3-009430 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0-preview3-35497 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0-preview3-27014-02 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by bradwilson** [comment]
dotnet-xunit was removed in 2.4.

**Comment by jnm2** [comment]
https://www.nuget.org/packages/dotnet-xunit doesn't have a minor rollforward policy, so to use 2.3.1 would mean installing .NET Core 2.0 which is EOL. Does this mean that `dotnet-xunit` is effectively deprecated?

Assuming there's no way to run it on a living version of .NET COre, what's the best page for me to point to when I remove `<DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />` from open-source projects?
