### ISSUE TITLE
Problems with xunit.runner.visualstudio nuget package

### ISSUE THREAD

**Issue by marcin-chwedczuk-meow** [xunit/xunit#1852]
`xunit.runner.visualstudio.testadapter` assembly is referencing Microsoft.VisualStudio.TestPlatform.ObjectModel which may not be present on the target machine. Either please reference another nuget package that provides this assembly (`Microsoft.TestPlatform.ObjectModel`) as a nuget dependency or remove this dependency altogether. It causes me some errors when I use custom assertion library called NFluent: 
```
[xUnit.net 00:00:01.86]     CyberVadis.Core.Functions.Test.UnitTest1.Test1 [FAIL]
Failed   CyberVadis.Core.Functions.Test.UnitTest1.Test1
Error Message:
 System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Stack Trace:
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at NFluent.Helpers.ExceptionHelper.ExceptionScanner(String assemblyMarker, String nameSpace, String assertionExceptionName, String ignoreExceptionName, String inconclusiveExceptionName)
   at NFluent.Helpers.ExceptionHelper.get_Constructors()
   at NFluent.Helpers.ExceptionHelper.BuildException(String theMessage)
   at NFluent.Kernel.ExceptionReporter.ReportError(String message)
   at NFluent.Kernel.CheckLogic`1.ReportError(FluentMessage fluentMessage)
   at NFluent.Kernel.CheckLogic`1.EndCheck()
   at NFluent.ObjectCheckExtensions.IsSameReferenceAs[T,TU](ICheck`1 check, TU expected)
```

**Comment by bradwilson** [comment]
This is working as designed.

The referenced assembly is a contract assembly which is expected to be provided by the version of Visual Studio (and/or VSTest) which is running the tests.

**Comment by marcin-chwedczuk-meow** [comment]
I use `dotnet` command to both build and run tests on my project on CI server (so I do not have VS installed there). Adding `xunit.runner.visualstudio.testadapter` is the only way that I know to have xunit tests runnable via `dotnet test` command (see: https://xunit.github.io/docs/getting-started-dotnet-core). Also please think about people that use linux to develop .NET core apps. As I stated earlier the problem is that this assembly is statically referenced - maybe if it would be loaded dynamically or if you could provide a separate runner nuget package for `dotnet test` that is not referencing this assembly it would solve the problems...

**Comment by bradwilson** [comment]
I'm confused about what you're trying to do. Please provide a repro project & steps that illustrates the problem.

**Comment by marcin-chwedczuk-meow** [comment]
Give me some time please, I am quite busy this week but I should provide a test project within next 7 days.

**Comment by marcin-chwedczuk-meow** [comment]
Demo project: https://github.com/marcin-chwedczuk-meow/xunit-assembly-load-problem

Open solution in Visual Studio, run both tests. One should pass, one should fail with meaningful error message (that references are not equal).

Now let's use a command line, go to the directory with csproj file and run `dotnet test` command (after `dotnet restore; dotnet build`. You will receive the two following errors:

```

$ dotnet test
Build started, please wait...
Build completed.

Test run for C:\Users\xxxx\tmp\foooo\xunit-assembly-load-problem\XUnitTestProject1\bin\Debug\net461\XUnitTestProject1.dll(.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.66]     XUnitTestProject1.UnitTest1.Test1 [FAIL]
[xUnit.net 00:00:00.71]     XUnitTestProject1.ExplicitAssemblyScan.Show_error [FAIL]
Failed   XUnitTestProject1.UnitTest1.Test1
Error Message:
 System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
---- System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Stack Trace:
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at NFluent.Helpers.ExceptionHelper.ExceptionScanner(String assemblyMarker, String nameSpace, String assertionExceptionName, String ignoreExceptionName, String inconclusiveExceptionName)
   at NFluent.Helpers.ExceptionHelper.get_Constructors()
   at NFluent.Helpers.ExceptionHelper.BuildException(String theMessage)
   at NFluent.Kernel.ExceptionReporter.ReportError(String message)
   at NFluent.Kernel.CheckLogic`1.ReportError(FluentMessage fluentMessage)
   at NFluent.Kernel.CheckLogic`1.EndCheck()
   at NFluent.ObjectCheckExtensions.IsSameReferenceAs[T,TU](ICheck`1 check, TU expected)
   at XUnitTestProject1.UnitTest1.Test1() in C:\Users\xxxx\tmp\foooo\xunit-assembly-load-problem\XUnitTestProject1\UnitTest1.cs:line 12
----- Inner Stack Trace -----

Failed   XUnitTestProject1.ExplicitAssemblyScan.Show_error
Error Message:
 System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
---- System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Stack Trace:
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at XUnitTestProject1.ExplicitAssemblyScan.<Show_error>d__0.MoveNext() in C:\Users\xxxx\tmp\foooo\xunit-assembly-load-problem\XUnitTestProject1\ExplicitAssemblyScan.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----


Total tests: 2. Passed: 0. Failed: 2. Skipped: 0.
Test Run Failed.
Test execution time: 1.4202 Seconds
```

Strangely I tested this also on Linux and there it works without any problems. I also add that `dotnet test` command was run on the same machine that has Visual Studio installed (with ReSharper). 

Some versions:
```
$ dotnet --version
2.1.500

Microsoft Visual Studio Professional 2017 
Version 15.9.0
VisualStudio.15.Release/15.9.0+28307.53
Microsoft .NET Framework
Version 4.7.03056
```

The code that triggers error:
```cs
        [Fact]
        public async Task Show_error()
        {
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                assembly.GetExportedTypes();
            }
        }
```

**Comment by marcin-chwedczuk-meow** [comment]
PS. Please also note although I use .NET Core csproj format my target framework is   
```
<PropertyGroup>
    <TargetFramework>net461</TargetFramework>
  </PropertyGroup>
```
Of course when I tested this on Linux I cannot use this target so I used .NET Core App 2.1.

**Comment by bradwilson** [comment]
The bug is in NFluent.

`GetExportedTypes` is [documented](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.getexportedtypes) to potentially throw two exceptions (`FileNotFoundException` and `NotSupportedException`). Any code which calls this needs to be prepared to deal with these exceptions, but NFluent is not properly handling that case: https://github.com/tpierrain/NFluent/blob/adc02216486658ed3a563902e072d9374b18896e/src/NFluent/Helpers/ExceptionHelper.cs#L91-L92

You should open a bug against NFluent.
