### ISSUE TITLE
new CultureInfo() doesn't throw on Linux with xUnit

### ISSUE THREAD

**Issue by derwasp** [xunit/xunit#1859]
Sorry if it's a dupe, but here's what I found:

Summary: xUnit tests don't throw an expected exception on **linux**, though a command line application does.

If you run the following script in bash it would throw an exception, as expected:

```
mkdir testConsoleApp
cd testConsoleApp
dotnet new console

cat >./Program.cs <<EOL
using System;
namespace testConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var c = new System.Globalization.CultureInfo("randomtexthere");
            Console.WriteLine("Hello World!");
        }
    }
}
EOL

dotnet run
```
Example output:

```
root@5eb8f8ad8848:/src/testConsoleApp# dotnet run

Unhandled Exception: System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: name
randomtexthere is an invalid culture identifier.
   at System.Globalization.CultureInfo.InitializeFromName(String name, Boolean useUserOverride)
   at testConsoleApp.Program.Main(String[] args) in /src/testConsoleApp/Program.cs:line 8
```

But this one will not, it will say that the test has passed

```
mkdir testXUnitApp
cd testXUnitApp
dotnet new xunit

using System;
using Xunit;

cat >./UnitTest1.cs <<EOL
using System;
using Xunit;
namespace xunittest
{
    public class UnitTest1
    {
        [Fact]
        public void Test1()
        {
             new System.Globalization.CultureInfo("randomtexthere");
        }
    }
}
EOL

dotnet test
```

Example output:

```
root@5eb8f8ad8848:/mnt/src/testXUnitApp# dotnet test

Build started, please wait...
Build completed.

Test run for /mnt/src/testXUnitApp/bin/Debug/netcoreapp2.1/testXUnitApp.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.4043 Seconds
```

The same thing fails on windows:

```
D:\Temp\delme\xunittest>dotnet test
Build started, please wait...
Build completed.

Test run for D:\Temp\delme\xunittest\bin\Debug\netcoreapp2.1\xunittest.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.61]     xunittest.UnitTest1.Test1 [FAIL]
Failed   xunittest.UnitTest1.Test1
Error Message:
 System.Globalization.CultureNotFoundException : Culture is not supported.
Parameter name: name
randomtexthere is an invalid culture identifier.
Stack Trace:
   at System.Globalization.CultureInfo.InitializeFromName(String name, Boolean useUserOverride)
   at xunittest.UnitTest1.Test1() in D:\Temp\delme\xunittest\UnitTest1.cs:line 11

Total tests: 1. Passed: 0. Failed: 1. Skipped: 0.
Test Run Failed.
Test execution time: 1.4006 Seconds
```

**Expected result**

Test fails with `System.Globalization.CultureNotFoundException: Culture is not supported.`

**Comment by derwasp** [comment]
Seems like a .net core bug. It only reproduces if the input string is short enough.

This this will actually work:

```
mkdir testConsoleApp
cd testConsoleApp
dotnet new console

cat >./Program.cs <<EOL
using System;
namespace testConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var c = new System.Globalization.CultureInfo("9test9");
            Console.WriteLine("Hello World!");
        }
    }
}
EOL

dotnet run
```

**Comment by derwasp** [comment]
https://github.com/dotnet/coreclr/issues/21306
