### ISSUE TITLE
Testing projects that depend on x86 DLLs

### ISSUE THREAD

**Issue by nicolasr75** [xunit/xunit#1975]
I know there have been several issues about x86 testing but they all seem slightly different from mine: I have a .NET Framework project which needs to pinvoke a native 32-bit DLL. For that I changed my project from "Any CPU" to "x86". I then created an xunit test project which I also changed to "x86". When I try to run my two simple tests I get the following (sorry partly in German):

```
[26.06.2019 01:35:29 Informational] ------ Discover test started ------
[26.06.2019 01:35:29 Warning] Der Testlauf verwendet DLLs, die für das Framework .NETCoreApp,Version=v1.0 und die Plattform X86 erstellt wurden. Die folgenden DLLs sind nicht Teil der Ausführung: 
"FF2ProviderTest.dll" wurde für das Framework 2.2 und die Plattform X86 erstellt.
.Navigieren Sie zu http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409, um weitere Details zum Verwalten dieser Einstellungen zu erhalten.

[26.06.2019 01:35:30 Informational] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.1 (64-bit .NET Core 4.6.27617.05)
[26.06.2019 01:35:31 Warning] [xUnit.net 00:00:00.89] Exception discovering tests from FF2ProviderTest: System.BadImageFormatException: Could not load file or assembly 'FF2ProviderTest, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. Es wurde versucht, eine Datei mit einem falschen Format zu laden.
File name: 'FF2ProviderTest, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Xunit.Sdk.ReflectionAssemblyInfo..ctor(String assemblyFileName) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionAssemblyInfo.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at Xunit.AppDomainManager_NoAppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args) in C:\Dev\xunit\xunit\src\xunit.runner.utility\AppDomain\AppDomainManager_NoAppDomain.cs:line 31
   at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2Discoverer.cs:line 101
   at Xunit.Xunit2..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyTestAssemblyExists) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2.cs:line 46
   at Xunit.XunitFrontController.CreateInnerController() in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 144
   at Xunit.XunitFrontController.EnsureInitialized() in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 163
   at Xunit.Runner.VisualStudio.VsTestRunner.DiscoverTestsInSource[TVisitor](XunitFrontController framework, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, Func`4 visitorFactory, Action`4 visitComplete, String assemblyFileName, Boolean shadowCopy, TestAssemblyConfiguration configuration) in C:\Dev\xunit\xunit\src\xunit.runner.visualstudio\VsTestRunner.cs:line 280


[26.06.2019 01:35:31 Warning] In C:\Daten\Test\FF2ProviderTest\bin\Debug\netcoreapp2.2\FF2ProviderTest.dll ist kein Test verfügbar. Stellen Sie sicher, dass Testdiscoverer und -executor registriert und die Versionseinstellungen für Plattform und Framework richtig sind, und versuchen Sie es anschließend noch mal.
[26.06.2019 01:35:31 Informational] ========== Discover test finished: 0 found (0:00:02,7820027) ==========
```
As I see it, it always tries to start a 64-bit instance of XUnit which of course can't load the x86 modules.

From reading other posts/issues I thought a .runsettings file may help, so I included xunit.runsettings with the following content:

```
<?xml version="1.0" encoding="utf-8"?>  
<RunSettings>  
  <!-- Configurations that affect the Test Framework -->  
  <RunConfiguration>  
    <!-- [x86] | x64    
      - You can also change it from menu Test, Test Settings, Default Processor Architecture -->  
      <TargetPlatform>x86</TargetPlatform>
  </RunConfiguration>  
</RunSettings>
```

Unfortunately it leads to the same error. As suggested in other issues I also explicitly installed an x86 .NET Core SDK but that didn't help either.

The used packages are the following:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.1.1" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.console" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

```

Any idea what could be the problem? Is this an issue with XUnit at all or with Visual Studio?

Environment:
Visual Studio 2019
Windows 10
.NET Core Runtime 2.2.300

**Comment by bradwilson** [comment]
Moving to the VSTest adapter item tracker.
