### ISSUE TITLE
Missing StackTrace on (some) failed Asserts when executing tests in target Release build

### ISSUE THREAD

**Issue by ricfre** [xunit/xunit#205]
I'm not sure if this is a feature request, a bug, expected behavior, or simply me doing something wrong, but here goes.

Consider the following setup:

```
public class Class1
{
    [Fact]
    public void FailingEqualTest()
    {
        Assert.Equal(1, 2);
    }

    [Fact]
    public void FailingTrueTest()
    {
        Assert.True(false);
    }

    [Fact]
    public void FailingNullTest()
    {
        Assert.Null(new object());
    }
}
```

If i build with **Debug** configuration and execute the tests with the console runner I get the following result:

``` bat
C:\xUnitTest>packages\xunit.runners.1.9.2\tools\xunit.console.clr4.exe Net45\bin\Debug\Net45.dll
xUnit.net console test runner (64-bit .NET 4.0.30319.18408)
Copyright (C) 2013 Outercurve Foundation.

xunit.dll:     Version 1.9.2.1705
Test assembly: C:\xUnitTest\Net45\bin\Debug\Net45.dll

Net45.Class1.FailingTrueTest [FAIL]
   Assert.True() Failure
   Stack Trace:
      c:\xUnitTest\Net45\Class1.cs(16,0): at Net45.Class1.FailingTrueTest()

Net45.Class1.FailingEqualTest [FAIL]
   Assert.Equal() Failure
   Expected: 1
   Actual:   2
   Stack Trace:
      c:\xUnitTest\Net45\Class1.cs(10,0): at Net45.Class1.FailingEqualTest()

Net45.Class1.FailingNullTest [FAIL]
   Assert.Null() Failure
   Expected: (null)
   Actual:   System.Object
   Stack Trace:
      c:\xUnitTest\Net45\Class1.cs(22,0): at Net45.Class1.FailingNullTest()

3 total, 3 failed, 0 skipped, took 0.329 seconds
```

If i build with **Release** configuration and execute the tests with the console runner I get the following result:

``` bat
C:\xUnitTest>packages\xunit.runners.1.9.2\tools\xunit.console.clr4.exe Net45\bin\Release\Net45.dll
xUnit.net console test runner (64-bit .NET 4.0.30319.18408)
Copyright (C) 2013 Outercurve Foundation.

xunit.dll:     Version 1.9.2.1705
Test assembly: C:\xUnitTest\Net45\bin\Release\Net45.dll

Net45.Class1.FailingEqualTest [FAIL]
   Assert.Equal() Failure
   Expected: 1
   Actual:   2

Net45.Class1.FailingTrueTest [FAIL]
   Assert.True() Failure
   Stack Trace:
      c:\xUnitTest\Net45\Class1.cs(16,0): at Net45.Class1.FailingTrueTest()

Net45.Class1.FailingNullTest [FAIL]
   Assert.Null() Failure
   Expected: (null)
   Actual:   System.Object

3 total, 3 failed, 0 skipped, took 0.332 seconds
```

In other words, the StackTrace is missing for Assert.Equal and Assert.Null in **Release** configuration. Assert.True contains the StackTrace in both Debug and Release configuration. 

I'm currently using "xUnit.net v1.9.2" and "xUnit.net: Runners v1.9.2" (both via NuGet).

To me, the StackTrace is the most convenient way to locate errors on the build server and then quickly locating the Assert that is actually failing.

Is this a bug, expected behavior, or simply me doing something wrong?

**Comment by turquoiseowl** [comment]
It is possible to disable the inlining optimizations that cause stacktrace frames to be missing by adding a .Net .INI file for the assembly(s) in quesiton.

Here's an example that works for me when used with the v1.9.2 console test runner. The file is called ```Func.Test.ini``` to go with the test assembly ```Func.Test.dll```. Note also that the ```/noshadow``` argument to ```xunit.console.clr4.exe``` seems to be necessary to get this to work.

```
; INI file to solve the problem of missing frames in stacktrace for failed tests.
; This can result from inlining performed by JIT optimizer in Release builds.
; The settings here effectively prevent the JIT compiler from performing theres optimizations.
; Ensure this file is named after the subject assembly file where the .DLL/.EXE file name extension
; is replaced by .INI - e.g. "Func.Test.ini"
; NB: for the XUnit console test runner, it is necessary to use the /noshadow argument for this
; file to be picked up - presumably because the shadow mechanism fails to pick up the file.
; https://www.hanselman.com/blog/ReleaseISNOTDebug64bitOptimizationsAndCMethodInliningInReleaseBuildCallStacks.aspx
; https://blogs.technet.microsoft.com/appssrv/2009/09/04/how-to-bulk-disable-optimization-for-net-assemblies-using-a-powershell-script/
; https://github.com/xunit/xunit/issues/205

[.NET Framework Debugging Control]
GenerateTrackingInfo=1
AllowOptimize=0
```
