### ISSUE TITLE
Null Reference when running tests

### ISSUE THREAD

**Issue by ghost** [xunit/xunit#206]
Hi,

I am running into this issue whe running my xUnit tests inside of Visual Studio.  Not sure the ability to reproduce this issue.  Happens on any run.

Apologies if the format isn't correct. Using the latest version of xUnit.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Xunit.Xunit1ExceptionUtility.ConvertToFailureInformation(XmlNode failureNode)
   at Xunit.TestClassCallbackHandler.OnTest(XmlNode xml)
   at Xunit.TestClassCallbackHandler.OnXmlNode(XmlNode xml)
   at Xunit.XmlNodeCallbackHandler.System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
   at System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Xunit.Sdk.ExecutorCallback.CallbackEventHandlerCallback.Notify(String value)
   at Xunit.Sdk.Executor.OnTestResult(ITestResult result, ExecutorCallback callback)
   at Xunit.Sdk.Executor.RunTests.<>c__DisplayClass12.<.ctor>b__11(ITestResult result)
   at Xunit.Sdk.TestClassCommandRunner.Execute(ITestClassCommand testClassCommand, List`1 methods, Predicate`1 startCallback, Predicate`1 resultCallback)
   at Xunit.Sdk.Executor.RunTests.<>c__DisplayClass12.<.ctor>b__f()
   at Xunit.Sdk.Executor.ThreadRunner(Object threadStart)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Object reference not set to an instance of an object.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Xunit.Sdk.ExecutorCallback.CallbackEventHandlerCallback.Notify(String value)
   at Xunit.Sdk.Executor.OnTestResult(ITestResult result, ExecutorCallback callback)
   at Xunit.Sdk.Executor.RunTests.<>c__DisplayClass12.<.ctor>b__11(ITestResult result)
   at Xunit.Sdk.TestClassCommandRunner.Execute(ITestClassCommand testClassCommand, List`1 methods, Predicate`1 startCallback, Predicate`1 resultCallback)
   at Xunit.Sdk.Executor.RunTests.<>c__DisplayClass12.<.ctor>b__f()
   at Xunit.Sdk.Executor.ThreadRunner(Object threadStart)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
========== Run test finished: 0 run (0:01:02.8221767) ==========
```

**Comment by abatishchev** [comment]
I'm getting the same exception in TeamCity with [Meta Runner Plugin](https://github.com/rhysgodfrey/team-city-xunit-meta-runner/).
```
xUnit.net v1 Tests for Project.Server.Api.Test.Integration\bin\Release\Project.Server.Api.Test.Integration.dll (running for 13s)
Project.Server.Api.Test.Integration.Controllers.HomeControllerIntegrationTest.GetRoot_Should_Return_Status_NotFound (running for 13s)
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.

Server stack trace:
 at Xunit.TestClassCallbackHandler.OnTest(XmlNode xml)
 at Xunit.TestClassCallbackHandler.OnXmlNode(XmlNode xml)
 at Xunit.XmlNodeCallbackHandler.System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
 at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
 at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]:
 at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
 at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
 at System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
 --- End of inner exception stack trace ---
 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
 at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
 at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
 at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
 at Xunit.Sdk.Executor.OnTestResult(ITestResult result, ExecutorCallback callback)
 at Xunit.Sdk.TestClassCommandRunner.Execute(ITestClassCommand testClassCommand, List`1 methods, Predicate`1 startCallback, Predicate`1 resultCallback)
 at Xunit.Sdk.Executor.ThreadRunner(Object threadStart)
 at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
 at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
 at System.Threading.ThreadHelper.ThreadStart(Object obj)
```
Any thoughts, please?

**Comment by bradwilson** [comment]
Do you have a repro test that causes this issue?

**Comment by abatishchev** [comment]
I wish I had. Will work to create some. But so far I don't understand where it comes from.

**Comment by abatishchev** [comment]
Interesting. I've used to use Meta Runner TeamCity Plugin. This time I used xunit.console.exe (ver. 2.0.0.2650, both x64 and x86) and got the same exception.

What else can I try? Older version? Newer version? Thanks for help in advance.

**Comment by abatishchev** [comment]
Meta Runner TeamCity Plugin uses xunit.console.exe ver. 2.0.0.2665 and it throws the exception below.

Using console ver. 1.9.2.1705 works just fine.

2.x is available only as source code, correct? Can't find a per-compiled binary.

**Comment by bradwilson** [comment]
2.x is on NuGet, as pre-release packages. That is only way binaries are being distributed for 2.x.

https://www.nuget.org/packages/xunit/2.0.0-rc1-build2826
