### ISSUE TITLE
Regression for constrained generic tests using types containing implicit conversion

### ISSUE THREAD

**Issue by antonfirsov** [xunit/xunit#2061]
When upgrading from 2.3.1 to 2.4.1, the following generic theory fails:
```C#
public class Test
{
    public interface IConstraint { }

    public struct ShouldBeThis : IConstraint
    {
        public static implicit operator ShouldBeThis(GetsConvertedToThis x) => default;
        public static implicit operator GetsConvertedToThis(ShouldBeThis x) => default;
    }

    public static readonly TheoryData<object> Data = new TheoryData<object>()
    {
        default(ShouldBeThis)
    };

    public struct GetsConvertedToThis { }

    [Theory]
    [MemberData(nameof(Data))]
    public void Foo<T>(T x) where T : IConstraint { }
}
```

Stack trace:
```
System.ArgumentException : GenericArguments[0], 'Test+GetsConvertedToThis', on 'Void Foo[T](T)' violates the constraint of type 'T'.
---- System.Security.VerificationException : Method Test.Foo: type argument 'Test+GetsConvertedToThis' violates the constraint of type parameter 'T'.
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
----- Inner Stack Trace -----
   at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType declaringType, RuntimeType[] methodInstantiation)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
```

**Comment by bradwilson** [comment]
The problem here is `default(ShouldBeThis)` is a value without type: `null`. When we see this, we presume the type of `null` when closing a generic is `object`, which violates the constraint.

We are unlikely to fix this, as placing constraints on unit tests in not expected behavior (nor one that we would put into effort into supporting).
