### ISSUE TITLE
InvalidCastException is raised when using AssemblyRunner 

### ISSUE THREAD

**Issue by vincentlabonte** [xunit/xunit#2138]
I get the following error when I execute `var runner = AssemblyRunner.WithAppDomain(testAssemblyFileName)`:
```
Unhandled Exception: System.InvalidCastException: Unable to cast transparent proxy to type 'Xunit.DiaSessionWrapperHelper'.
   at Xunit.AppDomainManager_AppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args) in C:\Dev\xunit\xunit\src\xunit.runner.utility\AppDomain\AppDomainManager_AppDomain.cs:line 78
   at Xunit.DiaSessionWrapper..ctor(String assemblyFilename) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Utility\DiaSessionWrapper.cs:line 22
   at Xunit.VisualStudioSourceInformationProvider..ctor(String assemblyFileName) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\VisualStudioSourceInformationProvider.cs:line 24
   at Xunit.XunitFrontController..ctor(AppDomainSupport appDomainSupport, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, ISourceInformationProvider sourceInformationProvider, IMessageSink diagnosticMessageSink) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 70
   at Xunit.Runners.AssemblyRunner..ctor(AppDomainSupport appDomainSupport, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Runners\AssemblyRunner.cs:line 25
   at Xunit.Runners.AssemblyRunner.WithAppDomain(String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Runners\AssemblyRunner.cs:line 283
   at Runner.Runner.RunAsync() in C:\repos\XunitInvalidCastException\Runner\Runner.cs:line 24
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Console.Program.Main(String[] args) in C:\repos\XunitInvalidCastException\Console\Program.cs:line 18
```
For a specific repro please see [this project](https://github.com/vincentlabonte/XunitInvalidCastException).

**Comment by vincentlabonte** [comment]
I've also tried to use 'WithoutAppDomain' instead of 'WithAppDomain', but then again same result.

@bradwilson Did you get a chance to look into this?

**Comment by bradwilson** [comment]
What you're trying to do here is not supported: specifically, trying to separate the Console project from the Runner project and load it dynamically. I am relatively sure that the `Assembly.LoadFrom` is causing the issue, because it creates a special load context (different from the default load context that happens with implicitly loaded assemblies).

------

Unrelated, your code has a bug. The final line:

```
job.RunAsync().GetAwaiter().GetResult();
```

will fail, because the `RunAsync` method in `Runner` returns an `int`, not a `Task<int>`.

**Comment by vincentlabonte** [comment]
By subscribing to the `AppDomain.CurrentDomain.AssemblyResolve` event and making sure that the right assembly is getting loaded, I was able to fix the issue. This article and the xUnit MSBuild runner helped me to solve this.

Final solution:
```
AppDomain.CurrentDomain.AssemblyResolve += delegate (object sender, ResolveEventArgs e)
{
    String currentFolder = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
    AssemblyName requestedName = new AssemblyName(e.Name);
    if (requestedName.Name == "xunit.abstractions" || requestedName.Name == "xunit.runner.utility.net452")
    {
        var resolvedAssembly = Assembly.LoadFrom(Path.Combine(currentFolder, requestedName.Name + ".dll"));
        return resolvedAssembly;
    }
    return null;
};
```
