### ISSUE TITLE
ITestOutputHelper throws exception "There is no currently active test" randomly

### ISSUE THREAD

**Issue by Fabman08** [xunit/xunit#2146]
Hi guys,

I can't figure out this problem....

I have a .NET Framework 4.7.2 xUnit Project to test our DataModel Objects: it counts about 680 Fact Test Methods in order to check the consistency of our POCOs compared to our database tables.

I've tried to run the unit test with dotnet test (.net core 3.1), xunit.runner.console (v. 2.4.1), xunit.runner.visualstudio (v. 2.4.1) and also with Team City xUnit Runner (same as xunit.runner.console).

The problem is still the same: ITestOutputHelper throws "There is no currently active test" exception randomly.
Sometimes no errors, sometimes 1-2 errors, sometimes _n_ errors and the failed test methods are almost different every time.

I've tried to modify our _xunit.runner.json_ config file but without success.
I've tried to remove _ITestOutputHelper_ instances in every class but the problem still persist.
I've tried upgrading and downgrading xunit package without success. (actually v. 2.4.1)
I've tried to remove our Data Access Layer using EF 6.1 native methods without success.

The Unit Test Step is a part of out deployment pipeline in Team City so when unit test errors occurred the automation is stopped and the application is not deployed.

This is the exception thrown on a test method

```
_System.Data.Entity.Core.EntityCommandExecutionException
An error occurred while executing the command definition. See the inner exception for details.
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DataModel.Test.DataFacadeExtensions.ShouldNotBeNullOrThrow[T](IQueryableDataFacadeService queryableDataFacadeService) in Test\DataModel.Test\DataFacadeExtensions.cs:line 14
   at DataModel.Test.Addressbook.AddressbookConfigurationTest.AddressSearchHistoryShouldNotBeNullOrThrow() in Test\DataModel.Test\Addressbook\AddressbookConfigurationTest.cs:line 41

System.InvalidOperationException
There is no currently active test.
   at Xunit.Sdk.TestOutputHelper.GuardInitialized() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 51
   at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 62
   at System.Data.Entity.Infrastructure.Interception.DatabaseLogFormatter.LogCommand[TResult](DbCommand command, DbCommandInterceptionContext`1 interceptionContext)
   at System.Data.Entity.Infrastructure.Interception.DatabaseLogFormatter.Executing[TResult](DbCommand command, DbCommandInterceptionContext`1 interceptionContext)
   at System.Data.Entity.Infrastructure.Interception.DatabaseLogFormatter.ReaderExecuting(DbCommand command, DbCommandInterceptionContext`1 interceptionContext)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)_
```

I haven't attached any repos because the test works only with database. It can be useful watching the code only?

Thank you!
Regards

**Comment by bradwilson** [comment]
```
   at Xunit.Sdk.TestOutputHelper.GuardInitialized() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 51
   at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestOutputHelper.cs:line 62
   at System.Data.Entity.Infrastructure.Interception.DatabaseLogFormatter.LogCommand[TResult](DbCommand command, DbCommandInterceptionContext`1 interceptionContext)
   at System.Data.Entity.Infrastructure.Interception.DatabaseLogFormatter.Executing[TResult](DbCommand command, DbCommandInterceptionContext`1 interceptionContext)
   at System.Data.Entity.Infrastructure.Interception.DatabaseLogFormatter.ReaderExecuting(DbCommand command, DbCommandInterceptionContext`1 interceptionContext)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
```

This is Entity Framework code. How is `ITestOutputHelper` getting passed to it? We have no ties to EF.

You have code running after the test has finished. The most likely candidate is a ackground thread or task that's getting kicked off, but not waited for, though the fact that I see LINQ's `ToList()` directly above your code also indicates that you may have a delayed enumeration happening after the test has finished.

Once you've exited your test method, `ITestOutputHelper` is no longer valid. You must absolutely prevent any access to it once your test has finished.

Hopefully this helps you head in the right direction to find your bug. If not, then you'll need to provide a repro project.

**Comment by Fabman08** [comment]
Hi @bradwilson, thank you for your quick reply!

Here my simplified code

_Test Class_
```cs
public class AddressbookConfigurationTest : IClassFixture<AddressbookFixture>
{
	private readonly AddressbookFixture fixture;

	public AddressbookConfigurationTest(AddressbookFixture fixture, ITestOutputHelper output)
	{
		this.fixture = fixture;
		this.fixture.DbContext.Database.Log = output.WriteLine; // "How is ITestOutputHelper getting passed to it?"
	}

	[Fact]
	public void MyPOCO_One_ShouldNotBeNullOrThrow()
	{
		this.fixture.DbContext.ShouldNotBeNullOrThrow<POCO_One>();
	}
	
	[Fact]
	public void MyPOCO_Two_ShouldNotBeNullOrThrow()
	{
		this.fixture.DbContext.ShouldNotBeNullOrThrow<POCO_Two>();
	}
	
	[Fact]
	public void MyPOCO_N_ShouldNotBeNullOrThrow()
	{
		this.fixture.DbContext.ShouldNotBeNullOrThrow<POCO_N>();
	}
}
```
_Fixture Class_
```cs
public class AddressbookFixture: DataAccessFixtureBase
{
        protected override DbContext GetDbContext()
        {
            return new AddressbookDbContext("MyConnectionString");
        }
 }
```
_Fixture Base Class_
```cs
public abstract class DataAccessFixtureBase
{
	protected DataAccessFixtureBase()
	{		
		this.SetDbContext();
	}

	public DbContext DbContext
	{
		get;
		private set;
	}

	protected abstract DbContext GetDbContext();

	private void SetDbContext()
	{
		this.DbContext = this.GetDbContext();
	}
}
```
_Extensions Class_
```cs
public static class DataAccessExtensions
{        
        public static void ShouldNotBeNullOrThrow<T>(this DbContext dbContext)
            where T : class
        {
            var list = dbContext.Set<T>().Take(1).ToList(); // I've added ToList here as you suggested, but the exception still thrown
            Assert.NotNull(list);
        }
}
```

Have you got any suggest?

Thank you for your support!!!

**Comment by GeraldLx** [comment]
I basically copied your code with another DbContext and cannot reproduce the error.

I used NCrunch, CodeRush TestRunner and the inbuild VS Test Runner.

I had similiar problems trying to log in EF Core projects. The problem is that you only have access to the ITestOutputHelper while the test is running. So if you make the DbContext log to the test output, you risk that some asynchronous logging tries to write to the output while it is not possible anymore.

I would suggest to change your DataAccessFixtureBase to implement IDisposable and closing the context asap.

Perhaps this helps.

**Comment by bradwilson** [comment]
The problem is here:

```csharp

	public AddressbookConfigurationTest(AddressbookFixture fixture, ITestOutputHelper output)
	{
		this.fixture = fixture;
		this.fixture.DbContext.Database.Log = output.WriteLine; // "How is ITestOutputHelper getting passed to it?"
	}
```

The lifetime of the context is longer than the lifetime of the test. By handing off the output object to the context, it's now available to be used, even after the test is finished.

Why is it trying to do that? I don't know. But my suggestion is that you wrap the call to output.WriteLine rather than handing it off as-is so that you can prevent the problem, something like:

```csharp

	public AddressbookConfigurationTest(AddressbookFixture fixture, ITestOutputHelper output)
	{
		this.fixture = fixture;
		this.fixture.DbContext.Database.Log = text => {
                        try { output.WriteLine(text); }
                        catch { }
                }
	}
```

The exceptions will still be thrown, but they will be swallowed and ignored.

**Comment by Fabman08** [comment]
I've implemented IDisposabe on DataAccessFixtureBase as suggested by @GeraldLx .
Last 30 runs has thrown 0 errors!

I think I'll implement also @bradwilson solution to ensure our Deployment Pipeline will terminate without errors.

Thank you!!!

**Comment by skironDotNet** [comment]
I have  2 unrelated projects, both in .NET6 and in one works fine, and the other getting that error.
When injected, Output buffer is not initialized 
![image](https://user-images.githubusercontent.com/2981715/210889956-81db26c5-5b54-4986-993d-baba11234fc2.png)

When inherited test class from TestExtensions, works fine. So something with the DI is no right?

**Comment by bradwilson** [comment]
@skironDotNet You cannot use the type unless you're in the context of an actively running test. Any attempt to use it outside the context of a running test will result in the error you're seeing.

Also, you should probably open a new issue rather than commenting on a closed one. Please open a new issue if you believe you are using it correctly and can provide a simple repro. Thanks!
