### ISSUE TITLE
Test methods not found due to use of custom Fact Attribute

### ISSUE THREAD

**Issue by anthonydotnet** [xunit/xunit#2206]
Scenario: Occurs in Visual Studio Mac and on CLI

Given that you have a custom fact attribute inheriting from Xunit.FactAttribute.
When putting the custom fact attribute on a test method,
Then all the test methods below it in the file are no longer found.

See here: https://youtu.be/kktHEB_9b7g

**Comment by bradwilson** [comment]
I believe I was able to reproduce the problem. Please see my [live stream](https://www.twitch.tv/videos/826884825?t=00h23m15s) starting at the 23:15 mark (the link should take you there directly, I hope).

The TL;DW: I believe your custom Fact attribute is throwing an exception during discovery, which causes the discovery for that test class to stop. The reason you see everything above but not below is because of this error. I enabled [diagnostic messages](https://xunit.net/docs/configuration-files#diagnosticMessages) and when I built the tests in VS2019, the Output > Tests window showed this:

```
Log level is set to Informational (Default).
Test data store opened in 0.059 sec.
---------- Starting test discovery ----------
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.3+1b45f5407b (64-bit .NET 5.0.0)
[xUnit.net 00:00:00.24]   Discovering: xunit-2206 (method display = ClassAndMethod, method display options = None)
[xUnit.net 00:00:00.26] xunit-2206: Exception during discovery:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.DivideByZeroException: Attempted to divide by zero.
   at CustomFactAttribute..ctor() in C:\Dev\repro\xunit-2206\CustomFact.cs:line 8
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at Xunit.Sdk.ReflectionAttributeInfo.Instantiate(CustomAttributeData attributeData) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionAttributeInfo.cs:line 136
   at Xunit.Sdk.ReflectionMethodInfo.GetCustomAttributes(MethodInfo method, Type attributeType, AttributeUsageAttribute attributeUsage) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionMethodInfo.cs:line 100
   at Xunit.Sdk.ReflectionMethodInfo.GetCustomAttributes(MethodInfo method, String assemblyQualifiedAttributeTypeName) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionMethodInfo.cs:line 87
   at Xunit.Sdk.ReflectionMethodInfo.GetCustomAttributes(String assemblyQualifiedAttributeTypeName) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionMethodInfo.cs:line 80
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 84
   at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 132
   at Xunit.Sdk.TestFrameworkDiscoverer.FindTestsForTypeAndWrapExceptions(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\TestFrameworkDiscoverer.cs:line 156
[xUnit.net 00:00:00.26]   Discovered:  xunit-2206 (found 0 test cases)
No test is available in C:\Dev\repro\xunit-2206\bin\Debug\net5.0\xunit-2206.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 0 Tests found in 859.3 ms ==========
```

I assume there is something equivalent for VS Mac (I don't use it so I don't know).

**Comment by anthonydotnet** [comment]
Thanks Brad! This is perfect! 

It was indeed my own code which was causing this. A typo in a string!

Thanks for jumping on this so fast. You rock!
