### ISSUE TITLE
Test AssemblyRunner WithoutAppDomain fails to specify DLL version

### ISSUE THREAD

**Issue by jagohr** [xunit/xunit#2441]
We implemented a AssemblyRunner in .netcore3.1, but get a _could not load file or assembly_ on the target test dll. Drilling into the stack trace we see the exception is coming from this line in the xunit code:
`Assembly = Assembly.Load(new AssemblyName { Name = Path.GetFileNameWithoutExtension(assemblyFileName), Version = new Version(0, 0, 0, 0) });`

The test dll is built against .netcore3.1 as well. Are there any working examples of an assembly runner in .netcore3.1? 

```
Looking for EndpointTest dll in C:\repos\ms.mrservices.anchorfrontend\___output\test\Microsoft.MixedRealityServices.AnchorFrontEnd.EndpointTest\Debug\netcoreapp3.1
Found and executing these test dlls:
C:\repos\ms.mrservices.anchorfrontend\___output\test\Microsoft.MixedRealityServices.AnchorFrontEnd.EndpointTest\Debug\netcoreapp3.1\Microsoft.MixedRealityServices.AnchorFrontEnd.EndpointTest.dll
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.MixedRealityServices.AnchorFrontEnd.EndpointTest, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Microsoft.MixedRealityServices.AnchorFrontEnd.EndpointTest, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
at Xunit.Sdk.ReflectionAssemblyInfo..ctor(String assemblyFileName) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionAssemblyInfo.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
at ExceptionExtensions.RethrowWithNoStackTraceLoss(Exception ex) in C:\Dev\xunit\xunit\src\common\ExceptionExtensions.cs:line 29
at Xunit.AppDomainManager_NoAppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args) in C:\Dev\xunit\xunit\src\xunit.runner.utility\AppDomain\AppDomainManager_NoAppDomain.cs:line 31
at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2Discoverer.cs:line 102
at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2Discoverer.cs:line 63
at Xunit.Xunit2..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyTestAssemblyExists) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\v2\Xunit2.cs:line 46
at Xunit.XunitFrontController.CreateInnerController() in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 144
at Xunit.XunitFrontController.EnsureInitialized() in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 163
at Xunit.XunitFrontController.get_InnerController() in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 104
at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 173
at TestFrameworkExtensions.Find(ITestFrameworkDiscoverer discoverer, Boolean includeSourceInformation, IMessageSinkWithTypes discoveryMessageSink, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\Dev\xunit\xunit\src\xunit.runner.utility\Extensions\TestFrameworkExtensions.cs:line 23
at Xunit.Runners.AssemblyRunner.<>c__DisplayClass63_0.<Start>b__0() in C:\Dev\xunit\xunit\src\xunit.runner.utility\Runners\AssemblyRunner.cs:line 251
at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__4_0(Object _) in C:\Dev\xunit\xunit\src\common\XunitWorkerThread.cs:line 92
at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by bradwilson** [comment]
Unfortunately there appears to be no easy way for us to determine the version of the assembly without loading, and you can't load it without knowing its version number. I'm not 100% sure what the solution might be here, but someone from the .NET team is probably going to have to chime in with a suggestion.

**Comment by bilalisa2022** [comment]
What is the status? I'm having the same problem. Setting version to 0.0.0.0 on my dynamically generated assembly does not solve the issue. @jagohr if you found a solution, do you mind sharing it with me?

**Comment by bilalisa2022** [comment]
Here's my test runner
`
using Xunit.Runners;

namespace Company.Core.Tests.Utils
{
    public class TestRunner
    {
        private static readonly object ConsoleLock = new();

        private static readonly ManualResetEvent Finished = new(false);

        public int Result;

        private readonly string _assemblyFileName;

        public TestRunner(string assemblyFileName)
        {
            _assemblyFileName = assemblyFileName;
        }

        public int Start()
        {
            using var runner = AssemblyRunner.WithoutAppDomain(_assemblyFileName);
            runner.OnDiscoveryComplete = OnDiscoveryComplete;
            runner.OnExecutionComplete = OnExecutionComplete;
            runner.OnTestFailed = OnTestFailed;
            runner.OnTestSkipped = OnTestSkipped;

            Console.WriteLine("Discovering...");
            runner.Start();

            Finished.WaitOne();
            Finished.Dispose();

            return Result;
        }
        
        private void OnDiscoveryComplete(DiscoveryCompleteInfo info)
        {
            lock (ConsoleLock)
                Console.WriteLine($"Running {info.TestCasesToRun} of {info.TestCasesDiscovered} tests...");
        }

        private void OnExecutionComplete(ExecutionCompleteInfo info)
        {
            lock (ConsoleLock)
                Console.WriteLine($"Finished: {info.TotalTests} tests in {Math.Round(info.ExecutionTime, 3)}s ({info.TestsFailed} failed, {info.TestsSkipped} skipped)");

            Finished.Set();
        }

        private void OnTestFailed(TestFailedInfo info)
        {
            lock (ConsoleLock)
            {
                Console.ForegroundColor = ConsoleColor.Red;

                Console.WriteLine("[FAIL] {0}: {1}", info.TestDisplayName, info.ExceptionMessage);
                if (info.ExceptionStackTrace != null)
                    Console.WriteLine(info.ExceptionStackTrace);

                Console.ResetColor();
            }

            Result = 1;
        }

        private void OnTestSkipped(TestSkippedInfo info)
        {
            lock (ConsoleLock)
            {
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.WriteLine("[SKIP] {0}: {1}", info.TestDisplayName, info.SkipReason);
                Console.ResetColor();
            }
        }
    }
}
`

Here's how I use it

`
using ConsoleApp;
using Company.Core.Tests;
using Company.Core.Tests.Utils;

var assemblyPath = args[2];

var tester = new StrArgNullExcTester(args[0], args[1], assemblyPath);

tester.RegisterTestCase<DummyClass>(nameof(DummyClass.TestMethod1));
tester.RegisterTestCase<DummyClass>(nameof(DummyClass.TestMethod2));

tester.GenerateDynamicTestAssembly();

var testRunner = new TestRunner(assemblyPath);

testRunner.Start();

return testRunner.Result;
`

**Comment by bilalisa2022** [comment]
@bradwilson Have you considered using the .NET core way to load an assembly: `AssemblyLoadContext.Default.LoadFromAssemblyPath(assemblyPath);`

**Comment by bradwilson** [comment]
@bilalisa2022 `xunit.execution` does not target .NET Core, it targets .NET Standard 1.1. It is not realistically possible to change these dependency, because it would break forward compatibility from older v2 runner utility.

This isn't an issue with v3, since test assemblies are programs, not libraries, so they don't get loaded with `Assembly.Load`.

**Comment by bilalisa2022** [comment]
@bradwilson Can you spell out for me? What am doing wrong and what should I be doing instead?

**Comment by bradwilson** [comment]
@bilalisa2022 There isn't anything you can do about this that I'm aware of, short of pulling the v2 source, making the changes yourself, building your own version, and using that.
