### ISSUE TITLE
Custom discoverer causes VS test discovery to spin forever

### ISSUE THREAD

**Issue by shiftkey** [xunit/xunit#249]
xunit.core: 2.0.0-beta5-build2785
xunit.runner.visualstudio: 0.99.9-build1021

I'm staring at a custom discoverer which causes the discovery process in VS to get stuck.

### Repro

This code sits in the same project as the tests:

```
public class ApplicationTestDiscoverer : IXunitTestCaseDiscoverer
{
    public IEnumerable<IXunitTestCase> Discover(ITestMethod testMethod, IAttributeInfo factAttribute)
    {
        // removed the logic here, but the intent is to check environment
        // variables and skip the test if the environment isn't setup right

        // this works
        // yield return new XunitTestCase(testMethod);
        // this does not - and the discoverer gets stuck
        yield return new SkipTestCase(testMethod,
            "Environment variables are not set for this test - set OCTOKIT_CLIENTID and OCTOKIT_CLIENTSECRET");
    }
}

[XunitTestCaseDiscoverer("Octokit.Tests.Integration.ApplicationTestDiscoverer", "Octokit.Tests.Integration")]
public class ApplicationTestAttribute : FactAttribute
{
}

public class SkipTestCase : XunitTestCase
{
   public SkipTestCase(ITestMethod testMethod, string skipReason)
        : base(testMethod)
    {
        SkipReason = skipReason;
    }
}
```

### Output

```
------ Discover test started ------
[xUnit.net 00:00:00.0000018] Discovery started
[xUnit.net 00:00:00.1723200] Discovery starting: clean-up-after-tests.exe
[xUnit.net 00:00:00.1819448] Discovery finished: clean-up-after-tests.exe (0 tests)
[xUnit.net 00:00:00.3942438] Discovery starting: Octokit.Tests.Integration.dll
========== Discover test finished: 0 found (0:03:41.5496078) ========== <--- triggered rebuild here
------ Discover test started ------
[xUnit.net 00:00:00.0001348] Discovery started
[xUnit.net 00:00:13.9793443] Discovery starting: clean-up-after-tests.exe
[xUnit.net 00:00:13.9973857] Discovery finished: clean-up-after-tests.exe (0 tests)
[xUnit.net 00:00:14.2112575] Discovery starting: Octokit.Tests.Integration.dll
```

Let me know if you need a better repro.

**Comment by bradwilson** [comment]
You made a small and completely inevitable mistake (which is our fault). We made a huge mistake (which is also our fault).

The core of the problem is: test cases, if they want to run inside Visual Studio, must be serializable. The huge mistake we made was that we failed silently, in the wrong place, which caused us to spin forever waiting for discovery to complete.

This is our repro that works:

```csharp
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Security;
using Xunit;
using Xunit.Abstractions;
using Xunit.Sdk;
using Xunit.Serialization;

public class ApplicationTestDiscoverer : IXunitTestCaseDiscoverer
{
    public IEnumerable<IXunitTestCase> Discover(ITestFrameworkDiscoveryOptions discoveryOptions, ITestMethod testMethod, IAttributeInfo factAttribute)
    {
        yield return new SkipTestCase(discoveryOptions.MethodDisplay(), testMethod, "Environment variables are not set for this test - set OCTOKIT_CLIENTID and OCTOKIT_CLIENTSECRET");
    }
}

[XunitTestCaseDiscoverer("ApplicationTestDiscoverer", "v2_net45")]
public class ApplicationTestAttribute : FactAttribute
{
}

[Serializable]
public class SkipTestCase : XunitTestCase
{
    public SkipTestCase(TestMethodDisplay defaultTestMethodDisplay, ITestMethod testMethod, string skipReason)
        : base(defaultTestMethodDisplay, testMethod)
    {
        SkipReason = skipReason;
    }

    protected SkipTestCase(SerializationInfo info, StreamingContext context)
        : base(info, context)
    {
        SkipReason = info.GetString("SkipReason");
    }

    public override void GetData(XunitSerializationInfo data)
    {
        data.AddValue("SkipReason", SkipReason);

        base.GetData(data);
    }

    [SecurityCritical]
    public override void GetObjectData(SerializationInfo info, StreamingContext context)
    {
        info.AddValue("SkipReason", SkipReason);

        base.GetObjectData(info, context);
    }

    public override void SetData(XunitSerializationInfo data)
    {
        SkipReason = data.GetString("SkipReason");

        base.SetData(data);
    }
}

public class CustomSkipper
{
    [ApplicationTest]
    public void ThisShouldNeverRun()
    {
        Assert.True(false);
    }
}
```

Also, the next build of the Visual Studio runner will give you a much better message (meaning, actually give you a message :-p) if you forget to do the serialization stuff:

```
[xUnit.net 00:00:00.1597515] Discovery starting: v2_net45.dll (name display = ClassAndMethod)
Error creating Visual Studio test case for CustomSkipper.ThisShouldNeverRun: System.Runtime.Serialization.SerializationException: Type 'SkipTestCase' in Assembly 'v2_net45, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is not marked as serializable.

Server stack trace: 
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at Xunit.Sdk.SerializationHelper.Serialize(Object value)
   at Xunit.Sdk.TestFrameworkDiscoverer.Serialize(ITestCase testCase)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Xunit.Abstractions.ITestFrameworkDiscoverer.Serialize(ITestCase testCase)
   at Xunit.Xunit2Discoverer.Serialize(ITestCase testCase) in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.runner.utility\Frameworks\v2\Xunit2Discoverer.cs:line 143
   at Xunit.XunitFrontController.Serialize(ITestCase testCase) in c:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.runner.utility\Frameworks\XunitFrontController.cs:line 152
   at Xunit.Runner.VisualStudio.TestAdapter.VsDiscoveryVisitor.CreateVsTestCase(String source, ITestFrameworkDiscoverer discoverer, ITestCase xunitTestCase, Boolean forceUniqueNames, IMessageLogger logger) in d:\Dev\xunit\visualstudio.xunit\xunit.runner.visualstudio.testadapter\Visitors\VsDiscoveryVisitor.cs:line 51
[xUnit.net 00:00:00.3343543] Discovery finished: v2_net45.dll (10 tests)
```

We will keep this in our integration test project as well.

Thanks...

**Comment by shiftkey** [comment]
![](http://media0.giphy.com/media/ChTbtWsFB75oA/giphy.gif)

**Comment by bradwilson** [comment]
![](http://i.imgur.com/RPAkdES.gif)
