### ISSUE TITLE
Exceptions in GetData of DataAttribute get mis-reported as NotSupportedException

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#2555]
### Discussed in https://github.com/xunit/xunit/discussions/2522

<div type='discussions-op-text'>

<sup>Originally posted by **EraYaN** May  5, 2022</sup>
So the JsonFileDataAttribute for example (talked about here: https://andrewlock.net/creating-a-custom-xunit-theory-test-dataattribute-to-load-data-from-json-files/) will throw an ArgumentException if the file is not found, if this exception is thrown in the constructor this is fine and it works, but when thrown in GetData it gets hidden away and replaced by a NotSupportedException.

https://stackoverflow.com/a/59027705 for example also talks about this.

The only thing xUnit outputs is:

```
System.NotSupportedException : Specified method is not supported.
```

No stack trace, no inner exception, nothing. Would it be possible somehow to get at the original exception without attaching a debugger?

When running this with a Debugger attached, I get a 

```
System.MissingMethodException
  HResult=0x80131513
  Message=Constructor on type 'Xunit.Sdk.DataDiscoverer' not found.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture) in /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs:line 3658
```
with the call stack
```
System.Private.CoreLib.dll!System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture) Line 3683
	at /_/src/coreclr/System.Private.CoreLib/src/System/RuntimeType.CoreCLR.cs(3683)
System.Private.CoreLib.dll!System.Activator.CreateInstance(System.Type type, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, object[] args, System.Globalization.CultureInfo culture, object[] activationAttributes) Line 38
	at /_/src/libraries/System.Private.CoreLib/src/System/Activator.RuntimeType.cs(38)
xunit.execution.dotnet.dll!Xunit.Sdk.ExtensibilityPointFactory.CreateInstance(Xunit.Abstractions.IMessageSink diagnosticMessageSink, System.Type type, object[] ctorArgs) Line 25
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\ExtensibilityPointFactory.cs(25)
xunit.execution.dotnet.dll!Xunit.Sdk.ExtensibilityPointFactory.Get.AnonymousMethod__0() Line 70
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\ExtensibilityPointFactory.cs(70)
xunit.execution.dotnet.dll!DictionaryExtensions.GetOrAdd<System.Tuple<System.Type, Xunit.Abstractions.IMessageSink>, object>(System.Collections.Generic.IDictionary<System.Tuple<System.Type, Xunit.Abstractions.IMessageSink>, object> dictionary, System.Tuple<System.Type, Xunit.Abstractions.IMessageSink> key, System.Func<object> newValue) Line 34
	at C:\Dev\xunit\xunit\src\common\DictionaryExtensions.cs(34)
xunit.execution.dotnet.dll!Xunit.Sdk.ExtensibilityPointFactory.Get<Xunit.Sdk.IDataDiscoverer>(Xunit.Abstractions.IMessageSink diagnosticMessageSink, System.Type type, object[] ctorArgs) Line 70
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\ExtensibilityPointFactory.cs(70)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTheoryTestCaseRunner.AfterTestCaseStartingAsync() Line 71
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTheoryTestCaseRunner.cs(71)
xunit.execution.dotnet.dll!Xunit.Sdk.TestCaseRunner<Xunit.Sdk.IXunitTestCase>.RunAsync() Line 81
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestCaseRunner.cs(81)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTheoryTestCase.RunAsync(Xunit.Abstractions.IMessageSink diagnosticMessageSink, Xunit.Sdk.IMessageBus messageBus, object[] constructorArguments, Xunit.Sdk.ExceptionAggregator aggregator, System.Threading.CancellationTokenSource cancellationTokenSource) Line 51
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTheoryTestCase.cs(51)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(Xunit.Sdk.IXunitTestCase testCase) Line 45
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestMethodRunner.cs(45)
xunit.execution.dotnet.dll!Xunit.Sdk.TestMethodRunner<Xunit.Sdk.IXunitTestCase>.RunTestCasesAsync() Line 136
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs(136)
xunit.execution.dotnet.dll!Xunit.Sdk.TestMethodRunner<Xunit.Sdk.IXunitTestCase>.RunAsync() Line 106
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs(106)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTestClassRunner.RunTestMethodAsync(Xunit.Abstractions.ITestMethod testMethod, Xunit.Abstractions.IReflectionMethodInfo method, System.Collections.Generic.IEnumerable<Xunit.Sdk.IXunitTestCase> testCases, object[] constructorArguments) Line 168
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestClassRunner.cs(168)
xunit.execution.dotnet.dll!Xunit.Sdk.TestClassRunner<Xunit.Sdk.IXunitTestCase>.RunTestMethodsAsync() Line 213
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestClassRunner.cs(213)
xunit.execution.dotnet.dll!Xunit.Sdk.TestClassRunner<Xunit.Sdk.IXunitTestCase>.RunAsync() Line 171
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestClassRunner.cs(171)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTestCollectionRunner.RunTestClassAsync(Xunit.Abstractions.ITestClass testClass, Xunit.Abstractions.IReflectionTypeInfo class, System.Collections.Generic.IEnumerable<Xunit.Sdk.IXunitTestCase> testCases) Line 158
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestCollectionRunner.cs(158)
xunit.execution.dotnet.dll!Xunit.Sdk.TestCollectionRunner<Xunit.Sdk.IXunitTestCase>.RunTestClassesAsync() Line 130
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestCollectionRunner.cs(130)
xunit.execution.dotnet.dll!Xunit.Sdk.TestCollectionRunner<Xunit.Sdk.IXunitTestCase>.RunAsync() Line 101
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestCollectionRunner.cs(101)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionAsync(Xunit.Sdk.IMessageBus messageBus, Xunit.Abstractions.ITestCollection testCollection, System.Collections.Generic.IEnumerable<Xunit.Sdk.IXunitTestCase> testCases, System.Threading.CancellationTokenSource cancellationTokenSource) Line 235
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestAssemblyRunner.cs(235)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionsAsync.AnonymousMethod__2() Line 184
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestAssemblyRunner.cs(184)
System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task<Xunit.Sdk.RunSummary>>.InnerInvoke() Line 503
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs(503)
System.Private.CoreLib.dll!System.Threading.Tasks.Task..cctor.AnonymousMethod__272_0(object obj) Line 2376
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2376)
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 183
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(183)
System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot, System.Threading.Thread threadPoolThread) Line 2333
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2333)
System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteEntry() Line 2253
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2253)
System.Private.CoreLib.dll!System.Threading.Tasks.SynchronizationContextTaskScheduler..cctor.AnonymousMethod__8_0(object s) Line 629
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskScheduler.cs(629)
xunit.execution.dotnet.dll!Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(System.Threading.SendOrPostCallback callback, object state) Line 107
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs(107)
xunit.execution.dotnet.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc.AnonymousMethod__0(object _) Line 96
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs(96)
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 183
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(183)
xunit.execution.dotnet.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc() Line 89
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs(89)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitWorkerThread.QueueUserWorkItem.AnonymousMethod__5_0(object _) Line 37
	at C:\Dev\xunit\xunit\src\common\XunitWorkerThread.cs(37)
System.Private.CoreLib.dll!System.Threading.Tasks.Task.InnerInvoke() Line 2397
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2397)
System.Private.CoreLib.dll!System.Threading.Tasks.Task..cctor.AnonymousMethod__272_0(object obj) Line 2376
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2376)
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 183
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(183)
System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot, System.Threading.Thread threadPoolThread) Line 2333
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2333)
System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread threadPoolThread) Line 2277
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2277)
System.Private.CoreLib.dll!System.Threading.Tasks.ThreadPoolTaskScheduler..cctor.AnonymousMethod__10_0(object s) Line 36
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ThreadPoolTaskScheduler.cs(36)
System.Private.CoreLib.dll!System.Threading.Thread.StartCallback() Line 105
	at /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs(105)
```

and then right after the thrown exception in user code followed by
```
System.NotSupportedException
  HResult=0x80131515
  Message=Specified method is not supported.
  Source=xunit.execution.dotnet
  StackTrace:
   at Xunit.Sdk.ReflectionMethodInfo.get_Type() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionMethodInfo.cs:line 71
```
This happens in the InnerInvoke function (line 503) in the Future.cs file in th CoreLib/src/System/Threading/Tasks tree.
with call stack:
```
xunit.execution.dotnet.dll!Xunit.Sdk.ReflectionMethodInfo.Type.get() Line 71
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Reflection\ReflectionMethodInfo.cs(71)
xunit.core.dll!Xunit.Sdk.DataDiscoverer.GetData(Xunit.Abstractions.IAttributeInfo dataAttribute, Xunit.Abstractions.IMethodInfo testMethod) Line 32
	at C:\Dev\xunit\xunit\src\xunit.core\Sdk\DataDiscoverer.cs(32)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTheoryTestCaseRunner.AfterTestCaseStartingAsync() Line 92
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTheoryTestCaseRunner.cs(92)
xunit.execution.dotnet.dll!Xunit.Sdk.TestCaseRunner<Xunit.Sdk.IXunitTestCase>.RunAsync() Line 81
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestCaseRunner.cs(81)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTheoryTestCase.RunAsync(Xunit.Abstractions.IMessageSink diagnosticMessageSink, Xunit.Sdk.IMessageBus messageBus, object[] constructorArguments, Xunit.Sdk.ExceptionAggregator aggregator, System.Threading.CancellationTokenSource cancellationTokenSource) Line 51
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\XunitTheoryTestCase.cs(51)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTestMethodRunner.RunTestCaseAsync(Xunit.Sdk.IXunitTestCase testCase) Line 45
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestMethodRunner.cs(45)
xunit.execution.dotnet.dll!Xunit.Sdk.TestMethodRunner<Xunit.Sdk.IXunitTestCase>.RunTestCasesAsync() Line 136
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs(136)
xunit.execution.dotnet.dll!Xunit.Sdk.TestMethodRunner<Xunit.Sdk.IXunitTestCase>.RunAsync() Line 106
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestMethodRunner.cs(106)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTestClassRunner.RunTestMethodAsync(Xunit.Abstractions.ITestMethod testMethod, Xunit.Abstractions.IReflectionMethodInfo method, System.Collections.Generic.IEnumerable<Xunit.Sdk.IXunitTestCase> testCases, object[] constructorArguments) Line 168
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestClassRunner.cs(168)
xunit.execution.dotnet.dll!Xunit.Sdk.TestClassRunner<Xunit.Sdk.IXunitTestCase>.RunTestMethodsAsync() Line 213
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestClassRunner.cs(213)
xunit.execution.dotnet.dll!Xunit.Sdk.TestClassRunner<Xunit.Sdk.IXunitTestCase>.RunAsync() Line 171
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestClassRunner.cs(171)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTestCollectionRunner.RunTestClassAsync(Xunit.Abstractions.ITestClass testClass, Xunit.Abstractions.IReflectionTypeInfo class, System.Collections.Generic.IEnumerable<Xunit.Sdk.IXunitTestCase> testCases) Line 158
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestCollectionRunner.cs(158)
xunit.execution.dotnet.dll!Xunit.Sdk.TestCollectionRunner<Xunit.Sdk.IXunitTestCase>.RunTestClassesAsync() Line 130
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestCollectionRunner.cs(130)
xunit.execution.dotnet.dll!Xunit.Sdk.TestCollectionRunner<Xunit.Sdk.IXunitTestCase>.RunAsync() Line 101
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestCollectionRunner.cs(101)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionAsync(Xunit.Sdk.IMessageBus messageBus, Xunit.Abstractions.ITestCollection testCollection, System.Collections.Generic.IEnumerable<Xunit.Sdk.IXunitTestCase> testCases, System.Threading.CancellationTokenSource cancellationTokenSource) Line 235
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestAssemblyRunner.cs(235)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionsAsync.AnonymousMethod__2() Line 184
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestAssemblyRunner.cs(184)
System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.Threading.Tasks.Task<Xunit.Sdk.RunSummary>>.InnerInvoke() Line 503
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs(503)
System.Private.CoreLib.dll!System.Threading.Tasks.Task..cctor.AnonymousMethod__272_0(object obj) Line 2376
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2376)
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 183
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(183)
System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot, System.Threading.Thread threadPoolThread) Line 2333
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2333)
System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteEntry() Line 2253
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2253)
System.Private.CoreLib.dll!System.Threading.Tasks.SynchronizationContextTaskScheduler..cctor.AnonymousMethod__8_0(object s) Line 629
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskScheduler.cs(629)
xunit.execution.dotnet.dll!Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(System.Threading.SendOrPostCallback callback, object state) Line 107
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs(107)
xunit.execution.dotnet.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc.AnonymousMethod__0(object _) Line 96
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs(96)
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 183
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(183)
xunit.execution.dotnet.dll!Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc() Line 89
	at C:\Dev\xunit\xunit\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs(89)
xunit.execution.dotnet.dll!Xunit.Sdk.XunitWorkerThread.QueueUserWorkItem.AnonymousMethod__5_0(object _) Line 37
	at C:\Dev\xunit\xunit\src\common\XunitWorkerThread.cs(37)
System.Private.CoreLib.dll!System.Threading.Tasks.Task.InnerInvoke() Line 2397
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2397)
System.Private.CoreLib.dll!System.Threading.Tasks.Task..cctor.AnonymousMethod__272_0(object obj) Line 2376
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2376)
System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 183
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs(183)
System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot, System.Threading.Thread threadPoolThread) Line 2333
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2333)
System.Private.CoreLib.dll!System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread threadPoolThread) Line 2277
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(2277)
System.Private.CoreLib.dll!System.Threading.Tasks.ThreadPoolTaskScheduler..cctor.AnonymousMethod__10_0(object s) Line 36
	at /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ThreadPoolTaskScheduler.cs(36)
System.Private.CoreLib.dll!System.Threading.Thread.StartCallback() Line 105
	at /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs(105)

```</div>

**Comment by sdelarosbil** [comment]
Hey, is it possible to get a more precise way to reproduce this? I tried on my end with a simple theory with the same code provided, but the exception outputs correctly in the console runner. I wonder if it's more specific or if it has been fixed since.

**Comment by etherfield** [comment]
@sdelarosbil I've [reproduced](https://github.com/etherfield/case/tree/main/xunit/issue-2555/Net60TestProject) the issue with .NET 6.0, both Visual Studio and console runners, and xUnit 2.4.2.
Apparently, it's been fixed, because 2.5.0 returns ArgumentException which it's supposed to.

![1](https://github.com/xunit/xunit/assets/148793545/5baf9142-7ee8-4c38-9c50-58e5cb0b8b16)

**Comment by bradwilson** [comment]
Fixed in 2.5.0. 😄
