### ISSUE TITLE
Assert.Empty doesn't dispose the enumerator

### ISSUE THREAD

**Issue by AndriySvyryd** [xunit/xunit#2792]
```C#
[Fact]
public void Empty_disposes_enumerator()
{
    Assert.Throws<NotImplementedException>(() => Assert.Empty(new TestEnumerable()));
}

public class TestEnumerable : IEnumerable<object>
{
    private readonly Enumerator _enumerator = new();
    public IEnumerator<object> GetEnumerator() => _enumerator;
    IEnumerator IEnumerable.GetEnumerator() => _enumerator;

    public class Enumerator : IEnumerator<object>
    {
        public object Current => throw new NotImplementedException();

        public void Dispose() => throw new NotImplementedException();
        public bool MoveNext() => false;
        public void Reset() => throw new NotImplementedException();
    }
}
```

v2.5.1

**Comment by bradwilson** [comment]
Already fixed in `2.5.2-pre.6`.

Slightly updated source for clarity:

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using Xunit;

namespace Empty;

public class UnitTest
{
    [Fact]
    public void Property_throws_when_invoked_outside_of_query2()
    {
        Assert.Empty(new TestEnumerable());
    }

    public class TestEnumerable : IEnumerable<object?>
    {
        public IEnumerator<object?> GetEnumerator() => new Enumerator();
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

        public class Enumerator : IEnumerator<object?>
        {
            public object? Current => null;

            public void Dispose() => throw new DivideByZeroException();
            public bool MoveNext() => false;
            public void Reset() { }
        }
    }
}
```

Result:

```
xUnit.net Console Runner v2.5.2-pre.6+4d9d4fcc5d (64-bit .NET Framework 4.7.2, runtime: 4.0.30319.42000)
  Discovering: empty (app domain = on [shadow copy], method display = ClassAndMethod, method display options = None)
  Discovered:  empty (found 1 test case)
  Starting:    empty (parallel test collections = off, max threads = 24)
    Empty.UnitTest.Property_throws_when_invoked_outside_of_query2 [FAIL]
      System.DivideByZeroException : Attempted to divide by zero.
      Stack Trace:
        UnitTest.cs(25,0): at Empty.UnitTest.TestEnumerable.Enumerator.Dispose()
        UnitTest.cs(13,0): at Empty.UnitTest.Property_throws_when_invoked_outside_of_query2()
  Finished:    empty
=== TEST EXECUTION SUMMARY ===
   empty  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 0.285s
```
