### ISSUE TITLE
Issue with `TestFrameworkExecutor` on .NET Core

### ISSUE THREAD

**Issue by Alxandr** [xunit/xunit#289]
I'm trying to run tests on .NET Core, and I get the following exception:

```
System.NotSupportedException: Assembly.Load with a Codebase is not supported on Windows Phone.
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Xunit.Sdk.TestFrameworkExecutor`1..ctor(AssemblyName assemblyName, ISourceInformationProvider sourceInformationProvider) in C:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.execution\Sdk\Frameworks\TestFrameworkExecutor.cs:line 28
   at Xunit.Sdk.XunitTestFrameworkExecutor..ctor(AssemblyName assemblyName, ISourceInformationProvider sourceInformationProvider) in C:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 20
   at Xunit.Sdk.XunitTestFramework.CreateExecutor(AssemblyName assemblyName) in C:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.execution\Sdk\Frameworks\XunitTestFramework.cs:line 21
   at Xunit.Sdk.TestFramework.GetExecutor(AssemblyName assemblyName) in C:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.execution\Sdk\Frameworks\TestFramework.cs:line 70 
   at Xunit.Sdk.TestFrameworkProxy.GetExecutor(AssemblyName assemblyName) in C:\TeamCity\buildAgent\work\74856245f07a90f0\src\xunit.execution\Sdk\Frameworks\TestFrameworkProxy.cs:line 81
   at YoloDev.Xunit.Program.RunTests(TestOptions options, ITestFramework framework, AssemblyName assemblyName, IServiceProvider services) in C:\projects\yolodev-xunit\src\YoloDev.Xunit\Program.cs:line 221
   at YoloDev.Xunit.Program.RunTestAssembly(TestOptions options, String testTarget, IAssemblyLoaderContainer container, IServiceProvider services) in C:\projects\yolodev-xunit\src\YoloDev.Xunit\Program.cs:line 200
   at YoloDev.Xunit.Program.RunTests(TestOptions options) in C:\projects\yolodev-xunit\src\YoloDev.Xunit\Program.cs:line 151
   at YoloDev.Xunit.Program.Main(String[] args) in C:\projects\yolodev-xunit\src\YoloDev.Xunit\Program.cs:line 53
```

The problem is probably that `Assembly.Load` is called with the wrong argument. The ifdef probably needs to be amended.

**Comment by bradwilson** [comment]
xUnit.net does not at this time have any direct support for .NET Core. The only .NET Core support that it does have is related to ASP.NET 5. We will need to add explicit support for .NET Core if it will be supported differently from the way ASP.NET 5 works.

**Comment by Alxandr** [comment]
I am running this from ASP.NET 5. And it is failing.

**Comment by bradwilson** [comment]
Is this a result of `k test`? I've never seen this before, and the error message seems unexpected.

**Comment by Alxandr** [comment]
Yes I am running `k test`, but I am not running the `xunit.aspnet` runner. I am trying to make my own, due to numerous problems with the one provided. Such as no support for other CI environments than TeamCity.

The problem occurs [here](https://github.com/xunit/xunit/blob/master/src/xunit.execution/Sdk/Frameworks/TestFrameworkExecutor.cs#L28), and the solution is probably a simple change in the `#ifdef` to include `aspnetcore50`. The error message is probably a simple bug in the Core CLR where they have yet to convert all error messages. https://github.com/dotnet/coreclr/blob/cbf46fb0b6a0b209ed1caf4a680910b383e68cba/src/mscorlib/src/mscorlib.txt#L1476

**Comment by bradwilson** [comment]
I don't know what to say, other than our ASP.NET runner (https://github.com/xunit/aspnet.xunit) does run on both 32- and 64-bit versions of the desktop CLR and the core CLR. It's hard for me to guess what's different about your runner without being able to see the source code.

**Comment by Alxandr** [comment]
It's open source. Error occurs here: https://github.com/YoloDev/YoloDev.Testing/blob/master/src/YoloDev.Xunit/Program.cs#L221

**Comment by bradwilson** [comment]
You should try using the FrontController instead of using Activate.CreateInstance.

https://github.com/xunit/aspnet.xunit/blob/master/src/xunit.runner.aspnet/Program.cs#L294

**Comment by Alxandr** [comment]
Interestingly enough, doing so reduced it from one working framework to no working frameworks. And it doesn't even give an exception. Something goes wrong when it tries to create the reflection-based `IAssemblyInfo`, and it resolves the wrong assembly. See image below:

![image](https://cloud.githubusercontent.com/assets/112334/6102549/ae47b3be-b038-11e4-953c-a2b457eb9325.png)
