### ISSUE TITLE
Generic methods with nullables uses non-nullable internal type

### ISSUE THREAD

**Issue by Clockwork-Muse** [xunit/xunit#296]
Using nullable types (like `int?`) as a subordinate generic type makes the test runner attempt to use the non-nullable base type instead.  That is, this:

    public static IEnumerable<object[]> NullableData()
    {
        yield return new object[] { Enumerable.Empty<int?>(), new Nullable<int>(1) };
    }

    [Theory]
    [MemberData("NullableData")]
    public static void NullableTest<T>(IEnumerable<T> e, T item)
    {
        Assert.Single(e, item);
        Assert.Single(e, n => n.Equals(item));
    }

yields the following stack trace:

> Result Message:	System.ArgumentException : Object of type 'System.Nullable`1[System.Int32][]' cannot be converted to type 'System.Collections.Generic.IEnumerable`1[System.Int32]'.
Result StackTrace:	
at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

This is on the prior beta builds, given the RC build currently isn't running.

**Comment by bradwilson** [comment]
You're about to discover a very uncomfortable truth about runtime type detection: nullable is a Heisen-type. It is purely a compiler-type fiction that does not exist in the runtime once the thing gets boxed.

If you have a `Nullable<int>`, and it's non-`null`, then when it's boxed (converted to an `object`), the boxed value is the raw `int`. Its nullable heritage is thrown away. If the value is `null`, then when it's boxed, it simply becomes a `null` object. Not only is the `Nullable<T>` thrown away here, so is the `T`. Since xUnit.net only deals in terms of `object`, there is absolutely now way to know that the `1` you're handing it started life as a `Nullable<int>`. It just knows that *right now*, it's a plain old `int`.

This behavior, while counter-intuitive, is dictated by the CLR.

For more information:
http://bradwilson.typepad.com/blog/2008/07/creating-nullab.html
https://msdn.microsoft.com/en-us/library/ms366789(VS.80).aspx

**Comment by Clockwork-Muse** [comment]
...well okay then.
