### ISSUE TITLE
Xunit 2.8.1 causes tests skipped from fixtures to be treated as failures

### ISSUE THREAD

**Issue by adamreeve** [xunit/xunit#2965]
Test class:
```c#
using Xunit;

namespace XunitTest;

public class UnitTest1 : IClassFixture<UnitTest1.MyFixture>
{
    class MyFixture
    {
        public MyFixture()
        {
            bool runTests = false;
            Skip.If(!runTests, "Skipping");
        }
    }

    [SkippableFact]
    public void Test1()
    {
        Assert.Equal(1, 1);
    }
}
```

csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />
    <PackageReference Include="xunit" Version="2.8.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.skippablefact" Version="1.4.13" />
  </ItemGroup>

</Project>
```

With Xunit 2.8.0, running `dotnet test` gives:
```
$ dotnet test
  Determining projects to restore...
  Restored /home/adam/dev/tmp/XunitTest/XunitTest.csproj (in 196 ms).
  XunitTest -> /home/adam/dev/tmp/XunitTest/bin/Debug/net8.0/XunitTest.dll
Test run for /home/adam/dev/tmp/XunitTest/bin/Debug/net8.0/XunitTest.dll (.NETCoreApp,Version=v8.0)
Microsoft (R) Test Execution Command Line Tool Version 17.8.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.12]     XunitTest.UnitTest1.Test1 [SKIP]
  Skipped XunitTest.UnitTest1.Test1 [1 ms]

Skipped! - Failed:     0, Passed:     0, Skipped:     1, Total:     1, Duration: < 1 ms - XunitTest.dll (net8.0)
```

With 2.8.1 I get:
```
$ dotnet test
  Determining projects to restore...
  Restored /home/adam/dev/tmp/XunitTest/XunitTest.csproj (in 211 ms).
  XunitTest -> /home/adam/dev/tmp/XunitTest/bin/Debug/net8.0/XunitTest.dll
Test run for /home/adam/dev/tmp/XunitTest/bin/Debug/net8.0/XunitTest.dll (.NETCoreApp,Version=v8.0)
Microsoft (R) Test Execution Command Line Tool Version 17.8.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
[xUnit.net 00:00:00.13]     XunitTest.UnitTest1.Test1 [FAIL]
  Failed XunitTest.UnitTest1.Test1 [1 ms]
  Error Message:
   Class fixture type 'XunitTest.UnitTest1+MyFixture' threw in its constructor
---- Xunit.SkipException : Skipping
  Stack Trace:
  
----- Inner Stack Trace -----
   at XunitTest.UnitTest1.MyFixture..ctor() in /home/adam/dev/tmp/XunitTest/UnitTest1.cs:line 12
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: < 1 ms - XunitTest.dll (net8.0)
```

**Comment by bradwilson** [comment]
Since this isn't our feature, you should open this issue against SkippableFact.

**Comment by bradwilson** [comment]
To add additional information:

Throwing in a fixture and having that exception "propagate" down into the test was never an intentional feature. What you're running into is us adding clarity for throwing fixtures in 2.8.1: https://github.com/xunit/xunit/issues/2927

**Comment by bradwilson** [comment]
For what it's worth, your test would've failed in 2.8.0 as well if you'd taken the fixture as a constructor argument. The fact that you didn't is what let the error fall through and get ignored:

![image](https://github.com/xunit/xunit/assets/16944/97f096e5-2233-4457-b86b-f1e2ce2dfd13)

**Comment by bradwilson** [comment]
At this point I'm willing to say that this probably isn't a bug in SkippableFact, but rather a misunderstanding (and unintentional bug related to) exception handling with fixture construction. This should've never worked. If there is a suggestion in SkippableFact's documentation that it should work, then that's probably the only bug that needs to be fixed.
