### ISSUE TITLE
Struct with self-referencing `ImmutableArray` static field produces `TypeLoadException` and fails tests

### ISSUE THREAD

**Issue by JakeYallop** [xunit/xunit#2970]
### Reproduction steps
```
dotnet new xunit
```
Update packages to latest versions (2.8.1 currently), then enter the following:

```csharp
public class UnitTest1
{
    [Fact]
    public void Test1() { }
}

public struct MyStruct
{
    static ImmutableArray<MyStruct> One;
}
```
Then, run `dotnet test`
```
XunitLoadFailiureRepro succeeded (0.1s) → XunitLoadFailiureRepro\bin\Debug\net8.0\XunitLoadFailiureRepro.dll
  XunitLoadFailiureRepro test succeeded with 2 warning(s) (0.4s)
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): warning :
      [xUnit.net 00:00:00.03] Exception discovering tests from XunitLoadFailiureRepro: System.TypeLoadException: Could not load type 'XunitLoadFailiureRepro.MyStruct' from assembly 'XunitLoadFailiureRepro, Version=1.0.0.0, Culture=neutral, Pu
      blicKeyToken=null'.
         at System.Reflection.RuntimeAssembly.GetExportedTypes()
         at Xunit.Sdk.ReflectionAssemblyInfo.GetTypes(Boolean includePrivateTypes) in /_/src/xunit.execution/Sdk/Reflection/ReflectionAssemblyInfo.cs:line 80
         at Xunit.Sdk.TestCollectionFactoryHelper.GetTestCollectionDefinitions(IAssemblyInfo assemblyInfo, IMessageSink diagnosticMessageSink) in /_/src/xunit.execution/Sdk/Frameworks/TestCollectionFactoryHelper.cs:line 22
         at Xunit.Sdk.CollectionPerClassTestCollectionFactory..ctor(ITestAssembly testAssembly, IMessageSink diagnosticMessageSink) in /_/src/xunit.execution/Sdk/Frameworks/CollectionPerClassTestCollectionFactory.cs:line 27
         at Xunit.Sdk.ExtensibilityPointFactory.GetXunitTestCollectionFactory(IMessageSink diagnosticMessageSink, IAttributeInfo collectionBehaviorAttribute, ITestAssembly testAssembly) in /_/src/xunit.execution/Sdk/ExtensibilityPointFactory.
      cs:line 245
         at Xunit.Sdk.XunitTestFrameworkDiscoverer..ctor(IAssemblyInfo assemblyInfo, ISourceInformationProvider sourceProvider, IMessageSink diagnosticMessageSink, IXunitTestCollectionFactory collectionFactory) in /_/src/xunit.execution/Sdk/F
      rameworks/XunitTestFrameworkDiscoverer.cs:line 45
         at Xunit.Sdk.XunitTestFramework.CreateDiscoverer(IAssemblyInfo assemblyInfo) in /_/src/xunit.execution/Sdk/Frameworks/XunitTestFramework.cs:line 21
         at Xunit.Sdk.TestFramework.GetDiscoverer(IAssemblyInfo assemblyInfo) in /_/src/xunit.execution/Sdk/Frameworks/TestFramework.cs:line 71
         at Xunit.Sdk.TestFrameworkProxy.GetDiscoverer(IAssemblyInfo assembly) in /_/src/xunit.execution/Sdk/Frameworks/TestFrameworkProxy.cs:line 68
         at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, B
      oolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk) in /_/src/xunit.runner.utility/Frameworks/v2/Xunit2Discoverer.cs:line 107
         at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagno
      sticMessageSink, Boolean verifyAssembliesOnDisk) in /_/src/xunit.runner.utility/Frameworks/v2/Xunit2Discoverer.cs:line 63
         at Xunit.Xunit2..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessag
      eSink, Boolean verifyTestAssemblyExists) in /_/src/xunit.runner.utility/Frameworks/v2/Xunit2.cs:line 41
         at Xunit.XunitFrontController.CreateInnerController() in /_/src/xunit.runner.utility/Frameworks/XunitFrontController.cs:line 134
         at Xunit.XunitFrontController.EnsureInitialized() in /_/src/xunit.runner.utility/Frameworks/XunitFrontController.cs:line 153
         at Xunit.XunitFrontController.get_InnerController() in /_/src/xunit.runner.utility/Frameworks/XunitFrontController.cs:line 93
         at Xunit.XunitFrontController.get_CanUseAppDomains() in /_/src/xunit.runner.utility/Frameworks/XunitFrontController.cs:line 78
         at Xunit.Runner.VisualStudio.VsTestRunner.DiscoverTestsInSource[TVisitor](XunitFrontController controller, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, Func`4 visitorFactory, Action`4 visitCo
      mplete, XunitProjectAssembly assembly) in /_/src/xunit.runner.visualstudio/VsTestRunner.cs:line 290
    C:\Program Files\dotnet\sdk\9.0.100-preview.5.24307.3\Microsoft.TestPlatform.targets(46,5): warning : No test is available in C:\Workspaces\XunitLoadFailiureRepro\XunitLoadFailiureRepro\bin\Debug\net8.0\XunitLoadFailiureRepro.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

### Other information
In the process of trying to figure out what issue was crashing my tests, I also tried `net9.0` (Preview 5),  xunit v3, the latest prelease versions of xunit v2 on the package feed, and some older versions of xunit and the `Microsoft.NET.Test.Sdk` (just in case), but I was still able to reproduce this issue.

For the `TypeLoadException` to occur, it must be a struct with a static field `ImmutableArray` of the enclosing struct. The following struct works just fine:
```csharp
// this works without any issues, no `static` modifier
public struct MyStruct
{
    ImmutableArray<MyStruct> One;
}
```

**Comment by bradwilson** [comment]
We could handle this more gracefully, but we're not the cause of the problem, so there is no way for me to fix it.

If you eliminate us entirely and just create a .NET 8 console app, you have the same problem:

![image](https://github.com/xunit/xunit/assets/16944/14651545-3b01-429e-9c6b-521b160b9707)

It would be worth opening an issue against .NET to get someone to explain to you why that type is not legal, because spending 20 minutes with the source to `ImmutableArray<>` did not yield any obvious clues to me. If I had to guess, I'd put 6 to 5 odds on the problem being one of the system not knowing how to lay out the memory for your struct correctly.

**Comment by JakeYallop** [comment]
That's interesting - I did initially assume it was a .NET issue, in my testing I ran a console app with this struct in it, but I didn't instantiate the struct! When actually creating the struct, I get the same result as you on both .NET 8 and 9 Preview 5.

I'll definitely open an issue in runtime for this.

**Comment by JakeYallop** [comment]
Opened https://github.com/dotnet/runtime/issues/104519
