### ISSUE TITLE
Issue Filtering By Trait in Xunit.v3

### ISSUE THREAD

**Issue by justindbaur** [xunit/xunit#3030]
I'm running into an issue while using `dotnet test` and including a `--filter MyTrait=One` to filter by only tests with a given. A minimally reproducible build for what I was going for is [here](https://github.com/justindbaur/xunit-v3-problem). But technically a custom `DataAttribute` isn't needed at all. You can recreate this with just the default template created with `dotnet new xunit3` and then pretending you have tests with a trait by adding the above filter.

The error I get is:

```
[xUnit.net 00:00:00.19] xunit-v3-problem: Catastrophic failure: System.ArgumentException: Argument was empty (Parameter 'settings.SerializedTestCases')
   at Xunit.Internal.Guard.ArgumentNotNullOrEmpty[T](T argValue, String argName)
   at Xunit.Runner.v3.Xunit3.Run(IMessageSink messageSink, FrontControllerRunSettings settings)
   at Xunit.XunitFrontController.Run(IMessageSink messageSink, FrontControllerRunSettings settings)
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, IMessageSink reporterMessageHandler, AssemblyRunInfo runInfo)
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, IMessageSink reporterMessageHandler, AssemblyRunInfo runInfo)
   at Xunit.Runner.VisualStudio.VsTestRunner.RunTestsInAssembly(IRunContext runContext, IFrameworkHandle frameworkHandle, LoggerHelper logger, TestPlatformContext testPlatformContext, RunSettings runSettings, IMessageSink reporterMessageHandler, AssemblyRunInfo runInfo)
```

Thank you so much for the work on v3, all the new goodies are very useful!

**Comment by bradwilson** [comment]
Dup of https://github.com/xunit/visualstudio.xunit/issues/417
