### ISSUE TITLE
xUnit v3 failed to run tests when stdout is captured and ANSI escape sequence exists

### ISSUE THREAD

**Issue by filzrev** [xunit/xunit#3091]
xUnit v3 failed to execute tests when following conditions met. 

1. There is  code that write ANSI escape sequence (e.g. `\u001B`) to stdout.
2. Using MicrosoftTestingPlatform test runner.
3. Capture console feature is enabled by setting `[assembly: CaptureConsole]`.
4. Any of test reporter is configured.

**How to reproduce problems**

1. Create xUnit v3 test project with `dotnet new xunit3` command
2. Enable `UseMicrosoftTestingPlatformRunner` to use MicrosoftTestingPlatform Main entry point.
3. Enable Capture console by setting `[assembly: CaptureConsole]`.
4. Add following code to test.
    > `Console.WriteLine("\u001B[31mred text");`
6. Run test exe with `--report-xunit-html` argument
7. Test execution failed and following stack trace is shown.

```
System.ArgumentException: 'exadecimal value 0x1B, is an invalid character.
   at System.Xml.XmlUtf8RawTextWriter.InvalidXmlChar(Int32 ch, Byte* pDst, Boolean entitize)
   at System.Xml.XmlUtf8RawTextWriter.WriteElementTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at <xsl:template match="test">(XmlQueryRuntime, XPathNavigator, Double)
   at <xsl:template name="compiler:generated"> (5)(XmlQueryRuntime, XPathNavigator)
   at <xsl:template match="/">(XmlQueryRuntime, XPathNavigator)
   at Root(XmlQueryRuntime)
   at System.Xml.Xsl.XmlILCommand.Execute(Object defaultDocument, XmlResolver dataSources, XsltArgumentList argumentList, XmlWriter writer)
   at System.Xml.Xsl.XslCompiledTransform.Transform(XmlReader input, XmlWriter results)
   at Xunit.Runner.Common.TransformFactory.Handler_XslTransform(String resourceName, XElement xml, String outputFileName) in D:\a\xunit\xunit\src\xunit.v3.runner.common\Transforms\TransformFactory.cs:line 439
   at Xunit.Runner.Common.TransformFactory.<>c.<.ctor>b__2_1(XElement xml, String outputFileName) in D:\a\xunit\xunit\src\xunit.v3.runner.common\Transforms\TransformFactory.cs:line 46
   at Xunit.Runner.Common.TransformFactory.<>c__DisplayClass7_0.<GetXmlTransformers>b__1(XElement xml) in D:\a\xunit\xunit\src\xunit.v3.runner.common\Transforms\TransformFactory.cs:line 152
   at Xunit.Runner.InProc.SystemConsole.ProjectAssemblyRunner.<>c__DisplayClass14_2.<Run>b__6(Action`1 transformer) in D:\a\xunit\xunit\src\xunit.v3.runner.inproc.console\Utility\ProjectAssemblyRunner.cs:line 331
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Xunit.Runner.InProc.SystemConsole.ProjectAssemblyRunner.Run(XunitProjectAssembly assembly, IMessageSink messageSink, IMessageSink diagnosticMessageSink, IRunnerLogger runnerLogger, ITestPipelineStartup pipelineStartup, HashSet`1 testCaseIDsToRun) in D:\a\xunit\xunit\src\xunit.v3.runner.inproc.console\Utility\ProjectAssemblyRunner.cs:line 331
   at Xunit.Runner.InProc.SystemConsole.TestingPlatform.TestPlatformTestFramework.<>c__DisplayClass17_0.<<OnExecute>b__0>d.MoveNext() in D:\a\xunit\xunit\src\xunit.v3.runner.inproc.console\TestingPlatform\TestPlatformTestFramework.cs:line 159
--- End of stack trace from previous location ---
   at Xunit.Runner.InProc.SystemConsole.TestingPlatform.TestPlatformTestFramework.OnRequest(SessionUid sessionUid, Action operationComplete, Func`3 callback, CancellationToken cancellationToken) in D:\a\xunit\xunit\src\xunit.v3.runner.inproc.console\TestingPlatform\TestPlatformTestFramework.cs:line 186
   at Xunit.Runner.InProc.SystemConsole.TestingPlatform.TestPlatformTestFramework.OnRequest(SessionUid sessionUid, Action operationComplete, Func`3 callback, CancellationToken cancellationToken) in D:\a\xunit\xunit\src\xunit.v3.runner.inproc.console\TestingPlatform\TestPlatformTestFramework.cs:line 192
   at Xunit.Runner.InProc.SystemConsole.TestingPlatform.TestPlatformTestFramework.Microsoft.Testing.Platform.Extensions.TestFramework.ITestFramework.ExecuteRequestAsync(ExecuteRequestContext context) in D:\a\xunit\xunit\src\xunit.v3.runner.inproc.console\TestingPlatform\TestPlatformTestFramework.cs:line 115
   at Microsoft.Testing.Platform.Requests.TestHostTestFrameworkInvoker.ExecuteRequestAsync(ITestFramework testFramework, TestExecutionRequest request, IMessageBus messageBus, CancellationToken cancellationToken) in /_/src/Platform/Microsoft.Testing.Platform/Requests/TestHostTestFrameworkInvoker.cs:line 73
   at Microsoft.Testing.Platform.Requests.TestHostTestFrameworkInvoker.ExecuteAsync(ITestFramework testFramework, ClientInfo client, CancellationToken cancellationToken) in /_/src/Platform/Microsoft.Testing.Platform/Requests/TestHostTestFrameworkInvoker.cs:line 62
   at Microsoft.Testing.Platform.Hosts.CommonTestHost.ExecuteRequestAsync(IPlatformOutputDevice outputDevice, ITestSessionContext testSessionInfo, ServiceProvider serviceProvider, BaseMessageBus baseMessageBus, ITestFramework testFramework, ClientInfo client) in /_/src/Platform/Microsoft.Testing.Platform/Hosts/CommonTestHost.cs:line 111
   at Microsoft.Testing.Platform.Hosts.ConsoleTestHost.InternalRunAsync() in /_/src/Platform/Microsoft.Testing.Platform/Hosts/ConsoleTestHost.cs:line 84
   at Microsoft.Testing.Platform.Hosts.ConsoleTestHost.InternalRunAsync() in /_/src/Platform/Microsoft.Testing.Platform/Hosts/ConsoleTestHost.cs:line 116
   at Microsoft.Testing.Platform.Hosts.CommonTestHost.RunTestAppAsync(CancellationToken testApplicationCancellationToken) in /_/src/Platform/Microsoft.Testing.Platform/Hosts/CommonTestHost.cs:line 85
   at Microsoft.Testing.Platform.Hosts.CommonTestHost.RunAsync() in /_/src/Platform/Microsoft.Testing.Platform/Hosts/CommonTestHost.cs:line 33
   at Microsoft.Testing.Platform.Hosts.CommonTestHost.RunAsync() in /_/src/Platform/Microsoft.Testing.Platform/Hosts/CommonTestHost.cs:line 56
   at Microsoft.Testing.Platform.Builder.TestApplication.RunAsync() in /_/src/Platform/Microsoft.Testing.Platform/Builder/TestApplication.cs:line 240
   at Xunit.Runner.InProc.SystemConsole.TestingPlatform.TestPlatformTestFramework.RunAsync(String[] args, Action`2 extensionRegistration) in D:\a\xunit\xunit\src\xunit.v3.runner.inproc.console\TestingPlatform\TestPlatformTestFramework.cs:line 270
   at XunitAutoGeneratedEntryPoint.Main(String[] args) in C:\Users\admin\.nuget\packages\xunit.v3.core\1.0.0\_content\EntryPoint-mtp.cs:line 11
```

**Comment by bradwilson** [comment]
Fix available in `1.0.1-pre.8` https://xunit.net/docs/using-ci-builds
