### ISSUE TITLE
Xunit and "missing assembly" tests

### ISSUE THREAD

**Issue by AArnott** [xunit/xunit#327]
I have some tests that explicitly test my product in the scenario of a missing assembly. Xunit unfortunately produces a failure as a result of this condition. Besides spewing a bunch of errors, it returns a nonzero result code leading to my CI build thinking the test run was a failure.

Is there a way to configure Xunit to swallow these errors as if they were expected?

    2015-02-27T02:41:44.5630362Z Starting test execution, please wait...
    2015-02-27T02:41:51.1255178Z [Error][Error]Error: [xUnit.net 00:00:00.5936751] Exception discovering tests from f:\vnext1\b25bab26\VSIDEProj.MEF\bin\Debug\NonShipping\Microsoft.VisualStudio.Composition.AssemblyDiscoveryTests.dll: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Composition.MissingAssemblyTests, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    2015-02-27T02:41:51.1255178Z [Error][Error]File name: 'Microsoft.VisualStudio.Composition.MissingAssemblyTests, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
    2015-02-27T02:41:51.1255178Z [Error][Error]   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at System.Reflection.CustomAttribute.IsDefined(RuntimeType type, RuntimeType caType, Boolean inherit)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at System.RuntimeType.IsDefined(Type attributeType, Boolean inherit)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at Xunit.Sdk.Reflector.ReflectionTypeInfo.HasAttribute(Type attributeType)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at Xunit.Sdk.TypeUtility.HasRunWith(ITypeInfo type)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at Xunit.Sdk.TypeUtility.IsTestClass(ITypeInfo type)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at Xunit.Sdk.TestClassCommandFactory.Make(ITypeInfo typeInfo)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at Xunit.Sdk.TestClassCommandFactory.Make(Type type)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at Xunit.Sdk.Executor.EnumerateTests..ctor(Executor executor, Object _handler)$$RethrowMarker$$   at ExceptionExtensions.RethrowWithNoStackTraceLoss(Exception ex)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at Xunit.RemoteAppDomainManager.CreateObject[TObject](String assemblyName, String typeName, Object[] args)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at Xunit.Xunit1Executor.CreateObject(String typeName, Object[] args)
    2015-02-27T02:41:51.1255178Z [Error][Error]   at Xunit.Xunit1Executor.EnumerateTests(ICallbackEventHandler handler)
    2015-02-27T02:41:51.1411423Z [Error][Error]   at Xunit.Xunit1.Find(Predicate`1 filter, Boolean includeSourceInformation, IMessageSink messageSink)
    2015-02-27T02:41:51.1411423Z [Error][Error]   at Xunit.Xunit1.Find(Boolean includeSourceInformation, IMessageSink messageSink)
    2015-02-27T02:41:51.1411423Z [Error][Error]   at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink)
    2015-02-27T02:41:51.1411423Z [Error][Error]   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetTests(IEnumerable`1 sources, IMessageLogger logger, XunitVisualStudioSettings settings, Stopwatch stopwatch)
    2015-02-27T02:41:51.1411423Z [Error][Error]WRN: Assembly binding logging is turned OFF.
    2015-02-27T02:41:51.1411423Z [Error][Error]To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
    2015-02-27T02:41:51.1411423Z [Error][Error]Note: There is some performance penalty associated with assembly bind failure logging.
    2015-02-27T02:41:51.1411423Z [Error][Error]To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
    2015-02-27T02:41:51.2505189Z [Error][Error]Error: [xUnit.net 00:00:00.7556778] Exception discovering tests from f:\vnext1\b25bab26\VSIDEProj.MEF\bin\Debug\NonShipping\Microsoft.VisualStudio.Composition.BrokenAssemblyTests.dll: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Composition.MissingAssemblyTests, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    2015-02-27T02:41:51.2505189Z [Error][Error]File name: 'Microsoft.VisualStudio.Composition.MissingAssemblyTests, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
    2015-02-27T02:41:51.2661436Z [Error][Error]   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
    2015-02-27T02:41:51.2661436Z [Error][Error]   at System.Reflection.RuntimeAssembly.GetExportedTypes()
    2015-02-27T02:41:51.2661436Z [Error][Error]   at Xunit.Sdk.Executor.EnumerateTests..ctor(Executor executor, Object _handler)$$RethrowMarker$$   at ExceptionExtensions.RethrowWithNoStackTraceLoss(Exception ex)
    2015-02-27T02:41:51.2661436Z [Error][Error]   at Xunit.RemoteAppDomainManager.CreateObject[TObject](String assemblyName, String typeName, Object[] args)
    2015-02-27T02:41:51.2661436Z [Error][Error]   at Xunit.Xunit1Executor.CreateObject(String typeName, Object[] args)
    2015-02-27T02:41:51.2661436Z [Error][Error]   at Xunit.Xunit1Executor.EnumerateTests(ICallbackEventHandler handler)
    2015-02-27T02:41:51.2661436Z [Error][Error]   at Xunit.Xunit1.Find(Predicate`1 filter, Boolean includeSourceInformation, IMessageSink messageSink)
    2015-02-27T02:41:51.2661436Z [Error][Error]   at Xunit.Xunit1.Find(Boolean includeSourceInformation, IMessageSink messageSink)
    2015-02-27T02:41:51.2661436Z [Error][Error]   at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink)
    2015-02-27T02:41:51.2661436Z [Error][Error]   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetTests(IEnumerable`1 sources, IMessageLogger logger, XunitVisualStudioSettings settings, Stopwatch stopwatch)
    2015-02-27T02:41:51.2661436Z [Error][Error]WRN: Assembly binding logging is turned OFF.
    2015-02-27T02:41:51.2661436Z [Error][Error]To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
    2015-02-27T02:41:51.2661436Z [Error][Error]Note: There is some performance penalty associated with assembly bind failure logging.
    2015-02-27T02:41:51.2661436Z [Error][Error]To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
    2015-02-27T02:41:54.9067914Z [Error][Error]Error: [xUnit.net 00:00:04.3982935] Exception discovering tests from f:\vnext1\b25bab26\VSIDEProj.MEF\bin\Debug\NonShipping\xunit.runner.visualstudio.testadapter.dll: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    2015-02-27T02:41:54.9067914Z [Error][Error]File name: 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
    2015-02-27T02:41:54.9067914Z [Error][Error]File name: 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
    2015-02-27T02:41:54.9067914Z [Error][Error]WRN: Assembly binding logging is turned OFF.
    2015-02-27T02:41:54.9067914Z [Error][Error]To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
    2015-02-27T02:41:54.9067914Z [Error][Error]Note: There is some performance penalty associated with assembly bind failure logging.
    2015-02-27T02:41:54.9067914Z [Error][Error]To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
    2015-02-27T02:41:54.9067914Z [Error][Error]   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
    2015-02-27T02:41:54.9067914Z [Error][Error]   at System.Reflection.RuntimeAssembly.GetExportedTypes()
    2015-02-27T02:41:54.9067914Z [Error][Error]   at Xunit.Sdk.Executor.EnumerateTests..ctor(Executor executor, Object _handler)$$RethrowMarker$$   at ExceptionExtensions.RethrowWithNoStackTraceLoss(Exception ex)
    2015-02-27T02:41:54.9067914Z [Error][Error]   at Xunit.RemoteAppDomainManager.CreateObject[TObject](String assemblyName, String typeName, Object[] args)
    2015-02-27T02:41:54.9067914Z [Error][Error]   at Xunit.Xunit1Executor.CreateObject(String typeName, Object[] args)
    2015-02-27T02:41:54.9067914Z [Error][Error]   at Xunit.Xunit1Executor.EnumerateTests(ICallbackEventHandler handler)
    2015-02-27T02:41:54.9067914Z [Error][Error]   at Xunit.Xunit1.Find(Predicate`1 filter, Boolean includeSourceInformation, IMessageSink messageSink)
    2015-02-27T02:41:54.9067914Z [Error][Error]   at Xunit.Xunit1.Find(Boolean includeSourceInformation, IMessageSink messageSink)
    2015-02-27T02:41:54.9067914Z [Error][Error]   at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink)
    2015-02-27T02:41:54.9067914Z [Error][Error]   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.GetTests(IEnumerable`1 sources, IMessageLogger logger, XunitVisualStudioSettings settings, Stopwatch stopwatch)

**Comment by bradwilson** [comment]
Given that you have a hard linked dependency against a missing assembly, there's really nothing we're going to be able to do about that. It's breaking us long before we're able to do anything useful.

**Comment by AArnott** [comment]
I was hoping xunit could catch the exception thrown while performing reflection and simply move on as if the attribute/base type, etc whatever you were looking for wasn't what you were looking for.

**Comment by bradwilson** [comment]
I'll see what we can do.

**Comment by bradwilson** [comment]
We just realized that you're using xUnit.net v1 tests. To fix this would require revving the xUnit.net v1 DLLs, which we are not planning to do.

If this problem also occurs in v2, we would be happy to fix it there. Please re-open if you have a v2-based repro.

**Comment by AArnott** [comment]
Fair enough. I'll try to port to xunit2 for this project. I've been meaning to anyway.
