### ISSUE TITLE
[InlineData] does not convert arrays to IEnumerable<T> parameter types in v2

### ISSUE THREAD

**Issue by pjmonks** [xunit/xunit#428]
When using xUnit 1.9 I had theories that looked similar to this:

    [Theory]
    [InlineData(new int[] { 1, 2, 3 }, new int[] { 1, 2, 3, 4, 5, 6 })]            
    public void MyTest(IEnumerable<int> input, IEnumerable<int> expected)
    {
        IEnumerable<int> actual = SomeOperation(input);
        Assert.Equal(expected, actual);
    }

These would run just fine and the `[InlineData]` attribute would automatically convert the `int[]` type (which is what C# attributes allow) to the `IEnumerable<int>` type on the method parameter.

Now I am upgrading to v2.0 I'm finding that all of these tests now fail because `[InlineData]` does not seem to be doing this type conversion anymore. Here is the error I'm getting from both the console runner and VS test runner:

    System.ArgumentException : Object of type 'System.Object[]' cannot be converted to type 'System.Collections.Generic.IEnumerable`1[System.Int32]'.
    Result StackTrace:	
    at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
       at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
       at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
       at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
       at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

The workaround is to change my tests so the method parameters are exactly the same as those in the `[InlineData]` attribute but this seems to be a breaking change for some reason.

**Comment by Galad** [comment]
Hello,
It looks like the same issue as #425 and could be fixed by my pull request.

**Comment by bradwilson** [comment]
I have verified that 6456ebdae9c4e825852bd28cb81e1dfd342fd63b does indeed fix this issue.
