### ISSUE TITLE
Teamcity + MSBuild -- can't find xunit DLLs, but tests pass?

### ISSUE THREAD

**Issue by SeanKilleen** [xunit/xunit#446]
(I think this qualifies as a potential issue so I wrote it up here. Let me know if it belongs more on StackOverflow.)

Hi all,

Digging into this still but have been stumped on it for a while.

## Summary
In TeamCity, with xUnit configured via MSBuild, I see `Tests Passed: 18; exit code 1` with a failing build that appears as if xUnit can't find a DLL it needs.

The error:

> System.ArgumentException: Unknown test framework: Could not find xunit.dll or xunit.execution.desktop.dll.

## The Components
* TeamCity 9.0.4, hosted on a windows box.
* A solution with 4 .NET 4.5.1 class libraries and their associated test projects.
* An MSBuild file specifically for tests.
* All test projects have the following packages (no pre-release):
 * Moq
 * FluentAssertions
 * xunit
 * xunit.abstractions
 * xunit.assert
 * xunit.core
 * xunit.extensibility.core
 * xunit.runner.console
 * xunit.runner.msbuild
 * xunit.runner.utility
 * xunit.runner.visualstudio

## The TeamCity config
Build steps:
* Restore nuget packages (using nuget installer 2.8.5 and restore).
* Build visual studio solution in release mode on default platform.
* Run the MSBuild file for the tests with the target name (test)

## The MSBuild File
In full below, copied almost verbatim from the example on codeplex:

```xml
<Project
    DefaultTargets="Test"
    xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!--
    I don't know if this is the correct reference path. 
    It couldn't find xunit.runner.msbuild.dll in the project outputs so I referenced this directly and it appeared to get past it.
    -->
  <UsingTask
    AssemblyFile="packages\xunit.runner.msbuild.2.0.0\build\portable-net45+win+wpa81+wp80+monotouch+monoandroid+Xamarin.iOS\xunit.runner.msbuild.dll"
    TaskName="Xunit.Runner.MSBuild.xunit" />

  <ItemGroup>
    <TestAssemblies Include="**/*.Tests.dll" />
  </ItemGroup>

  <Target Name="Test">
    <xunit Assemblies="@(TestAssemblies)" TeamCity="true" />
  </Target>

</Project>
```

## Looking for files in obj instead of bin folders?
The error message is:
> [xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5): System.ArgumentException: Unknown test framework: Could not find xunit.dll or xunit.execution.desktop.dll.
> Parameter name: C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\src\test\Common.Tests\obj\Release\RedactedCompany.RedactedProject.Common.Tests.dll

I noticed that it appears to be looking in the `obj` folder though I can't figure out why. The `xunit.execution.desktop.dll` file is in the `bin` folder as expected, but not in the `obj` folder.

Any leads on how I can get past this? I'll keep digging in but it seemed quirky enough that I wanted to report it.

## The full TeamCity xunit log in case it's useful
```
Step 3/3: xUnit tests for all assemblies (MSBuild) (8s)
[16:05:25][Step 3/3] tests.build.teamcity: Build target: Test (5s)
[16:05:25][tests.build.teamcity] Test (5s)
[16:05:25][Test] xunit (5s)
[16:05:27]
[xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5): System.ArgumentException: Unknown test framework: Could not find xunit.dll or xunit.execution.desktop.dll.
Parameter name: C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\src\test\Common.Tests\obj\Release\RedactedCompany.RedactedProject.Common.Tests.dll
[16:05:27][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.XunitFrontController.CreateInnerController()
[16:05:27][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.XunitFrontController.get_InnerController()
[16:05:27][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink, ITestFrameworkDiscoveryOptions discoveryOptions)
[16:05:27][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.Runner.MSBuild.xunit.ExecuteAssembly(String assemblyFileName, String configFileName, TestAssemblyConfiguration configuration)
[16:05:27]
[xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5): System.ArgumentException: Unknown test framework: Could not find xunit.dll or xunit.execution.desktop.dll.
Parameter name: C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\src\test\Data.Tests\obj\Release\RedactedCompany.RedactedProject.Data.Tests.dll
[16:05:27][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.XunitFrontController.CreateInnerController()
[16:05:27][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.XunitFrontController.get_InnerController()
[16:05:27][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink, ITestFrameworkDiscoveryOptions discoveryOptions)
[16:05:27][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.Runner.MSBuild.xunit.ExecuteAssembly(String assemblyFileName, String configFileName, TestAssemblyConfiguration configuration)
[16:05:30]
[xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5): System.ArgumentException: Unknown test framework: Could not find xunit.dll or xunit.execution.desktop.dll.
Parameter name: C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\src\test\Importer.Tests\obj\Release\RedactedCompany.RedactedProject.Importer.Tests.dll
[16:05:30][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.XunitFrontController.CreateInnerController()
[16:05:30][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.XunitFrontController.get_InnerController()
[16:05:30][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink, ITestFrameworkDiscoveryOptions discoveryOptions)
[16:05:30][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.Runner.MSBuild.xunit.ExecuteAssembly(String assemblyFileName, String configFileName, TestAssemblyConfiguration configuration)
[16:05:31]
[xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5): System.ArgumentException: Unknown test framework: Could not find xunit.dll or xunit.execution.desktop.dll.
Parameter name: C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\src\test\ImporterService.Tests\obj\Release\RedactedCompany.RedactedProject.ImporterService.Tests.dll
[16:05:31][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.XunitFrontController.CreateInnerController()
[16:05:31][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.XunitFrontController.get_InnerController()
[16:05:31][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.XunitFrontController.Find(Boolean includeSourceInformation, IMessageSink messageSink, ITestFrameworkDiscoveryOptions discoveryOptions)
[16:05:31][xunit] C:\TeamCity\buildAgent\work\4f4919fa5ddee2f7\tests.build(14, 5):    at Xunit.Runner.MSBuild.xunit.ExecuteAssembly(String assemblyFileName, String configFileName, TestAssemblyConfiguration configuration)
[16:05:31][Step 3/3] Step xUnit tests for all assemblies (MSBuild) failed
```

**Comment by bradwilson** [comment]
I like to ensure `bin` is in the path to solve this exact problem (I also like to use the `$(Configuration)` to make sure I'm not double-running Debug and Release, since I typically build Debug from Visual Studio and Release from the command line):

```xml
<ItemGroup>
    <TestAssemblies Include="**/bin/$(Configuration)/*.Tests.dll" />
</ItemGroup>
```

**Comment by SeanKilleen** [comment]
This was 100% the issue -- makes perfect sense. Thanks for the help! Closing.

**Comment by SeanKilleen** [comment]
Actually, need to reopen this: With that configuration, the build passed, but I hadn't realized it wasn't actually running any of the tests. :laughing: 

This is the output I see -- I'm not sure if it's not finding any assemblies now or what:

![image](https://cloud.githubusercontent.com/assets/2148318/8396643/cdc1fa7c-1d7c-11e5-971d-1fae9248f67e.png)

I'm going to provide a hard reference to an assembly that I know exists and see if I can get it to fail the build based on a forced failing test.

**Comment by SeanKilleen** [comment]
Yeah, odd, works with hard-coded references. Which is fine for me right now since this is only for our build server which is only being built in release for those specific projects. It's not too much overhead to remember to add a test project to the build file if we create a new one.

**Comment by bradwilson** [comment]
That output indicates that the assemblies list you passed was empty. That should maybe be a warning...
