### ISSUE TITLE
Access to the path 'C:\ProgramData\chocolatey\lib\XUnit\tools\xunit\NUnitXml.xslt' is denied

### ISSUE THREAD

**Issue by mattqs** [xunit/xunit#448]
I'm using xunit version 2 installed with chocolatey:

    choco install xunit -version 2.0.0

Running test:

    C:/ProgramData/chocolatey/bin/xunit.console.exe Tests.dll -nunit test.xml -parallel none

Getting exception:

    System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\chocolatey\lib\XUnit\tools\xunit\NUnitXml.xslt' is denied
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share,
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions o
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
       at System.IO.File.Open(String path, FileMode mode)
       at Xunit.ConsoleClient.TransformFactory.Handler_XslTransform(String xslPath, XElement xml, String outputFileName)
       at Xunit.ConsoleClient.TransformFactory.<>c__DisplayClassb.<GetXmlTransformers>b__9(XElement xml)
       at System.Collections.Generic.List`1.ForEach(Action`1 action)
       at Xunit.ConsoleClient.Program.RunProject(String defaultDirectory, XunitProject project, Boolean quiet, Boolean serialize, Bo
       at Xunit.ConsoleClient.Program.Main(String[] args)

**Comment by bradwilson** [comment]
Sorry, we don't maintain the Chocolately packages, so I may not be able to help.

Is that file present on the disk? If not, you'll need to get the Chocolately package maintainer to update the package to include it.

**Comment by mattqs** [comment]
The file is present:

    C:\ProgramData\chocolatey\lib\XUnit\tools\xunit\NUnitXml.xslt

**Comment by bradwilson** [comment]
Stupid bug on my part: we were opening the XSL-T file in read/write mode instead of read-only mode.
