### ISSUE TITLE
RemotingException thrown

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#449]
With 2.1 Beta 3, I received the following exception. My current theory is that the new reporter system is giving the reporter access to messages after the remote testing app domain has shut down.

```
C:\Path\To\MSBuild.proj(287,9): error : [FATAL ERROR] System.Runtime.Remoting.RemotingException
        System.Runtime.Remoting.RemotingException : Object '/f672871c_e3fe_47ec_85b7_b57537ce9c3f/58a7p8su7myf5whp7wuhlluk_1746.rem' has been disconnected or does not exist at the server.

          Server stack trace:
             at System.Runtime.Remoting.Channels.ChannelServices.CheckDisconnectedOrCreateWellKnownObject(IMessage msg)
             at System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage(IMessage msg)

          Exception rethrown at [0]:
             at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
             at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
             at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
             at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

          Exception rethrown at [1]:
             at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
             at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
```

**Comment by bradwilson** [comment]
After a bit of investigation, it appears to be the `ITestAssemblyFinished` message (not surprising, since that's the last thing sent), because the final totals were missing one of the assemblies.

**Comment by bradwilson** [comment]
This could theoretically be related to xunit/visualstudio.xunit#6.

**Comment by bradwilson** [comment]
This appears to have been fixed somewhere along the way.
