### ISSUE TITLE
Tests not executing in VS2015

### ISSUE THREAD

**Issue by paiden** [xunit/xunit#475]
Today I upgraded from VS2015RC to VS2015. Now my XUnit test don't work anymore. Test discovery works correctly, but the tests don't execute. 

When I click 'Run All' in Test Explorer, the progress bar (indicator) starts spinning but nothing happens (waited for 2 minutes, the tests normally need ~15 seconds to execute). 

The only output I get in the Output Pane (Test) is: ------ Run test started ------
Nothing else happens.

The xunit.runner.visualstudio version I use is 2.1.0-beta3-build3029

What can I do to diagnose what exactly the problem is? What can I try to get it to work (uninstall/reinstall runners didn't help)?

Any help would be appreciated, Thx

Best Regards,
Philipp

**Comment by bradwilson** [comment]
Have you tried clearing our your `VisualStudioTestExplorerExtensions` temp folder as [instructed here](http://xunit.github.io/docs/running-tests-in-vs.html)?

**Comment by paiden** [comment]
Unfortunately clearing that folder didn't help. Still the same behavior.

**Comment by bradwilson** [comment]
Try enabling diagnostic messages and see if there is anything more useful in the Tests window when the run fails: http://xunit.github.io/docs/configuring-with-xml.html

Also, do you have a repro available? Is the project in question open source, perhaps?

**Comment by paiden** [comment]
When diagnostics are enabled I get the following output.
``------ Discover test started ------
[xUnit.net 00:00:00.4037670] Exception discovering tests from Nett.UnitTests.dll: System.MissingMethodException: Constructor on type 'Xunit.Sdk.TestFrameworkProxy' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at System.AppDomain.CreateInstanceAndUnwrap(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityAttributes)
   at Xunit.RemoteAppDomainManager.CreateObject[TObject](String assemblyName, String typeName, Object[] args)
   at Xunit.Xunit2Discoverer..ctor(ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder)
   at Xunit.XunitFrontController.CreateInnerController()
   at Xunit.XunitFrontController.get_InnerController()
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IEnumerable`1 sources, IMessageLogger logger, Func`3 visitorFactory, Action`3 visitComplete, Stopwatch stopwatch)
========== Discover test finished: 120 found (0:00:01,2338993) ==========
------ Run test started ------``

But the exception is thrown during discovery, and it seems discovery works correctly. The tested project is available at https://github.com/paiden/Nett. But as said the issues started after upgrading Visual Studio. So I think it is more environment related than project related.

**Comment by bradwilson** [comment]
What version of xUnit.net are you using? (version of the `xunit` package, not the VS runner)

**Comment by paiden** [comment]
I just made a simple new test project with a single test. Tried it with xunit.runner.visualstudio 2.0.0 + xunit 2.0.0 and another time with xunit.runner.visualstudio 2.1.0-beta3-build1069  + xunit 2.1.0-beta3-build3029. In both scenarios I see the same behavior, tests do not run.

I think somehow my dev environment is corrupted. I will try to use XUnit on one of my other machines with a fresh install of VS2015.

**Comment by paiden** [comment]
On my other system xunit works without any issues. On the system with the issues, I'm not able to uninstall/reinstall Visual Studio any more as the setup hangs in a specific step. So it seems all the CTP's, RC's and finally RTM simply created some faulty system state (which I don't intend to analyze further).

Seems I have to completely wipe the system on July 29'th :smile: 

I'm sorry for the troubles & thanks for the help.
