### ISSUE TITLE
Unexpected exceptions during test execution of v1 theories in VS 2015 (RC)

### ISSUE THREAD

**Issue by bradwilson** [xunit/xunit#492]
_From @bradwilson on July 3, 2015 19:49_

While working through issues related to #71, it was discovered that VS2015 is throwing exceptions during reporting of theories with v1 tests, where VS2013 previously was not.

The output for VS2013 is as follows:

```
[xUnit.net 00:00:00.6636602] v1_net45: Performing RecordStart for test case BasicTests.Theory
[xUnit.net 00:00:00.6656988] v1_net45: Performing RecordResult (Pass) for test case BasicTests.Theory
[xUnit.net 00:00:00.6711453] v1_net45: Performing RecordResult (Pass) for test case BasicTests.Theory
[xUnit.net 00:00:00.6735760] v1_net45: Performing RecordResult (Fail) for test case BasicTests.Theory
[xUnit.net 00:00:00.6744458] v1_net45: Performing RecordEnd for test case BasicTests.Theory
```

The output for VS2015 is as follows:

```
[xUnit.net 00:00:00.9678382] v1_net45: Performing RecordStart for test case BasicTests.Theory
[xUnit.net 00:00:00.9691659] v1_net45: Performing RecordResult (Pass) for test case BasicTests.Theory
[xUnit.net 00:00:00.9704055] v1_net45: Performing RecordResult (Pass) for test case BasicTests.Theory
[xUnit.net 00:00:00.9722230] v1_net45: Error occured while RecordResult (Pass) for test case BasicTests.Theory: System.Runtime.InteropServices.COMException (0x80070490): The specified test case was not found in the current result context.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at WEX.TestExecution.FrameworkHandle.RecordResult(TestResult testResult)
   at Xunit.Runner.VisualStudio.TestAdapter.VsExecutionVisitor.<>c__DisplayClass10_0.<Visit>b__0()
   at Xunit.Runner.VisualStudio.TestAdapter.VsExecutionVisitor.TryAndReport(String actionDescription, ITestCase testCase, Action action)
[xUnit.net 00:00:00.9737970] v1_net45: Performing RecordResult (Fail) for test case BasicTests.Theory
[xUnit.net 00:00:00.9747519] v1_net45: Error occured while RecordResult (Fail) for test case BasicTests.Theory: System.Runtime.InteropServices.COMException (0x80070490): The specified test case was not found in the current result context.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at WEX.TestExecution.FrameworkHandle.RecordResult(TestResult testResult)
   at Xunit.Runner.VisualStudio.TestAdapter.VsExecutionVisitor.<>c__DisplayClass9_0.<Visit>b__0()
   at Xunit.Runner.VisualStudio.TestAdapter.VsExecutionVisitor.TryAndReport(String actionDescription, ITestCase testCase, Action action)
[xUnit.net 00:00:00.9751302] v1_net45: Performing RecordEnd for test case BasicTests.Theory
```

In both cases, all the results are actually showing in Visual Studio, so the issue is seemingly benign for the moment.

_Copied from original issue: xunit/visualstudio.xunit#72_

**Comment by MiguelAlho** [comment]
Just wanted to add: Caught this also with Facts, and running the tests in TFS Build (using the VS test task). All tests run and pass, but the record fails (in my case, twice), so the build itself fails.

**Comment by ngates87** [comment]
I am seeing a similar bug, when trying to debug unit tests, using the karama test runner in visual studio 2015 w/ Update 1. 

System.AggregateException was unhandled by user code
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
       at System.Threading.Tasks.Task`1.get_Result()
       at JsTestAdapter.TestAdapter.TestRunner.RunTests(IEnumerable`1 sources, IRunContext runContext, IFrameworkHandle frameworkHandle) in c:\Git\JsTestAdapter\JsTestAdapter\TestAdapter\TestRunner.cs:line 138
       at JsTestAdapter.TestAdapter.TestRunner.RunTests(IEnumerable`1 tests, IRunContext runContext, IFrameworkHandle frameworkHandle) in c:\Git\JsTestAdapter\JsTestAdapter\TestAdapter\TestRunner.cs:line 155
       at WEX.TestExecution.ExecutionPlugin.ExecuteTests(IntPtr context, IDictionary`2 rockSteadySettings)
       at WEX.TestExecution.InteropMethods.ExecuteTests(IntPtr context, String[] rockSteadySettings, Int32 rockSteadySettingsSize)
  InnerException: 
       ErrorCode=-2147023728
       HResult=-2147023728
       Message=The specified test case was not found in the current result context (mapping test id to test node).
       Source=""
       StackTrace:
            at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
            at WEX.TestExecution.FrameworkHandle.RecordStart(TestCase testCase)
            at JsTestAdapter.TestAdapter.TestRunner.RunTest(TestSourceSettings settings, ITestLogger logger, IRunContext runContext, IFrameworkHandle frameworkHandle, Spec spec) in c:\Git\JsTestAdapter\JsTestAdapter\TestAdapter\TestRunner.cs:line 185
            at JsTestAdapter.TestAdapter.TestRunner.<>c__DisplayClassc.<RunTests>b__a(Spec spec) in c:\Git\JsTestAdapter\JsTestAdapter\TestAdapter\TestRunner.cs:line 168
            at JsTestAdapter.TestServerClient.DiscoverCommand.<>c__DisplayClass1.<Run>b__0(JObject message) in c:\Git\JsTestAdapter\JsTestAdapter\TestServerClient\DiscoverCommand.cs:line 21
            at JsTestAdapter.JsonServerClient.JsonServerCommand.<>c__DisplayClassb.<RunInternal>b__4(JObject message) in c:\Git\JsTestAdapter\JsTestAdapter\JsonServerClient\JsonServerCommand.cs:line 81
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
            at JsTestAdapter.JsonServerClient.JsonServerCommand.<RunInternal>d__d.MoveNext() in c:\Git\JsTestAdapter\JsTestAdapter\JsonServerClient\JsonServerCommand.cs:line 99
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
            at JsTestAdapter.JsonServerClient.JsonServerCommand.<RunInternal>d__0.MoveNext() in c:\Git\JsTestAdapter\JsTestAdapter\JsonServerClient\JsonServerCommand.cs:line 53
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
            at JsTestAdapter.TestServerClient.DiscoverCommand.<Run>d__3.MoveNext() in c:\Git\JsTestAdapter\JsTestAdapter\TestServerClient\DiscoverCommand.cs:line 21
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
            at JsTestAdapter.TestAdapter.TestRunner.<RunTests>d__e.MoveNext() in c:\Git\JsTestAdapter\JsTestAdapter\TestAdapter\TestRunner.cs:line 166
       InnerException:

**Comment by borrrden** [comment]
I'm seeing this with UWP.  Also after test execution has supposedly finished the process just hangs there.  The exact message it:

> 23:36:22 Error: [xUnit.net 00:00:24.3128902] Couchbase.Lite.Tests.UWP: Error occured while RecordResult (Pass) for test case LiteCore.Tests.DatabaseTest.TestDatabaseBlobStore: System.ServiceModel.FaultException: The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://tempuri.org/:newTestResults. The InnerException message was 'There was an error deserializing the object of type System.Collections.Generic.IEnumerable\`1[[Microsoft.VisualStudio.TestPlatform.ObjectModel.TestResult, Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]]. StringConverter cannot convert from System.Guid.'.  Please see InnerException for more details.<br>
23:36:22    at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)<br>
23:36:22    at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)<br>
23:36:22    at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation)<br>
23:36:22    at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args)<br>
23:36:22 --- End of stack trace from previous location where exception was thrown ---<br>
23:36:22    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<br>
23:36:22    at System.Reflection.DispatchProxyGenerator.Invoke(Object[] args)<br>
23:36:22    at Microsoft.VisualStudio.TestPlatform.TestExecutor.RocksteadyExecutor.SendTestRunStatsChange(TestRunStats testRunStats, IEnumerable\`1 newTestResults, IEnumerable`1 inProgressTestCases)<br>
23:36:22    at Microsoft.VisualStudio.TestPlatform.Core.TestRunCache.SendResults()<br>
23:36:22    at Microsoft.VisualStudio.TestPlatform.Core.TestRunCache.CheckForCacheHit()<br>
23:36:22    at Microsoft.VisualStudio.TestPlatform.Core.TestRunCache.OnNewTestResult(TestResult testResult)<br>
23:36:22    at Microsoft.VisualStudio.TestPlatform.Core.TestExecutionManager.SendTestResult(TestResult result)<br>
23:36:22    at Xunit.Runner.VisualStudio.TestAdapter.VsExecutionSink.TryAndReport(String actionDescription, ITestCase testCase, Action action)

**Comment by bradwilson** [comment]
Closed for age.
