### ISSUE TITLE
xunit.runner.dnx fail to start TestHost

### ISSUE THREAD

**Issue by singlewind** [xunit/xunit#550]
xunit.runner.dnx 2.1.0-beta5-aspnet-2
xunit 2.1.0-beta4-build3109
Microsoft.Dnx.TestHost 1.0.0-beta7-11805
Microsoft.Dnx.TestAdapter 1.0.0-beta7-11805

with error
System.InvalidOperationException: Unable to load application or execute command 'Microsoft.Framework.TestHost'. Available commands: test.
   at Microsoft.Framework.ApplicationHost.Program.ThrowEntryPointNotfoundException(DefaultHost host, String applicationName, Exception innerException)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)

Unable to start Microsoft.Framework.TestHost

I think Roslyn team has made some changes which breaks the runner.

**Comment by bradwilson** [comment]
We don't support the ASP.NET team builds of the xUnit.net runner (that's what that version number in the package indicates).
