### ISSUE TITLE
xunit.runner.dnx not working in beta7?

### ISSUE THREAD

**Issue by Daniel15** [xunit/xunit#583]
Note: Not sure if this is a Visual Studio tooling issue or a xunit runner issue. Please close this if it's an issue in the VS tooling rather than xunit.

In Visual Studio when I do "Run all" in the Test Explorer, I get this output:

```
------ Test started: Project: RouteJs.Tests.AspNet ------
Starting  Microsoft.Dnx.TestHost [C:\Users\danlo\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7\bin\dnx.exe --appbase "C:\Users\danlo\Documents\Visual Studio 2015\Projects\RouteJs\src\RouteJs.Tests.AspNet" Microsoft.Dnx.ApplicationHost --port 55713 Microsoft.Dnx.TestHost --port 56446]

System.InvalidOperationException: Unable to load application or execute command 'Microsoft.Dnx.TestHost'. Available commands: test.
   at Microsoft.Dnx.ApplicationHost.Program.ThrowEntryPointNotfoundException(DefaultHost host, String applicationName, Exception innerException)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
Unable to start Microsoft.Dnx.TestHost
```

My `project.json`:
```
{
  "version": "2.0.0-*",
  "description": "Unit tests for RouteJs ASP.NET 5 integration",
  "authors": [ "Daniel Lo Nigro" ],
  "tags": [ "asp.net", "mvc", "asp", "routing", "route", "url", "ajax", "jquery", "javascript", "js", "vnext" ],
  "projectUrl": "http://dan.cx/projects/routejs",
  "licenseUrl": "https://github.com/Daniel15/RouteJs#licence",

  "dependencies": {
    "Microsoft.AspNet.Routing": "1.0.0-beta7",
    "Moq": "4.2.1507.118",
    "RouteJs.AspNet": "2.0.0-*",
    "xunit": "2.1.0-beta4-*",
    "xunit.runner.dnx": "2.1.0-beta4-*"
  },

  "frameworks": {
    "dnx451": { }
  },

  "commands": {
    "test": "xunit.runner.dnx"
  }
}
```

**Comment by bradwilson** [comment]
Upgrade to `xunit 2.1.0-rc1-*` and `xunit.runner.dnx 2.1.0-beta5-*`.
