### ISSUE TITLE
UWP test discovery fails with x64 build

### ISSUE THREAD

**Issue by sandersaares** [xunit/xunit#598]
I see no tests in the Test Explorer. Using the following NuGet packages:

```
 "xunit": "2.1.0-rc2-build3176",
 "xunit.runner.visualstudio": "2.1.0-rc2-build1126"
```

Everything works fine with x86 build. Here is the output from test discovery when x64 variant of my project is built:

```
------ Discover test started ------
Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run: 
Tests.Uwp.exe is built for Framework Framework45 and Platform X64.
 Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.
[xUnit.net 00:00:00.1421886] Exception discovering tests from Tests.Uwp: System.BadImageFormatException: Could not load file or assembly 'Tests.Uwp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: 'Tests.Uwp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Xunit.Sdk.ReflectionAssemblyInfo..ctor(String assemblyFileName)$$RethrowMarker$$   at ExceptionExtensions.RethrowWithNoStackTraceLoss(Exception ex)
   at Xunit.AppDomainManager_AppDomain.CreateObject[TObject](AssemblyName assemblyName, String typeName, Object[] args)
   at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk)
   at Xunit.XunitFrontController.CreateInnerController()
   at Xunit.XunitFrontController.get_InnerController()
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IEnumerable`1 sources, LoggerHelper logger, Func`4 visitorFactory, Action`4 visitComplete)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

========== Discover test finished: 0 found (0:00:00,1600002) ==========
```

Project files themselves: https://mega.nz/#!NkgUFSgY!HDLCq6LFdKnaLPyUu5QuBBy1xLU_sVarpSOBrWhstNI

**Comment by sandersaares** [comment]
Hmm, upon contemplating I realize this may be built-in Visual Studio behavior? My expectation was that tests follow the selected CPU architecture but I realize there is also another "Default processor architecture" switch just for tests. Please confirm what is the proper pattern of using xunit with regard to CPU architecture, in case I misunderstand it.

**Comment by onovotny** [comment]
I'm not sure this can be resolved for the Visual Studio Runner. The VS Runner always runs discovery using an x86 process using the Desktop .NET version. xUnit requires code to run during discovery as that's how its extensibility works for discovery/execution.

For the VS runner to work, you'll probably need to be in x86 for your build configuration. Otherwise, you can give the xUnit for Devices a shot as it'll work with everything. http://xunit.github.io/docs/getting-started-devices-uwp.html

**Comment by pk-picturepark** [comment]
I had a similar exception. This did the trick for me in VS2013:

- Delete the temp test discovery directory located here C:\Users\{USER}\AppData\Local\Temp\VisualStudioTestExplorerExtensions.
- In Visual Studio set all projects to x64.
- In Visual Studio set the default processor architecture to x64 (Test/Test Settings/Default Processor Architecture).

**Comment by ZodmanPerth** [comment]
Following the advice from @pk-picturepark, all I had to do was set my test settings default processor architecture to x64 and rebuild and my tests showed up in Test Explorer.  Awesome!

**Comment by bradwilson** [comment]
Closing as external.
