### ISSUE TITLE
HTML Report Output Error

### ISSUE THREAD

**Issue by tstewart65** [xunit/xunit#613]
There is an error in the message area of the HTML Report for test failures.  The message area is not getting newlines in the output.  I am getting either \r\n or just \n.  Here is the output from two test failures from a test project I made to show the problem.  The place where the \n only shows up is from an error using the Shouldy library for the assertion.

✘  xUnitErrorProject.TestClassTests.Test1
**Multi Line Failure Message\r\nLine 2\r\nLine 3\r\nLine 4\r\nExpected: True\r\nActual:   False**
   at xUnitErrorProject.TestClassTests.Test1() in D:\VS.Net2015_WorkArea\xUnitErrorProject\xUnitErrorProject\TestClassTests.cs:line 21
0.2303286s
✘  xUnitErrorProject.TestClassTests.Test2
**Shouldly.ShouldAssertException : TestClass.Function1() should be True but was False\n    Additional Info:\n    Multi Line Failure Message\r\nLine 2\r\nLine 3\r\nLine 4**
   at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual, Func`1 customMessage)
   at Shouldly.ShouldBeBooleanExtensions.ShouldBeTrue(Boolean actual, String customMessage)
   at xUnitErrorProject.TestClassTests.Test2() in D:\VS.Net2015_WorkArea\xUnitErrorProject\xUnitErrorProject\TestClassTests.cs:line 31

**Comment by bradwilson** [comment]
Already fixed.

**Comment by tstewart65** [comment]
Fixed in what version?  I am currently using version 2.2.0 and I still get the same error.

**Comment by bradwilson** [comment]
Please try with the latest 2.3 build (right now, `2.3.0-beta5-build3769`) and see if your problem is solved.

**Comment by tstewart65** [comment]
Just tried 2.3.0-beta5-build3769 and I still get \r\n and \n in the output.

**Comment by tstewart65** [comment]
Two examples

Shouldly.ShouldAssertException : _dataFileInfo.DeviceName\n    should be\n\"1\"\n    but was\n\"\"\n    difference\nDifference     |  |   \r\n               | \\|/  \r\nIndex          | 0    \r\nExpected Value | 1    \r\nActual Value   |      \r\nExpected Code  | 49   \r\nActual Code    |      

   at Shouldly.ShouldBeStringTestExtensions.ExecuteAssertion(IAssertion assertion, Func`1 customMessage)
   at Shouldly.ShouldBeStringTestExtensions.ShouldBe(String actual, String expected, Func`1 customMessage, StringCompareShould options)
   at Shouldly.ShouldBeStringTestExtensions.ShouldBe(String actual, String expected, StringCompareShould options)
   at Shouldly.ShouldBeStringTestExtensions.ShouldBe(String actual, String expected)

System.ArgumentNullException : Value cannot be null.\r\nParameter name: dataFileRules

**Comment by tstewart65** [comment]
Will a fix for this make it into the 2.3.0 release?

**Comment by bradwilson** [comment]
2.3.0 has already been released, and I haven't had a chance to revisit this.

**Comment by EamonNerbonne** [comment]
This same bug also occurs in the xml output (using 2.3.1).  Additionally, `\` appears to be "unescaped" into `\\` - even though in an xml CDATA section that's clearly not needed.

If by design, it's not documented https://xunit.github.io/docs/format-xml-v2 - since not all codepoints are valid in xml at all (e.g. an exception with control-characters is nasty nasty, but possible), I can imagine the unescaping was by design?

**Comment by EamonNerbonne** [comment]
This appears to be because the XmlEscape method xUnit uses, which is here... 

https://github.com/xunit/xunit/blame/master/src/xunit.runner.utility/Sinks/DelegatingSinks/DelegatingXmlCreationSink.cs#L249

...chooses to escape values like `\n` even though those don't need to be escaped, and subsequent consumers such as the html reporter but e.g. also the jenkins plugin don't unescape.  I'm guessing either this custom escapeing should be documented at  https://xunit.github.io/docs/format-xml-v2, or it should be removed (and xml-invalid codepoints like `0` replaced with readable but not reversible alternative).  Given that consumers currently clearly do not support this output *well* as is, I'd vote for removing the escaping, even though that may break any consumers that do support this undocumented escaping.

I don't mind helping out, if that's appreciated and @bradwilson thinks replacing the escaping with something else is the way to go.

**Comment by RikkiGibson** [comment]
This is still happening. I wonder if you would accept a fix for this @bradwilson? Should it work by removing the escaping and fixing up consumers that expected the escaping, or by having some consumers such as the HTML reporter unescape the content as needed?

**Comment by RikkiGibson** [comment]
Posting just in case it helps anyone. I have created a bookmarklet which reverses the undesirable HTML escaping. You can open your HTML test results in your browser and just run it to view the error messages in your tests in a comprehensible form.

```js
(function () {
  for (let parent of document.querySelectorAll("a#failures div.row")) {
    parent.childNodes[6].innerHTML = parent.childNodes[6].innerHTML
      .replaceAll("\\\\", "\\")
      .replaceAll("\\r", "\r")
      .replaceAll("\\n", "\n")
      .replaceAll("\\t", "\t")
      .replaceAll("\\0", "\0")
      .replaceAll("\\a", "\a")
      .replaceAll("\\b", "\b")
      .replaceAll("\\v", "\v")
      .replaceAll("\\\"", "\"")
      .replaceAll("\\f", "\f");
  }
})();
```

Minified bookmarklet:
```js
javascript:(function(){for(let l of document.querySelectorAll("a#failures%20div.row"))l.childNodes[6].innerHTML=l.childNodes[6].innerHTML.replaceAll("\\\\","\\").replaceAll("\\r","\r").replaceAll("\\n","\n").replaceAll("\\t","\t").replaceAll("\\0","\0").replaceAll("\\a","a").replaceAll("\\b","\b").replaceAll("\\v","\v").replaceAll('\\"','"').replaceAll("\\f","\f")})();
```

**Comment by bradwilson** [comment]
I have verified that this is fixed in v3.

![image](https://github.com/user-attachments/assets/1eefb418-99cc-443c-a3fd-9b94b97838e7)
