### ISSUE TITLE
Provide build compatible with DNX rc1-16048

### ISSUE THREAD

**Issue by AlekseyMartynov** [xunit/xunit#652]
System.NullReferenceException: Object reference not set to an instance of an object.
       at Xunit.Runner.Dnx.Program.Main(String[] args)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
       at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()

with 

    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-beta6-*",

and **Clr-x86-1.0.0-rc1-16048**

P.S. with 2.1.0-rc1-build194 too

**Comment by bradwilson** [comment]
Build `2.1.0-rc1-build195`
