### ISSUE TITLE
Console & DNX runner should fail better with an unknown switch

### ISSUE THREAD

**Issue by LeeCheneler** [xunit/xunit#653]
-Xml command works fine:
`dnx test -xml "report.xml"`

-NUnit command throws an exception:
`dnx test -NUnit "report.xml"`

The exception:
'System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Xunit.Runner.Dnx.TransformFactory.<>c__DisplayClass5_0.<GetXmlTransformers>b__1(XElement xml)
   at Xunit.Runner.Dnx.Program.RunProject(XunitProject project, Nullable`1 parallelizeAssemblies, Nullable`1 parallelizeTestCollections, Nullable`1 maxThreadCount, Boolean diagnosticMessages, Boolean noColor, Boolean designTime, Boolean list, IReadOnlyList`1 designTimeFullyQualifiedNames)
   at Xunit.Runner.Dnx.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)'

**Comment by bradwilson** [comment]
Leaving aside that the failure message is poor, your seeing this because the DNX runner does not support any output format other than XML (because DNX does not support XSL-T).
