### ISSUE TITLE
Microsoft.Dnx.TestHost error

### ISSUE THREAD

**Issue by wangkanai** [xunit/xunit#690]
I having trouble trying get xunit to discover my tests and its showing the following error.
```
------ Discover test started ------
------ Test started: Project: Hashnest.FunctionalTest ------
Starting  Microsoft.Dnx.TestHost [C:\Users\sarin\.dnx\runtimes\dnx-clr-win-x64.1.0.0-rc1-final\bin\dnx.exe --appbase "D:\Sources\Bitcoin\Hashnest\test\Hashnest.FunctionalTest" Microsoft.Dnx.ApplicationHost --port 35520 Microsoft.Dnx.TestHost --port 53582 --parentProcessId 12452]
Connected to Microsoft.Dnx.TestHost
Discovering tests in 'D:\Sources\Bitcoin\Hashnest\test\Hashnest.FunctionalTest\project.json'
Error discovering tests in 'D:\Sources\Bitcoin\Hashnest\test\Hashnest.FunctionalTest\project.json'. 
Exception: System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dnx.TestHost.ProjectTestHostServices..ctor(Project project, ReportingChannel channel)
   at Microsoft.Dnx.TestHost.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.Discovery.HostExtensions.GetTests(IHost host, ITestCaseDiscoverySink discovery, IMessageLogger logger, KRuntimeConfiguration testConfiguration)
   at Microsoft.VisualStudio.Web.UnitTest.TestAdapter.KUnitTestDiscoverer.GetTestCases(IEnumerable`1 sources, IMessageLogger logger, ITestCaseDiscoverySink discoverySink)
---> (Inner Exception #0) System.InvalidOperationException: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dnx.TestHost.ProjectTestHostServices..ctor(Project project, ReportingChannel channel)
   at Microsoft.Dnx.TestHost.Program.<>c__DisplayClass0_0.<<Main>b__0>d.MoveNext()<---

========== Discover test finished: 0 found (0:00:01.0431483) ==========
```

**Comment by wangkanai** [comment]
I using the current `dnvm`, but the other machine work fine.
```
PS C:\Users\sarin> dnvm
   ___  _  ___   ____  ___
  / _ \/ |/ / | / /  |/  /
 / // /    /| |/ / /|_/ /
/____/_/|_/ |___/_/  /_/
.NET Version Manager v1.0.0-rc2-15545
```

**Comment by bradwilson** [comment]
DNX version and `xunit.runner.dnx` version must be correctly matched. See the table here: http://xunit.github.io/docs/getting-started-dnx.html

**Comment by scugzbc** [comment]
Our understanding is ambiguous ,  just see the issue #692 .
There is only one truth.
