### ISSUE TITLE
Xunit crashes when discovering tests if a public class derives from a Windows runtime component

### ISSUE THREAD

**Issue by twsouthwick** [xunit/xunit#730]
I have a UWP test project that references a runtime component that has a few interfaces I need to implement for test mocking. I ran into a bug where xunit will crash during the test discovery phase because it cannot load types from a winmd on desktop.

A simple repro:

The runtime component:

``` csharp
namespace RuntimeComponentXunitIssue
{
    public interface IRuntimeComponent
    {
    }
}
```

The UWP xunit test:

``` csharp
using Xunit;

namespace UnitTestProject1
{
    public class Test : RuntimeComponentXunitIssue.IRuntimeComponent { }

    public class UnitTest1
    {

        [Fact]
        public void TestMethod1()
        {
        }
    }
}
```

The exception I get when the discovery step happens is below:

```
------ Discover test started ------
[xUnit.net 00:00:00.8035827] Exception discovering tests from UnitTestProject1: System.TypeLoadException: Could not find Windows Runtime type 'RuntimeComponentXunitIssue.IRuntimeComponent'. ---> System.NotSupportedException: Types from custom Windows Runtime components are not supported in desktop applications.

   --- End of inner exception stack trace ---

Server stack trace: 
   at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at Xunit.Sdk.ReflectionAssemblyInfo.GetTypes(Boolean includePrivateTypes)
   at Xunit.Sdk.TestCollectionFactoryHelper.GetTestCollectionDefinitions(IAssemblyInfo assemblyInfo, IMessageSink diagnosticMessageSink)
   at Xunit.Sdk.CollectionPerClassTestCollectionFactory..ctor(ITestAssembly testAssembly, IMessageSink diagnosticMessageSink)
   at Xunit.Sdk.ExtensibilityPointFactory.GetXunitTestCollectionFactory(IMessageSink diagnosticMessageSink, IAttributeInfo collectionBehaviorAttribute, ITestAssembly testAssembly)
   at Xunit.Sdk.XunitTestFrameworkDiscoverer..ctor(IAssemblyInfo assemblyInfo, ISourceInformationProvider sourceProvider, IMessageSink diagnosticMessageSink, IXunitTestCollectionFactory collectionFactory)
   at Xunit.Sdk.XunitTestFramework.CreateDiscoverer(IAssemblyInfo assemblyInfo)
   at Xunit.Sdk.TestFramework.GetDiscoverer(IAssemblyInfo assemblyInfo)
   at Xunit.Sdk.TestFrameworkProxy.GetDiscoverer(IAssemblyInfo assembly)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Xunit.Abstractions.ITestFramework.GetDiscoverer(IAssemblyInfo assembly)
   at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk)
   at Xunit.XunitFrontController.CreateInnerController()
   at Xunit.XunitFrontController.get_InnerController()
   at Xunit.Runner.VisualStudio.TestAdapter.VsTestRunner.DiscoverTests[TVisitor](IEnumerable`1 sources, LoggerHelper logger, Func`4 visitorFactory, Action`4 visitComplete)
========== Discover test finished: 0 found (0:00:00.8379584) ==========
```

If I make the class a non-public class the discovery step continues fine. I'm fine with that work around, but it would be better to have an actionable error shown when the test discovery step fails.

**Comment by bradwilson** [comment]
Yeah, you can't do that.

The Visual Studio runner discover tests in the desktop CLR, None of UWP is available at the time of discovery. If you do anything during discovery that would require UWP components to be available, the discovery will fail.

You have two choices:

1. Stop doing this. This is a pretty good choice. :)
2. Use the [devices runner](https://github.com/xunit/devices.xunit) instead of the Visual Studio runner. Also a pretty good choice. :)

**Comment by twsouthwick** [comment]
It makes sense that it can't load the type. I'm wondering why it just spits out a stack trace when it could log that a specific type couldn't be loaded (and maybe give helpful hints about next steps), and continue on with the discovery phase. Does it have to be all or nothing?

**Comment by bradwilson** [comment]
There's absolutely nothing we can do here. We ask the assembly for the exported types (which is what we'd use to do the scan), and it throws an exception.

No types, no discovery.

**Comment by twsouthwick** [comment]
Ok - wasn't sure the process you were using for discovering types. Is there a place you capture known issues/problems people may face? I can add this and describe the workaround.

**Comment by bradwilson** [comment]
We don't have a Known Issues page on our [docs site](https://xunit.github.io/), but we'd be happy to [take a PR](https://github.com/xunit/xunit.github.io/pulls/).

**Comment by bradwilson** [comment]
Closed for age.
