### ISSUE TITLE
Console Runner 2.1.0 IndexOutOfRangeException Xunit.XmlTestExecutionVisitor.CreateFailureElement

### ISSUE THREAD

**Issue by paulespinosa** [xunit/xunit#739]
Hello, the xUnit console runner for version 2.1.0 is throwing an IndexOutOfRangeException and crashing without producing any test results.

I'm running:
`C:\xunit.runner.console.2.1.0\tools> xunit.console.runner.exe Test.dll -noshadow -nunit TestResults.xml -verbose`
Let me know what other information you need to help understand the problem.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.

Server stack trace: 
   at Xunit.XmlTestExecutionVisitor.CreateFailureElement(IFailureInformation failureInfo)
   at Xunit.XmlTestExecutionVisitor.Visit(ITestFailed testFailed)
   at Xunit.TestMessageVisitor.<>c.<OnMessage>b__2_31(TestMessageVisitor t, ITestFailed m)
   at Xunit.TestMessageVisitor.DoVisit[TMessage](IMessageSinkMessage message, Func`3 callback)
   at Xunit.TestMessageVisitor.OnMessage(IMessageSinkMessage message)
   at Xunit.TestMessageVisitor`1.OnMessage(IMessageSinkMessage message)
   at Xunit.XmlTestExecutionVisitor.OnMessage(IMessageSinkMessage message)
   at Xunit.XmlAggregateVisitor.OnMessage(IMessageSinkMessage message)
   at Xunit.TestClassCallbackHandler.OnTest(XmlNode xml)
   at Xunit.TestClassCallbackHandler.OnXmlNode(XmlNode node)
   at Xunit.XmlNodeCallbackHandler.System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.PrivateProcessMessage(RuntimeMethodHandle md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at System.Web.UI.ICallbackEventHandler.RaiseCallbackEvent(String eventArgument)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Xunit.Sdk.ExecutorCallback.CallbackEventHandlerCallback.Notify(String value)
   at Xunit.Sdk.Executor.OnTestResult(ITestResult result, ExecutorCallback callback)
   at Xunit.Sdk.Executor.RunTests.<>c__DisplayClass12.<.ctor>b__11(ITestResult result)
   at Xunit.Sdk.TestClassCommandRunner.Execute(ITestClassCommand testClassCommand, List`1 methods, Predicate`1 startCallback, Predicate`1 resultCallback)
   at Xunit.Sdk.Executor.RunTests.<>c__DisplayClass12.<.ctor>b__f()
   at Xunit.Sdk.Executor.ThreadRunner(Object threadStart)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by bradwilson** [comment]
Closed for age.
