### ISSUE TITLE
Getting System.InvalidOperationException while testing action method returning view with model as argument.

### ISSUE THREAD

**Issue by Ashish225** [xunit/xunit#794]
I am using xunit framework to test MVC6 application, I have test project created by asp.net5 class library project template with VS2015.

While testing action method which is returning view with model passed as argument, throws System.InvalidOperationException.

Here is full details of exception:

An exception of type 'System.InvalidOperationException' occurred in Microsoft.Extensions.DependencyInjection.Abstractions.dll but was not handled in user code

Additional information: No service for type 'Microsoft.AspNet.Mvc.ViewFeatures.ITempDataDictionary' has been registered.

Stack trace:
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNet.Mvc.Controller.get_TempData()
   at Microsoft.AspNet.Mvc.Controller.View(String viewName, Object model)
   at Microsoft.AspNet.Mvc.Controller.View(Object model)

Note: if action method returns view without passed model as argument, then no exception raised.

Can anybody help me to find out cause.

Regards,
Ashish

**Comment by bradwilson** [comment]
Closed for age.
