### ISSUE TITLE
XUnit with 1.0.0-rc2-20222 Not discovering Tests

### ISSUE THREAD

**Issue by DreamingDevs** [xunit/xunit#825]
I have following `dotnet CLI` version installed on `Visual Studio 2015 Update 2 Azure VM` - 

![image](https://cloud.githubusercontent.com/assets/5579127/14523051/3324702c-024f-11e6-9e4b-dd635ef55be4.png)

I am using `DNX 1.0.0-rc2-20222` from unstable feed by setting `DNX_UNSTABLE_FEED=https://www.myget.org/F/aspnetcidev/` - 

![image](https://cloud.githubusercontent.com/assets/5579127/14523255/5a3c9ed6-0250-11e6-973e-a89553bad569.png)

I have following `Test` Project `Project.json` - 

```
{
  "version": "1.0.0-*",
  "description": "Test Class Library",
  "authors": [ "Rami" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "frameworks": {
    "net451": {
      "frameworkAssemblies": {
        "System.ComponentModel": "",
        "System.Threading.Tasks": ""
      }
    }
  },
  "dependencies": {
    "Moq": "4.2.1312.1622",
    "xunit": "2.1.0"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  }
}
```

I get following output - 

```

------ Discover test started ------
------ Test started: Project: Aps.Idp.Tests ------
Starting  Microsoft.Dnx.TestHost [C:\Users\ramiadmin\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc2-20222\bin\dnx.exe --appbase "C:\Users\ramiadmin\Desktop\SbmAps\SbmAps\Idp\test\Aps.Idp.Tests" Microsoft.Dnx.ApplicationHost --port 51123 Microsoft.Dnx.TestHost --port 51821 --parentProcessId 6836]

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.CommandLineUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Extensions.CommandLineUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Microsoft.Dnx.TestHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.<>c__DisplayClass3_0.<ExecuteMain>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Unable to start Microsoft.Dnx.TestHost
========== Discover test finished: 0 found (0:00:01.0481486) ==========

```

Questions - 
1. What should I dot to get `net451` with `xUnit` to discover test? I am not even able to add `xunit.runner.dnx` as dependency because it is not compatible with `net451`. How should I proceed?
2. Should I need to use `dnx451` and add `xunit.runner.dnx`? I did this change, but got lot of compilation errors in the test project (for example System.Object is missng etc.,).

**Comment by onovotny** [comment]
The DNX runner does not support dotnet CLI. You need to use the CLI runner.

You can see examples of this with https://github.com/dotnet/coreclr.xunit and Humanizer: https://github.com/Humanizr/Humanizer/tree/dev/src/Humanizer.Tests.DotNet

Note that you'll need to make sure that the nuget.config matches those repos for now.

**Comment by bradwilson** [comment]
Closed for age.
