### ISSUE TITLE
dotnet-test-xunit breaks for net451 (dotnet CLI RC2)

### ISSUE THREAD

**Issue by qooroo** [xunit/xunit#848]
`dotnet test` with framework `net451` does not work.

When running on windows 10, the runner is found but errors as follows:
```
xUnit.net .NET CLI test runner (32-bit win10-x86)
System.DllNotFoundException: Unable to load DLL 'Microsoft.DiaSymReader.Native.x86.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```
Details found here: https://github.com/dotnet/cli/issues/3069

When running on Ubuntu 14.04 / mono 4.2.3.4, it cannot find the test runner:
```
dotnet-test Error: 0 : Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-test-xunit"
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.FindProjectDependencyCommands(String commandName, IEnumerable`1 commandArgs, String configuration, NuGetFramework framework, String outputPath, String buildBasePath, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration)
   at Microsoft.DotNet.Tools.Test.ConsoleTestRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
```

`dotnet --version` `1.0.0-preview1-002702`

Repro here:
https://gist.github.com/qooroo/d989eb091e2581fdea818c78d6b8f485

**Comment by pranavkm** [comment]
Dup of https://github.com/xunit/xunit/issues/843
