### ISSUE TITLE
Core RC2 project with net451

### ISSUE THREAD

**Issue by techcap** [xunit/xunit#850]
xUnit works well at .net core RC2 based on this documents.
https://xunit.github.io/docs/getting-started-dotnet-core.html

I want to use net451 framework only on this project template.

When I used this project.json, it works properly both of netcore and net451.

```
{
  "version": "1.0.0-*",
  "testRunner": "xunit",
  "dependencies": {
    "xunit": "2.1.0",
    "dotnet-test-xunit" : "1.0.0-rc2-build10015"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-rc2-3002702"
        }
      },
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ]
    },
    "net451": {
    }
  }
}
```

But if I change the framework order of netcoreapp1.0 and net451 like below, it doesn't work. There's no list in the Test Explorer.

```
  "version": "1.0.0-*",
  "testRunner": "xunit",
  "dependencies": {
    "xunit": "2.1.0",
    "dotnet-test-xunit" : "1.0.0-rc2-build10015"
  },

  "frameworks": {
    "net451": {
    },
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0-rc2-3002702"
        }
      },
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  }
}
```

Finally, I want to use only net451 like below. Is there anything I can do?

```
{
  "version": "1.0.0-*",
  "testRunner": "xunit",
  "dependencies": {
    "xunit": "2.1.0",
    "dotnet-test-xunit" : "1.0.0-rc2-build10015"
  },

  "frameworks": {
    "net451": {
    }
  }
}
```

**Comment by techcap** [comment]
I got the error message after building.

```
------ Discover test started ------
Discovering tests in 'd:\work\xUnitTest\src\xUnitTest\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "d:\work\xUnitTest\src\xUnitTest\project.json" --output "d:\work\xUnitTest\src\xUnitTest\bin\Debug\net451\win7-x64" --port 12293 --parentProcessId 8496 --no-build]
Unable to start C:\Program Files\dotnet\dotnet.exe
dotnet-test Error: 0 : [ReportingChannel]: Waiting for message failed System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.DotNet.Tools.Test.ReportingChannel.ReadMessages()
dotnet-test Error: 0 : [ReportingChannel]: Error sending System.IO.IOException: Unable to write data to the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BinaryWriter.Write7BitEncodedInt(Int32 value)
   at System.IO.BinaryWriter.Write(String value)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.Send(Message message)

Unhandled Exception: System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.Stream.ReadByte()
   at System.IO.BinaryReader.ReadByte()
   at System.IO.BinaryReader.Read7BitEncodedInt()
   at System.IO.BinaryReader.ReadString()
   at Microsoft.DotNet.Tools.Test.ReportingChannel.ReadMessages()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
dotnet-test Error: 0 : System.IO.IOException: Unable to write data to the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BinaryWriter.Write7BitEncodedInt(Int32 value)
   at System.IO.BinaryWriter.Write(String value)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.Send(Message message)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.SendError(String error)
   at Microsoft.DotNet.Tools.Test.ReportingChannel.SendError(Exception ex)
   at Microsoft.DotNet.Tools.Test.DesignTimeRunner.HandleDesignTimeMessages(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.DesignTimeRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.BaseDotnetTestRunner.RunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams, BuildWorkspace workspace)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
========== Discover test finished: 0 found (0:00:00.4140169) ==========
```

**Comment by guylando** [comment]
I get the same error.

**Comment by guylando** [comment]
OK i managed to get it working, will share my project.json so it might help you:
The 2 critical stuff are:
1)"testRunner": "xunit"
2)The versions of the xunit packages and of the Microsoft.NETCore.Platforms package.

{
  "version": "0.0.1",
  "dependencies": {
    "Microsoft.NETCore.Platforms": "1.0.1-rc3-24117-00",
    "xunit": "2.1.0",
    "dotnet-test-xunit": "1.0.0-rc3-build10019",
    "Microsoft.Extensions.Logging": "1.0.0-rc3-21005"
  },
  "testRunner": "xunit",
  "frameworks": {
    "net451": {
    }
  },
  "buildOptions": {
    "preserveCompilationContext": true,
    "copyToOutput": {
      "include": [
        "config.json"
      ]
    },
    "warningsAsErrors": true
  }
}

**Comment by techcap** [comment]
dotnet-test-xunit is updated. Now it works properly.

project.json
```
{
  "version": "1.0.0-*",
  "testRunner": "xunit",

  "frameworks": {
    "net451": {

    }
  },

  "dependencies": {
    "xunit": "2.1.0",
    "dotnet-test-xunit": "1.0.0-rc2-build10025"
  }
}
```

**Comment by techcap** [comment]
It only works several times and stops working.
If I delete debug folder, it works again.
So strange.

**Comment by RehanSaeed** [comment]
Can confirm that this is not working when selecting the full .NET Framework. I've tried @techcap's project.json and I get no tests appearing in my Test Explorer.

**Comment by bradwilson** [comment]
Following my *_exact_* directions, I'm able to get `net451` tests to show in Visual Studio.

http://xunit.github.io/docs/getting-started-dotnet-core.html#targeting-desktop

**Comment by RehanSaeed** [comment]
This is what I've got but Test Explorer is still not showing my tests.

```
{
  "version": "1.5.0-*",
  "testRunner": "xunit",

  "dependencies": {
    "MyAssembly": "1.5.0-*",
    "Moq": "4.2.1510.2205",
    "xunit": "2.1.0",
    "dotnet-test-xunit": "1.0.0-rc2-build10025"
  },

  "frameworks": {
    "net461": {
      "dependencies": {
        "Microsoft.NETCore.Platforms": "1.0.1-rc2-24027"
      }
    }
  }
}
```

**Comment by bradwilson** [comment]
Do the tests run from the command line?

**Comment by techcap** [comment]
@RehanSaeed In my case, after removing debug folder, it works again.

**Comment by RehanSaeed** [comment]
I managed to find the issue. I was porting my project from RC1 to RC2 and did not have the xproj quite right. 

```
Correct
<Import Project="$(VSToolsPath)\DotNet\Microsoft.DotNet.targets" Condition="'$(VSToolsPath)' != ''" />
```

```
Incorrect
<Import Project="$(VSToolsPath)\DotNet.Web\Microsoft.DotNet.targets" Condition="'$(VSToolsPath)' != ''" />
```

**Comment by Aerendel** [comment]
I had the same issue as @RehanSaeed but it had to do with "Target framework version" set by Visual Studio for the project. When creating the unit test project, I had 4.5.2 selected as target version, and my project.json had ```net451```. In other words, Visual Studio seems to want the xproj target version to match with the project.json target framework if you are targetting desktop.

This can be verified and fixed in the xproj:
```<TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>```

**Comment by MedAnd** [comment]
Similar issue with Core RC2 project and net460, fails with:

Unable to start C:\Program Files\dotnet\dotnet.exe
Could not read the incremental cache file: xxxxxxxxxxxxxxxxxxxxxxxxxx\Acme.Core\obj\Debug\net46\.IncrementalCache
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.

{
  "version": "1.0.0-*",
  "testRunner": "xunit",

  "dependencies": {
    "Acme.Common": "1.0.0-*",
    "Acme.Core": "1.0.0-*",
    "Acme.Test.Helpers": "1.0.0-*",
    "xunit": "2.2.0-beta1-build3239",
    "dotnet-test-xunit": "1.0.0-rc2-build10025"
  },

  "frameworks": {
    "net46": {
      "frameworkAssemblies": {
        "System.Net": "4.0.0.0",
        "System.Net.Http": "4.0.0.0",
        "System.Runtime": "4.0.20.0",
        "System.Threading.Tasks": "4.0.10.0"
      }
    }
  },

  "runtimes": {
    "win7-x64": { }
  }

}

**Comment by MedAnd** [comment]
Just re-tested with .Net Core RC2 and dotnet-test-xunit 1.0.0-rc3-build10027,  and still the same issue to above. For example test discovery in VS 2015 fails only for some projects with error:

Unable to start C:\Program Files\dotnet\dotnet.exe
Could not read the incremental cache file: xxxxxxxxxxxxxxxxxxxxxxxxxx\Acme.Core\obj\Debug\net46.IncrementalCache

**Comment by MedAnd** [comment]
@bradwilson - Hope this helps... tracked down one potential issue in VS2015; 

When Test Settings --> Default Processor Architecture is x86 then xUnit tests work as expected. 

When Test Settings --> Default Processor Architecture is set to x64 multiple test projects experience this bug:

Could not read the incremental cache file: xxxxxxxxxxxxxxxxxxxxxxxxxx\Acme.Core\obj\Debug\net46.IncrementalCache

**Comment by bradwilson** [comment]
That's outside the realm of things we control. This issue should probably be reported to Microsoft.

**Comment by bradwilson** [comment]
Closed for age.
