### ISSUE TITLE
dotnet-test-xunit 1.0.0-rc3 not working on net451 with mono on ubuntu 14.04

### ISSUE THREAD

**Issue by qooroo** [xunit/xunit#852]
using:

```
{
  "version": "1.0.0",

  "dependencies": {
    "Microsoft.NETCore.Platforms": "1.0.1-rc2-24027",
    "xunit": "2.1.0",
    "xunit.runner.visualstudio": "2.1.0",
    "dotnet-test-xunit": "1.0.0-rc3-*"
  },

  "testRunner": "xunit",

  "frameworks": {
    "net451": {
    }
  }
}
```

This runs fine on windows, but running on ubuntu/mono I get the following:

```
dotnet-test Error: 0 : Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-test-xunit"
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.FindProjectDependencyCommands(String commandName, IEnumerable`1 commandArgs, String configuration, NuGetFramework framework, String outputPath, String buildBasePath, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration)
   at Microsoft.DotNet.Tools.Test.ConsoleTestRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
```

ubuntu 14.04,

```
Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
```

**Comment by wmeints** [comment]
Tried running tests with your project.json file, but apparantly there's a typo at line 4. it shouldn't list the extra curly brace on that line. On Mac everything works with RC3 luckely :-)

**Comment by jchannon** [comment]
Even with the typo this still seems to be the case.

We are trying to support net452 on mono and netcore on Nancy.

If you clone Nancy, `dotnet restore` , `cd test/Nancy.Authentication.Basic.Tests`, `dotnet test` the output is :
```
dotnet-test Error: 0 : Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "dotnet-test-xunit"
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.FindProjectDependencyCommands(String commandName, IEnumerable`1 commandArgs, String configuration, NuGetFramework framework, String outputPath, String buildBasePath, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration)
   at Microsoft.DotNet.Tools.Test.ConsoleTestRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
```

I have tried latest `dotnet-test-xunit` on MyGet but still same problem.

Any plans to support net452 on mono?

cc @thecodejunkie @khellang

**Comment by qooroo** [comment]
typo now fixed in original post

**Comment by bradwilson** [comment]
External: https://github.com/dotnet/cli/issues/3073
