### ISSUE TITLE
dotnet test (dotnettest-xunit) working only on Windows

### ISSUE THREAD

**Issue by Dima4ka** [xunit/xunit#854]
Hi all,

I was trying to add tests to my ASP Core RC2 app.
I followed documentation and tutorials.

However, when I type `dotnet test` (being in the proper folder), there are different outputs on different systems.
### Mac OS X 10.11.5 (ERROR)

```
$ dotnet test
Project EShop (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Project EShop.UnitTests (.NETCoreApp,Version=v1.0) will be compiled because Input items added from last build
Compiling EShop.UnitTests for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:04.2629937


xUnit.net .NET CLI test runner (64-bit osx.10.11-x64)
  Discovering: EShop.UnitTests
System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
```
### Ubuntu 14.04 (ERROR)

```
# dotnet test
Project EShop (.NETCoreApp,Version=v1.0) will be compiled because Input items added from last build
Compiling EShop for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:10.0260974
Project EShop.UnitTests (.NETCoreApp,Version=v1.0) will be compiled because dependencies changed
Compiling EShop.UnitTests for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:05.3193905


dotnet-test Error: 0 : System.ComponentModel.Win32Exception: Success
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Test.ConsoleTestRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
```
### Windows 10 (SUCCESS)

```
$ dotnet test
Project EShop (.NETCoreApp,Version=v1.0) will be compiled because Input items removed from last build
Compiling EShop for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:09.6015473
Project EShop.UnitTests (.NETCoreApp,Version=v1.0) will be compiled because dependencies changed
Compiling EShop.UnitTests for .NETCoreApp,Version=v1.0

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.9926299


xUnit.net .NET CLI test runner (64-bit win10-x64)
  Discovering: EShop.UnitTests
  Discovered:  EShop.UnitTests
  Starting:    EShop.UnitTests
    EShop.UnitTests.Services.Test.FailingTest [FAIL]
      Assert.Equal() Failure
      Expected: 5
      Actual:   4
      Stack Trace:
        C:\Users\Dmytro\Source\Repos\shevastreameshop\test\EShop.UnitTests\Services\Test.cs(17,0): at EShop.UnitTests.Services.Test.FailingTest()
  Finished:    EShop.UnitTests
=== TEST EXECUTION SUMMARY ===
   EShop.UnitTests  Total: 2, Errors: 0, Failed: 1, Skipped: 0, Time: 0.420s
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
```
### Observation

I have figured out that at least on Mac if I remove `"EShop": "1.0.0",` from dependencies it works fine. Notice, I do not use this dependency in code, it is just in `project.json`.
### Code

Here are some code pieces:

EShop `project.json`:

``` json
{
    "version": "1.0.0",
    "authors": [
        "Dmytro Bogatov"
    ],
    "dependencies": {
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-*",
        "Npgsql": "3.1.0",
        "Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.0-rc2-release1",
        "Npgsql.EntityFrameworkCore.PostgreSQL.Design": "1.0.0-rc2-release1",
        "Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-*",
        "Microsoft.EntityFrameworkCore.SqlServer.Design": "1.0.0-*",
        "Microsoft.EntityFrameworkCore.Sqlite": "1.0.0-*",
        "Microsoft.EntityFrameworkCore.Sqlite.Design": "1.0.0-*",
        "Microsoft.EntityFrameworkCore.InMemory": "1.0.0-*",
        "Microsoft.ApplicationInsights.AspNetCore": "1.0.0-*",
        "Microsoft.AspNetCore.Authentication.Cookies": "1.0.0-*",
        "Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore": "1.0.0-*",
        "Microsoft.AspNetCore.Diagnostics": "1.0.0-*",
        "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.0.0-*",
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-*",
        "Microsoft.AspNetCore.Mvc": "1.0.0-*",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
        "Microsoft.AspNetCore.StaticFiles": "1.0.0-*",
        "Microsoft.AspNetCore.Razor.Tools": "1.0.0-*",
        "Microsoft.Extensions.Configuration.Json": "1.0.0-*",
        "Microsoft.Extensions.Configuration.UserSecrets": "1.0.0-*",
        "Microsoft.Extensions.Logging": "1.0.0-*",
        "Microsoft.Extensions.Logging.Console": "1.0.0-*",
        "Microsoft.Extensions.Logging.Debug": "1.0.0-*",
        "NetTelegramBotApi": "3.7.50926",
        "Microsoft.NETCore.Platforms": "1.0.1-*"
    },
    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "dnxcore50",
                "portable-net45+win8"
            ]
        }
    },
    "runtimes": {
        "osx.10.11-x64": {},
        "ubuntu.14.04-x64": {},
        "win7-x64": {}
    },
    "tools": {
        "Microsoft.AspNetCore.Razor.Tools": {
            "version": "1.0.0-preview1-final",
            "imports": "portable-net45+win8+dnxcore50"
        },
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
            "version": "1.0.0-preview1-final",
            "imports": "portable-net45+win8+dnxcore50"
        },
        "Microsoft.EntityFrameworkCore.Tools": {
            "version": "1.0.0-preview1-final",
            "imports": [
                "portable-net45+win8+dnxcore50",
                "portable-net45+win8"
            ]
        },
        "Microsoft.Extensions.SecretManager.Tools": {
            "version": "1.0.0-preview1-final",
            "imports": "portable-net45+win8+dnxcore50"
        },
        "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
            "version": "1.0.0-preview1-final",
            "imports": [
                "portable-net45+win8+dnxcore50",
                "portable-net45+win8"
            ]
        }
    },
    "runtimeOptions": {
        "gcServer": false,
        "gcConcurrent": true
    },
    "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true,
        "compile": {
            "exclude": [
                "wwwroot",
                "node_modules"
            ]
        }
    },
    "publishOptions": {
        "include": [
            "appsettings.json",
            "wwwroot",
            "Views"
        ],
        "exclude": [
            "**.user",
            "**.vspscc"
        ]
    },
    "scripts": {
        "prepublish": [
            "npm install",
            "bower install  --allow-root"
        ]
    }
}
```

tests `project.json`:

``` json
{
    "version": "1.0.0",
    "authors": [
        "Dmytro Bogatov"
    ],
    "buildOptions": {
        "warningsAsErrors": true
    },
    "dependencies": {
        "dotnet-test-xunit": "1.0.0-*",
        "Microsoft.NETCore.Platforms": "1.0.1-*",
        "EShop": "1.0.0",
        "XUnit": "2.1.0"
    },
    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "dnxcore50",
                "portable-net451+win8"
            ],
            "dependencies": {
                "Microsoft.NETCore.App": {
                    "version": "1.0.0-*",
                    "type": "platform"
                }
            }
        }
    },
    "runtimes": {
        "osx.10.11-x64": {},
        "ubuntu.14.04-x64": {},
        "win7-x64": {}
    },
    "testRunner": "xunit",
    "commands": {
        "test": "xunit.runner.dnx"
    }
}
```

The only one test file:

``` c#
using Xunit;
//using EShop.Services;

namespace EShop.UnitTests.Services
{
    public class Test
    {
        [Fact]
        public void PassingTest()
        {
            Assert.Equal(4, Add(2, 2));
        }

        [Fact]
        public void FailingTest()
        {
            Assert.Equal(5, Add(2, 2));
        }

        int Add(int x, int y)
        {
            return x + y;
        }
    }
}
```

Thank you in advance!

**Comment by filipw** [comment]
I'm getting the exact same error on OS X

```
xUnit.net .NET CLI test runner (64-bit .NET Core osx.10.11-x64)
  Discovering: Foo.WebApi.IntegrationTests
System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler.
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
```

using `"dotnet-test-xunit": "2.2.0-preview2-build1029"`

**Comment by bradwilson** [comment]
Given that `dotnet-test-xunit` is built on/for dead-end technology (namely, `project.json`), it's unlikely that we will make any effort to fix any issues with it.

**Comment by filipw** [comment]
I think you can close it anyway, it's another manifestation of the `Too many open files` bug so it's OSS X's fault.
