### ISSUE TITLE
Could not load file or assembly 'xunit.runner.utility.desktop, Version=2.1.0.3179, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies

### ISSUE THREAD

**Issue by davidpeden3** [xunit/xunit#862]
I have a test assembly with the following `project.json`:

`{
	"version": "1.0.0-rc2-*",
	"testRunner": "xunit",
	"dependencies": {
		"xunit": "2.1.0",
		"dotnet-test-xunit": "1.0.0-rc2-*"
	},
	"frameworks": {
		"dnx46": {
		}
	}
}`

When I run `dotnet test`, I get the following error:

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'xunit.runner.utility.desktop, Version=2.1.0.3179, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The system cannot find the file specified.
   at Xunit.Runner.DotNet.Program..ctor()
   at Xunit.Runner.DotNet.Program.Main(String[] args)
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.

The build output folder contains the following xunit assemblies:

- xunit.abstractions.dll
- xunit.assert.dll
- xunit.core.dll
- xunit.execution.dotnet.dll
- xunit.runner.reporters.dotnet.dll
- xunit.runner.utility.dotnet.dll

If I manually copy `xunit.runner.utility.desktop.dll` into the folder, the tests run.

Why is this file expected to be present?
Why isn't it present?
What do I need to do to solve this properly?

**Comment by davidpeden3** [comment]
After reading my post, I instantly saw the problem. I had failed to change the target framework from `dnx46` to `net46`. This issue can be closed.
