### ISSUE TITLE
-method option is not documented

### ISSUE THREAD

**Issue by lgreenlee** [xunit/xunit#981]
The very important command line option `-method` of `dotnet test` is not in the `dotnet test --help` output.

**Comment by bradwilson** [comment]
It is documented on `dotnet test -help`. Using `--help` invokes the .NET CLI help. Unfortunately, we have no control over this at this point in time.

Compare:

```
$ dotnet test --help
.NET Test Driver

Usage: dotnet test [arguments] [options]

Arguments:
  <PROJECT>  The project to test, defaults to the current directory. Can be a path to a project.json or a project directory.

Options:
  -?|-h|--help                        Show help information
  --parentProcessId                   Used by IDEs to specify their process ID. Test will exit if the parent process does.
  --port                              Used by IDEs to specify a port number to listen for a connection.
  -c|--configuration <CONFIGURATION>  Configuration under which to build
  -o|--output <OUTPUT_DIR>            Directory in which to find the binaries to be run
  -b|--build-base-path <OUTPUT_DIR>   Directory in which to find temporary outputs
  -f|--framework <FRAMEWORK>          Looks for test binaries for a specific framework
  -r|--runtime <RUNTIME_IDENTIFIER>   Look for test binaries for a for the specified runtime
  --no-build                          Do not build project before testing
```

to:

```
$ dotnet test -help

xUnit.net .NET CLI test runner (64-bit .NET Core win10-x64)
Copyright (C) 2016 .NET Foundation.
usage: dotnet-test-xunit [configFile.json] [options] [reporter] [resultFormat filename [...]]

Valid options:
  -nologo                : do not show the header message
  -nocolor               : do not output results with colors
  -failskips             : convert skipped tests into failures
  -parallel option       : set parallelization based on option
                         :   none        - turn off all parallelization
                         :   collections - only parallelize collections
                         :   assemblies  - only parallelize assemblies
                         :   all         - parallelize collections and assemblies
  -maxthreads count      : maximum thread count for collection parallelization
                         :   default   - run with default (1 thread per CPU thread)
                         :   unlimited - run with unbounded thread count
                         :   (number)  - limit task thread pool size to 'count'
  -wait                  : wait for input after completion
  -diagnostics           : enable diagnostics messages for all test assemblies
  -trait "name=value"    : only run tests with matching name/value traits
                         : if specified more than once, acts as an OR operation
  -notrait "name=value"  : do not run tests with matching name/value traits
                         : if specified more than once, acts as an AND operation
  -method "name"         : run a given test method (should be fully specified;
                         : i.e., 'MyNamespace.MyClass.MyTestMethod')
                         : if specified more than once, acts as an OR operation
  -class "name"          : run all methods in a given test class (should be fully
                         : specified; i.e., 'MyNamespace.MyClass')
                         : if specified more than once, acts as an OR operation
  -namespace "name"      : run all methods in a given namespace (i.e.,
                         : 'MyNamespace.MySubNamespace')
                         : if specified more than once, acts as an OR operation
  -noautoreporters       : do not allow reporters to be auto-enabled by environment
                         : (for example, auto-detecting TeamCity or AppVeyor)

Reporters: (optional, choose only one)
  -appveyor              : forces AppVeyor CI mode (normally auto-detected)
  -json                  : show progress messages in JSON format
  -quiet                 : do not show progress messages
  -teamcity              : forces TeamCity mode (normally auto-detected)
  -verbose               : show verbose progress messages

Result formats: (optional, choose one or more)
  -xml <filename>        : output results to xUnit.net v2 style XML file
```

**Comment by FanMix** [comment]
But on my comp `dotnet test -help` provide error message (Exception).

c:\MyFolder\dotnet test -help
dotnet-test Error: 0 : System.InvalidOperationException: C:\Dev\Lendoit\BackEnd\project.json does not exist.
   at Microsoft.DotNet.Tools.Test.TestCommand.GetProjectPath(String projectPath)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)

**Comment by shanselman** [comment]
Ping @blackdwarf

**Comment by bradwilson** [comment]
Closed for age.
